### ISSUE TITLE
HSAttachmentPicker Image Not Found

### ISSUE THREAD

**Issue by ay8s** [helpscout/beacon-ios-sdk#1]
Beacon install method: Cocoapods

**Actual outcome**
Including Beacon in the Buffer project resulted in a "dyld: Library not loaded" error for the HSAttachmentPicker. With the reason "Image not found".

```
dyld: Library not loaded: @rpath/HSAttachmentPicker.framework/HSAttachmentPicker
  Referenced from: /Users/andrewyates/Library/Developer/CoreSimulator/Devices/C65E2427-8CFE-4B9D-9FCD-06232CC6B560/data/Containers/Bundle/Application/FC140322-2806-408B-818F-27255184BEC0/Buffer.app/Frameworks/Beacon.framework/Beacon
  Reason: image not found
```

**Comment by ay8s** [comment]
Will give that a shot shortly and let you know 👍

**Comment by ay8s** [comment]
Actually seeing this with HSAttachmentPicker 1.0.8 @jgritman.

**Comment by jgritman** [comment]
Ah, I've tracked it down and can reproduce your error here! It looks like we've built the Pod in such a way that it needs `use_frameworks!` to be set in your `Podfile`.

We're looking into a way to package the Pod so it works as a static library (thus doesn't require that setting). If you want to experiment in the meantime, you can enable that setting for your project, though I know another one of our projects got wonky last time I tried that setting alongside the other non-framework Pods we use.

I'll let you know what we've found out tomorrow. Thanks for bearing with us with these beta hiccups!

**Comment by jgritman** [comment]
@ay8s Hey Andrew! We've re-worked our build so Beacon is a static framework now instead of a dynamic one. If you run a `pod repo update` and update to Beacon version `0.44` you'll pull down the latest.

This was tested with sample projects of every configuration we could think of, and hopefully, you should be good to go now. Let us know if you're still having any issues!

**Comment by ay8s** [comment]
Working well for me now 👍 

Curious if you have any apps released with Beacon? We'd ideally ship with it next month.

**Comment by jgritman** [comment]
@ay8s Great to hear! 

The Help Scout app has integrated the Beacon SDK since March. We have two other companies testing it out currently, but neither has released it in the App Store as far as we know.
