### ISSUE TITLE
Chat attachment option available regardless of attachments setting

### ISSUE THREAD

**Issue by NappyPirate** [helpscout/beacon-ios-sdk#101]
* Beacon version 2.0.1
* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

**Actual outcome**
After an agent has accepted a chat, the option to send an attachment in the chat is always displayed.

**Expected outcome**
The option to send an attachment in a chat should only display if the beacon is configured to "Allow Attachments"

**Screenshots or GIFs**
![Image 2020-09-02 at 2 12 12 PM](https://user-images.githubusercontent.com/6239901/92026854-46780680-ed27-11ea-80c6-ff0e431fd662.png)
![Image 2020-09-02 at 2 11 22 PM](https://user-images.githubusercontent.com/6239901/92026866-48da6080-ed27-11ea-9a73-f697e33e3a8e.png)

**Comment by codenameDuchess** [comment]
Hi @NappyPirate, thanks for reaching out. The attachment setting that's currently available relates exclusively to the contact form. That said, we'll raise the issue with our product team and see if we can accommodate your request with a similar setting for chat conversations. 

We'll report back once we've gotten a decision. Thanks again!

[Internal tracking ticket](https://helpscout.atlassian.net/browse/IOSSDK-333).

**Comment by ScottPetit** [comment]
Hey 👋 @NappyPirate ,

Thanks for reporting this, just wanted to write and let you know that as of the latest version (2.0.2) of the SDK Beacon now respects this property on both the contact form and chats.  If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
