### ISSUE TITLE
Session attributes are not read/set for live chats

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#103]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [x] Manual

**Actual outcome**
[Session attributes](https://developer.helpscout.com/beacon-2/ios/#session-attributes) are attached to the chat activity.

`sessionAttributes` callback on HSBeaconDelegate is only called for a contact form, but not for a new chat conversation. 

There is no custom session attributes on the live chat transcript in the web admin Mailbox either.

**Expected outcome**
Beacon should attach session attributes to chat sessions as well.

**Comment by codenameDuchess** [comment]
Hi @andreyz, thanks for bringing this to our attention. We appreciate it. We'll let you know once we've gotten this update into a release.

[Internal tracking ticket](https://helpscout.atlassian.net/browse/MOBILE-394).

**Comment by ScottPetit** [comment]
Hey 👋 @andreyz ,

Just wanted to let you know that in the latest version (2.1.2) chats will now include session attributes. You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md). Thanks for the suggestion.
