### ISSUE TITLE
handleWillPresentNotification should return a Bool

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#104]
* Beacon install method: [ ] Carthage, [ ] CocoaPods,  [x] Manual

**Actual outcome**
Beacon SDK method `handleWillPresentNotification` does not indicate if it has identified a Beacon notification and it will call `completionHandler` or app code should call `completionHandler` itself.

This creates a situation when either app code will always call `completionHandler` right after `handleWillPresentNotification ` method or will ignore non-Beacon notifications by omitting a call to `completionHandler`.

**Expected outcome**
Beacon SDK method `handleWillPresentNotification ` should return a Bool value indicating if it will call `completionHandler`. Alternatively provide an equivalent of `isBeaconPushNotification` method to be called before `handleWillPresentNotification`.

**Comment by ScottPetit** [comment]
Hey 👋  @andreyz thanks for the feedback.  I agree the API isn't the best and have [noted internally](https://helpscout.atlassian.net/browse/IOSSDK-339) to take a look at improving it.

In the meantime you can wrap the call to `handleWillPresentNotification` in a `isBeaconPushNotification` check like so:

```swift
if HSBeacon.isBeaconPushNotification(notification.request.content.userInfo) {
    HSBeacon.handleWillPresent(notification, withCompletionHandler: completionHandler)
}
```
and as of the latest version (2.0.1) Beacon will call the completionHandler appropriately in all of those cases.

**Comment by andreyz** [comment]
Thanks for the workaround @ScottPetit !

**Comment by ScottPetit** [comment]
Hey 👋 @andreyz ,

Just wanted to let you know we updated this method signature to return a `BOOL` in the latest version (2.1.2). You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).  Thanks for the suggestion.
