### ISSUE TITLE
Previous conversations button takes you to the wrong destination

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#108]
Beacon version: 2.0.1

Steps to reproduce. 

1: Open beacon ( chat disabled, docs enabled)
2: Send a message.
3: Wait for the "We're on it" page, and press "Previous Conversations"

Expected:
Pressing previous conversations should take you to previous conversations

Actual:
You are taken to the "Beacon home" page.

[RPReplay_Final1599816779.MP4.zip](https://github.com/helpscout/beacon-ios-sdk/files/5208058/RPReplay_Final1599816779.MP4.zip)

**Comment by ScottPetit** [comment]
Hey 👋  @sipersso,

Thanks for reporting this. I reproduced this locally and created an [internal ticket](https://helpscout.atlassian.net/browse/IOSSDK-352) to track it and let you know when it's resolved.  Thanks again.

**Comment by ScottPetit** [comment]
👋 Hey @sipersso,

Thanks for filing this. Just wanted to let you know that this should be resolved in the latest release (2.1.0). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
