### ISSUE TITLE
Can't enter email in non-secure mode after sending a message.

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#109]
Beacon version: 2.0.1

Steps to reproduce:
1: Open beacon in non secure mode. 
2: Send a message and close the beacon.
3: Open the beacon again. 

Actual:
Email field is hidden, and empty. Pressing "Send a message" will generate a "Please use a valid email adress" error message. This seem to be persistent and the only way to be able to send messages again is to restart the app. 

Expected:
Email field should never be hidden in non-secure mode. You should always be able to send messages using the beacon.

**Comment by ScottPetit** [comment]
Hey @sipersso, thanks for submitting it.  We're currently QAing a fix for this with https://github.com/helpscout/beacon-ios-sdk/issues/94 so I'm going to include the [internal ticket](https://helpscout.atlassian.net/browse/IOSSDK-325) we have for that one, and let you know when the fix is out.

**Comment by ScottPetit** [comment]
Hey 👋 @sipersso ,

Thanks for reporting this, just wanted to write and let you know that this is resolved with the latest version (2.0.2) of the SDK. If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
