### ISSUE TITLE
Chat not available even though set in settings

### ISSUE THREAD

**Issue by jasonwiener** [helpscout/beacon-ios-sdk#110]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
Beacon does not display chat as an option even though it is configured to do so via Settings on HelpScout, a CS rep is available, and it displays on Beacon for Web. Tapping **Get In Touch** or **Ask** simply routes to the email form.

**Expected outcome**
Beacon should display chat as an option 

**Screenshots or GIFs**
![Screen Shot 2020-09-13 at 9 39 10 AM](https://user-images.githubusercontent.com/204083/93023629-17725800-f5a5-11ea-99e4-4e998ccda203.png)
![Screen Shot 2020-09-13 at 9 39 13 AM](https://user-images.githubusercontent.com/204083/93023632-19d4b200-f5a5-11ea-99ec-2a354b6319dc.png)

**Additional comments**
FYI: In the Pod version installed, chatEnabled is not a settings attribute

**Comment by ScottPetit** [comment]
Hey 👋 @jasonwiener, since `chatEnabled` isn't a settings attribute can you confirm you're running the latest version (2.0.1) of Beacon.  You can do so by running

```
pod update Beacon
```

and confirming you see `Installing Beacon 2.0.1 (was x.x.x)` in the console output.  If you don't see that in the output you may need to change the version restrictions on Beacon in your pod file to something like

```
pod 'Beacon', '~> 2.0.1'
```

and then run `pod update Beacon`.

Let us know if you run into any issues with that.

**Comment by jasonwiener** [comment]
Hi @ScottPetit. You're spot on. We're running the `1.0.2` Pod. The project we're using is running 5.1. It complies with the `podspec` reqs (ios11+, swift5+). However, it appears the framework is compiled on 5.2 and not compatible with 5.1.

**Comment by ScottPetit** [comment]
Hey @jasonwiener so that issue should just resolve itself by upgrading your version of Xcode.  The latest version of Xcode is 11.7 but if you update to 11.6 then you should be good to go as well.  I'll update some of our documentation around min Xcode version to reflect that.

**Comment by ScottPetit** [comment]
Hey @jasonwiener,

I went ahead and updated the README to reflect Xcode 11.4 as the minimum version supported.  If updating Xcode didn't resolve your issue feel free to open up another issue.
