### ISSUE TITLE
SwiftUI Previews can not be rendered in Xcode 12 projects with Beacon included

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#112]
* Beacon install method: N/A

**Actual outcome**
Beacon framework supports only one compiler version. For example it prevents from using Xcode preview on Xcode 12 GM.

**Expected outcome**
Beacon should pre-build and support multiple toolchains with it's binary framework. Allowing for faster adoption of iOS technologies.

**Screenshots or GIFs**
```
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios11.0'
error: failed to build module 'Beacon' from its module interface; the compiler that produced it, 'Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)'
```

**Comment by ScottPetit** [comment]
Hey 👋  @andreyz,

So Beacon is built for distribution which should allow it be used with any Xcode from 11.4 on.  Also all summer we've been using Beacon in projects with Xcode 11.6/11.7 as well as the Xcode 12 betas.  All that said this seems like a random Xcode issue that some people ran into [here](https://stackoverflow.com/questions/51558933/error-unable-to-load-standard-library-for-target-arm64-apple-ios10-0-simulator).  Would it be possible to try some of those suggestions (basically delete derived data, restarting Xcode, cleaning, etc) and let us know where you end up?

Thanks.

**Comment by andreyz** [comment]
@ScottPetit try running a SwiftUI preview for any view in Xcode project with Beacon included and you'll see this "random" error. 

I've found a workaround, excluding arm64 architecture for debug builds.

**Comment by ScottPetit** [comment]
@andreyz so just to be clear without any changes (excluding arm64) you can continue to build your app to device and to the simulator without problem, **BUT** SwiftUI Previews won't work?

**Comment by andreyz** [comment]
> @andreyz so just to be clear without any changes (excluding arm64) you can continue to build your app to device and to the simulator without problem, **BUT** SwiftUI Previews won't work?

Yeap.

**Comment by sipersso** [comment]
I have seen this for a lot of my dependencies when using XCode 12.  If you are using Cocoapods you can add the following to your PodFile. This fixed the issue for me.

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        end
    end
end

```

**Comment by ScottPetit** [comment]
Hey 👋 @andreyz & @sipersso,

Just wanted to reach out and let you know that the latest version of Beacon (2.1.0) is now distributed as an `.xcframework` which from my testing plays nicely with SwiftUI and allows SwiftUI Previews to be rendered. If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by andreyz** [comment]
@ScottPetit this might solved as well then https://github.com/helpscout/beacon-ios-sdk/issues/113

**Comment by ScottPetit** [comment]
@andreyz yea I completely agree.  Unfortunately we don't have a great way of verifying that because of how we bundle Beacon in our own apps.  If you remember next time you do a release to remove the `Carthage` steps you had to add and could update the issue that'd be great.

**Comment by andreyz** [comment]
@ScottPetit checking now... The articles UI is looking good now too. Nice work!

**Comment by ScottPetit** [comment]
Hi @andreyz We discovered an issue with version 2.1.0 where under certain configurations Beacon wouldn't be able to be dismissed. Therefore we decided to remove 2.1.0 and aim to resolve this issue in the next release. We'll update you once this is released, thank you for your patience.

**Comment by andreyz** [comment]
Thanks for notifying. I won't update the app yet.

**Comment by andreyz** [comment]
@ScottPetit hope you can solve #124 with the next release too 🙌

**Comment by ScottPetit** [comment]
Hey 👋 @andreyz & @sipersso,

Just wanted to reach out and let you know that the latest version of Beacon (2.1.1) is now distributed as an .xcframework which from my testing plays nicely with SwiftUI and allows SwiftUI Previews to be rendered. If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
