### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#114]
**Actual outcome**
Beacon does not support integration via Swift Package Manager.

**Expected outcome**
Beacon should offer an SPM supported way to include SDK. Now that [SPM supports binary dependencies](https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages) in Swift 5.3.

**Comment by ScottPetit** [comment]
Hey 👋  @andreyz,

We plan on adding support for this in a future version and are tracking that [internally here](https://helpscout.atlassian.net/browse/IOSSDK-356).  We'll let you know when it's rolled out and available.

**Comment by rromanchuk** [comment]
obligatory +1 noise

**Comment by ScottPetit** [comment]
Hey 👋 @andreyz @rromanchuk @lewis-smith,

Thanks for the write up and easy repro steps. Just wanted to let you know that we added support for SPM in the latest version (2.1.2). You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).  Also you can get some integration help on [Swift Package Registry](https://swiftpackageregistry.com/helpscout/beacon-ios-sdk).

**Comment by andreyz** [comment]
Great job! Thank you @ScottPetit and the team
