### ISSUE TITLE
Clicking on push notification from a support agent replying does not take to the conversation

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#116]
Hello,
After replying a to user's conversation from Help Scout, the push notification sent to user, it seems like it does not open Beacon and take user to the conversation when clicking on push notification.

Steps to reproduce:
1. Make sure the Help Scout notification has been integrated in the app
2. Run the app, open Beacon and send a message
3. Go to Help Scout mail box, reply user's conversation
4. The app would receive push notification, click on notification
5. Notice that it will open the app instead of open Beacon and take user to the conversation

Beacon SDK: 2.0.1
Xcode version: 11.6
OS version: iOS 13

**Actual outcome**
Clicking on push notification does not open Beacon and take user to the conversation

**Expected outcome**
Clicking on push notification should open Beacon and take user to the conversation

Could you please help?
Thanks,
Binh

**Comment by scottyab** [comment]
Hey @BinhTNT I've just tried this on the SDK 2.0.2 and it works as expected here's a screen recording of it https://c.hlp.sc/OAuJ9ggB 

Can you confirm you're still seeing the issue with 2.0.2? 

Thanks.

**Comment by BinhTNT** [comment]
Hi @scottyab How can I have SDK 2.0.2 in my project?
I tried these in Podfile:
 pod 'Beacon', :git => 'https://github.com/helpscout/beacon-ios-sdk.git'
--> It give me SDK 2.0.1
 pod 'Beacon'
--> It give me SDK 1.0.5

**Comment by ScottPetit** [comment]
👋 @BinhTNT,

You should be able to use

```ruby
pod 'Beacon', '2.0.2'
```

I'd expect `pod 'Beacon'` to give you 2.0.2 but perhaps your Cocoapods source is a bit different.  As of Cocoapods 1.8 the recommended source is 'https://cdn.cocoapods.org/' which you can define at the top of your Podfile as

```ruby
source 'https://cdn.cocoapods.org/'
```

**Comment by BinhTNT** [comment]
Hi @ScottPetit I was able to integrate SDK 2.0.2. The issue is still happening. Is there any info that you need to figure out what i am missing? Thx

**Comment by ScottPetit** [comment]
Hey @BinhTNT, 

So the first step would be how you're initializing push notification support.  The two options are documented in our [docs](https://developer.helpscout.com/beacon-2/ios/#push-notifications-1).  Once we know which option you're initializing with we can have a better chance at debugging.  Although the docs would hopefully be able to guide you through getting it setup, let us know if that's not the case.

**Comment by BinhTNT** [comment]
Hi @ScottPetit 
I'm using initializeBeaconPushNotificationSupport method for initializing. I think it would be better for your investigation by sending you the source code files. Please check in attachment. Note that our project is using React Native, so please ignore which part of code related to it. Hope it would be helpful. Thanks

[hs_pn_src.zip](https://github.com/helpscout/beacon-ios-sdk/files/5280640/hs_pn_src.zip)

**Comment by ScottPetit** [comment]
Hey @BinhTNT,

Would you mind adding this to your AppDelegate.m around Line 126 in the `userNotificationCenter:didRecieveNotificationResponse:withCompletionHandler:` method.

```objc
NSDictionary *userInfo = response.notification.request.content.userInfo;
[[HelpScoutBeacon instance] handlePushNotification:userInfo];
```

That method should then look like

```objc
// IOS 10+ Required for localNotification event
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  [RNCPushNotificationIOS didReceiveNotificationResponse:response];
  NSDictionary *userInfo = response.notification.request.content.userInfo;
  [[HelpScoutBeacon instance] handlePushNotification:userInfo];
  completionHandler();
}
```

Pardon any typos, didn't have a compiler when I wrote those.  Let us know if that settles your problem.

**Comment by BinhTNT** [comment]
> Hey @BinhTNT,
> 
> Would you mind adding this to your AppDelegate.m around Line 126 in the `userNotificationCenter:didRecieveNotificationResponse:withCompletionHandler:` method.
> 
> ```objc
> NSDictionary *userInfo = response.notification.request.content.userInfo;
> [[HelpScoutBeacon instance] handlePushNotification:userInfo];
> ```
> 
> That method should then look like
> 
> ```objc
> // IOS 10+ Required for localNotification event
> - (void)userNotificationCenter:(UNUserNotificationCenter *)center
> didReceiveNotificationResponse:(UNNotificationResponse *)response
>          withCompletionHandler:(void (^)(void))completionHandler
> {
>   [RNCPushNotificationIOS didReceiveNotificationResponse:response];
>   NSDictionary *userInfo = response.notification.request.content.userInfo;
>   [[HelpScoutBeacon instance] handlePushNotification:userInfo];
>   completionHandler();
> }
> ```
> 
> Pardon any typos, didn't have a compiler when I wrote those. Let us know if that settles your problem.
