### ISSUE TITLE
Beacon does not prefill the contact form on the first try

### ISSUE THREAD

**Issue by lewis-smith** [helpscout/beacon-ios-sdk#117]
* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
Beacon did not prefill the contact form on the first try. It took two attempts before the form is filled

**Expected outcome**
Beacon should not need two attempts

**Screenshots or GIFs**
![CleanShot 2020-09-25 at 15 30 19](https://user-images.githubusercontent.com/1905433/94279485-15fd4400-ff44-11ea-8580-335b350c3b76.gif)

Code:
[HelpController.swift.zip](https://github.com/helpscout/beacon-ios-sdk/files/5283401/HelpController.swift.zip)

**Comment by scottyab** [comment]
Hi @lewis-smith thanks for the report, video and sample code. Can you confirm you are using the latest release 2.0.2 of the iOS SDK?

**Comment by lewis-smith** [comment]
Hi @scottyab , yes 2.0.2

```
PODS:
  - Beacon (2.0.2)
```

**Comment by BinhTNT** [comment]
Hello, I got the same issue. Beacon SDK 2.0.2
Thanks

**Comment by michalciurus** [comment]
I have the exact same problem

**Comment by ScottPetit** [comment]
Hey 👋  @lewis-smith, @BinhTNT & @michalciurus,

Just wanted to let y'all know that we've resolved this issue in the latest release (2.1.0).  This release updates the UI to be more in line with what you may have seen from Beacon Web or Beacon Android.  If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by ScottPetit** [comment]
Hi @lewis-smith We discovered an issue with version 2.1.0 where under certain configurations Beacon wouldn't be able to be dismissed. Therefore we decided to remove 2.1.0 and aim to resolve this issue in the next release. We'll update you once this is released, thank you for your patience.

**Comment by ScottPetit** [comment]
Hey 👋 @lewis-smith, @BinhTNT & @michalciurus,

Just wanted to let y'all know that we've resolved this issue in the latest release (2.1.1). This release updates the UI to be more in line with what you may have seen from Beacon Web or Beacon Android. If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
