### ISSUE TITLE
Unable to attach .MP4 file to beacon form

### ISSUE THREAD

**Issue by mehedihasan619** [helpscout/beacon-ios-sdk#119]
Device/OS: iPhone 11/iOS 14

Actual Result: Unable to attach .MP4 screen recording file to beacon contact us form

Steps to reproduce:

1. Navigate to beacon contact us form
2. Tap on the attachment icon
3. Try attaching  a .MP4 file

Expected Result: It should be possible to attach a .MP4 file that iOS produces natively so that our users can send us screen recording when we request them or when they wish.

Note: It is possible to attach the .mp4 file on Android.

**Comment by scottyab** [comment]
Hey @mehedihasan619 I've attempted to reproduce this issue with an .mp4 file but not seeing any errors attaching it or sending via contact form. What kind of error are you seeing? It would help greatly if you could share the .mp4 file with us so we can narrow this down. 

I used an mp4 from my local mac and one from this [sample website](https://www.appsloveworld.com/download-sample-mp4-video-mp4-test-videos/).  Also if you can confirm you are using the latest 2.0.2 version of the iOS SDK? 

Thanks, Scott

**Comment by mehedihasan619** [comment]
Hey, @scottyab I used one of the screen recordings.
Here is one of them https://drive.google.com/file/d/1dbLPiIiFzWwCEBG3OljUp1vwkBU7BFwI/view

Hi, @BinhTNT could you let us know which SDK version we are using currently?

**Comment by scottyab** [comment]
I'm unable to reproduce any issue with the file you've supplied. Here's a [screen recording](https://c.hlp.sc/jkuDr6G9) of me attaching the file linked above and sending the message successfully. 

I'm not clear on the error are you seeing? Please can you provide more details and/or screen recording 

Can you upgrade to latest 2.0.2 and confirm it's still an issue? 

Thanks, Scott

**Comment by mehedihasan619** [comment]
@scottyab Sorry for not attaching the error message in my last reply. 
Here is the screen recording: https://drive.google.com/file/d/1Sbx8NAtyrlYwwmush_nUXKoNlkTLKZju/view?usp=sharing

**Comment by scottyab** [comment]
Thanks for that, so the message is  "Media type unsupported" ![Image 2020-09-29 at 1 21 57 pm](https://user-images.githubusercontent.com/404105/94557679-ca55dd80-0256-11eb-8648-876f6668d1c8.png)

I'm guessing it's something to do with the output of your device's compression before the file it's being passed to the Beacon SDK. If its a native iOS file format it does feel like it should be supported I wonder if the default file type has changed in iOS 14? I'll confer with the team.

**Comment by scottyab** [comment]
It seems related to iOS 14 and the permissions choice. If we "Select Photos..." option from the permissions message we're seeing the media unsupported message (misleading error message). However everything works if we choose "Allow Access to All Photos".  I'll create a ticket to address.

**Comment by ScottPetit** [comment]
Hey 👋 @mehedihasan619 & @BinhTNT,

Just wanted to let you know that we've resolved this issue with the latest release (2.1.0).  Beacon now uses the `PhotosUI` framework on iOS 14 to not have to request permission to the users photo library.  If you'd like to see what else in this release please check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md)

**Comment by mehedihasan619** [comment]
Hey @ScottPetit,
Thanks for the update. Will keep on eye on this.

**Comment by ScottPetit** [comment]
Hey 👋 @mehedihasan619 & @BinhTNT,

Just wanted to let you know that we've resolved this issue with the latest release (2.1.0). Beacon now uses the PhotosUI framework on iOS 14 to not have to request permission to the users photo library. If you'd like to see what else in this release please check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by mehedihasan619** [comment]
Thanks for the update @ScottPetit 
We will upgrade to  2.1.1
