### ISSUE TITLE
Translatable accessibility labels

### ISSUE THREAD

**Issue by jonklo** [helpscout/beacon-ios-sdk#12]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [x] Manual

**Actual outcome**
The Back and Close buttons have English accessibility labels, used by VoiceOver.

**Expected outcome**
These should be translatable 😊

**Comment by jgritman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VoiceOver labels](https://trello.com/c/uEFHTONv/304-voiceover-labels)

**Comment by jgritman** [comment]
There are new accessibility labels for Back, Close, and Attach in our latest release. We've also improved the VoiceOver support for navigation as well.

You'll find the new translation [here](https://github.com/helpscout/beacon-ios-sdk/blob/master/Example/Beacon/en.lproj/BeaconLocalizable.strings#L32).
