### ISSUE TITLE
If you have sent an email using wrong adress, you can't change it. 

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#120]
Beacon version: 2.0.2

Steps to reproduce:
1: Start beacon (docs disabled, chat disabled and do not use pass an email to the HSBeacon user)
2: Enter an invalid email in the email field. For example invalid@example.com
3: Send the message
4: Close the beacon
5: Open the beacon again and press back to get to the "Ask field"

Expected:
I should be able to correct the email by entering a different email. 

Actual:
It is not possible to change the email. In fact, the email field is hidden until I restart the app.

**Comment by scottyab** [comment]
Hey @sipersso I'm seeing similar behavour. This could be related to the way iOS SDK is hanlding state 🤔  if you're seeing that the email address field is shown following an app restart. My understanding if it's a user input email we should be showing this in the contact form every times as you rightly point out it allows the user to amend an invalid email. 

I've created [internal ticket ](https://helpscout.atlassian.net/browse/IOSSDK-374) for this. Thanks for reporting! 🙇

**Comment by sipersso** [comment]
Thanks for confirming @scottyab!

**Comment by ScottPetit** [comment]
👋 Hey @sipersso,

Thanks for filing this.  Just wanted to let you know that this should be resolved in the latest release (2.1.0).  If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by ScottPetit** [comment]
Hi @sipersso, as you know, we discovered an issue with version 2.1.0 where under certain configurations Beacon wouldn't be able to be dismissed. Therefore we decided to remove 2.1.0 and aim to resolve this issue in the next release. We'll update you once this is released, thank you for your patience.

**Comment by ScottPetit** [comment]
👋 Hey @sipersso,

Thanks for filing this. Just wanted to let you know that this should be resolved in the latest release (2.1.1). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
