### ISSUE TITLE
Unable to close beacon. No Navigation Bar?

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#125]
Beacon version: 2.1.0

Steps to reproduce:
1: Open beacon 

Expected:
There should be an option to close the beacon and I should be able to see the contact options
Result:
There is no button to close the beacon. All I see is a search bar. The contact option is missing. See screenshot. 
![IMG_0580](https://user-images.githubusercontent.com/6479433/97629271-25cde380-1a2e-11eb-85f9-ea2b5393622e.PNG)

**Comment by sipersso** [comment]
This issue can be reproduced in your sample app as well.

**Comment by ScottPetit** [comment]
Hey @sipersso, 

I'm seeing the same thing with your Beacon.  I'm in the process of trying to figure out what's going as we haven't seen that with any of our other test Beacons.  I'll get back to you when I have more info and an internal issue we'll use for tracking it.

**Comment by ScottPetit** [comment]
Hey @sipersso,

So your initial assumption was correct in that the navigation bar was getting hidden.  We've filed it internally [here](https://helpscout.atlassian.net/browse/IOSSDK-411) and are working on getting it in a release shortly.

**Comment by ScottPetit** [comment]
👋 Hey @sipersso ,

Thanks for filing this. Just wanted to let you know that this should be resolved in the latest release (2.1.1). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

Also as a note we've updated our testing plans to include a wider array of Beacon configurations to limit the possibility of this sort of issue happening in the future.
