### ISSUE TITLE
User can't leave screen

### ISSUE THREAD

**Issue by adrianne-helpscout** [helpscout/beacon-ios-sdk#127]
@ScottPetit Thanks! Assets are loading normally for me now, but I found this problem:

[<img src="https://user-images.githubusercontent.com/551004/97701130-b1299200-1a8b-11eb-9733-7b3eca4579ba.png" width="320">](https://user-images.githubusercontent.com/551004/97701130-b1299200-1a8b-11eb-9733-7b3eca4579ba.png)

There is no way for the user to leave this screen after sending a message... it needs to close the app. Is there a way to resolve this problem in code?

_Originally posted by @rafaelks in https://github.com/helpscout/beacon-ios-sdk/issues/91#issuecomment-719504847_

**Comment by ScottPetit** [comment]
Hey 👋 @rafaelks,

So we have reports of another similar issue https://github.com/helpscout/beacon-ios-sdk/issues/125.  I just wanted to double check if it's the same issue or a separate one.  Are you seeing the navigation bar on the other screens of Beacon and just not on the confirmation screen?  E.G. the launch screen in `selfService` mode should look something like this:

![Simulator Screen Shot - iPhone 11 Pro - 2020-10-30 at 11 53 58](https://user-images.githubusercontent.com/2100009/97734129-bfd17280-1aa6-11eb-9c2d-fa141b3f008d.png)

Where you have the close button in the upper right corner and a title or in a different focus mode you could have ask and answers tabs like this screenshot:

![Simulator Screen Shot - iPhone 11 Pro - 2020-10-30 at 11 56 38](https://user-images.githubusercontent.com/2100009/97734313-0030f080-1aa7-11eb-8a9f-c5a4dbae1727.png)

**Comment by ScottPetit** [comment]
👋 Hey @rafaelks,

Thanks for filing this. Just wanted to let you know that this should be resolved in the latest release (2.1.1). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by rafaelks** [comment]
Awesome, thanks @ScottPetit :-)
