### ISSUE TITLE
Removing (or hiding) fields in get in touch form

### ISSUE THREAD

**Issue by zoufishanmehdi** [helpscout/beacon-ios-sdk#13]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [X] Manual

Hi, I wanted to remove "name" and "email" fields from helpscout 'get in touch' form in Swift. What's the best way of doing so? Would really appreciate your help. Thank you.

**Comment by jgritman** [comment]
Hello! The name field is configurable via the [web builder](http://c.hlp.sc/bb1014ca1209) or through the [`HSBeaconSettings` object](https://developer.helpscout.com/beacon-2/ios/#settings-customization).

However, the email field is required to send a message into Help Scout. If you already know the user's email address, you can provide it via the [HSBeacon login method](https://developer.helpscout.com/beacon-2/ios/#authenticating-users) before launching Beacon and it won't get displayed on the messaging form.

I hope that helps! Let us know if you have any other questions.
