### ISSUE TITLE
Build error SDK 2.1.1

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#130]
Hello,

I tried to upgrade SDK 2.1.1 but I got some errors when compiling our project. 

Xcode version: 12.1

Could you please help?

Here is the screenshot of errors and our project:

<img width="1010" alt="Screen Shot 2020-11-11 at 11 21 22 AM" src="https://user-images.githubusercontent.com/45462932/98784093-28b4d500-242d-11eb-9792-8743b975b6d1.png">

Pods project:
<img width="252" alt="Screen Shot 2020-11-11 at 2 55 00 PM" src="https://user-images.githubusercontent.com/45462932/98784658-07a0b400-242e-11eb-81d9-479e39f25553.png">

Pods configs:
<img width="746" alt="Screen Shot 2020-11-11 at 2 55 37 PM" src="https://user-images.githubusercontent.com/45462932/98784675-0bccd180-242e-11eb-8d38-bf40f53e03d8.png">

Thanks,
Binh

**Comment by scottyab** [comment]
Hey @BinhTNT - I'll ask one of our iOS engineers to take a 👀 at this in case there's something I'm missing. In the meantime are you able to get the [Beacon Example app](https://github.com/helpscout/beacon-ios-sdk/tree/master/Example) that's in this repo compiling and running on device?

I've just cloned this Beacon Example app, ran `pod update` opened the `Beacon Example.xcworkspace` and was able to run a-ok on a iPhone 7 simulator using Xcode 12.1. ❓ I'm seeing more files in the Pods/Beacon folder see below
![Image 2020-11-11 at 10 55 31 am](https://user-images.githubusercontent.com/404105/98803364-897fe580-240c-11eb-8f50-d92c36157deb.png)

**Comment by ScottPetit** [comment]
Hey @BinhTNT,

I just tried integrating Beacon 2.1.1 into my React Native test project and was able to do successfully.  Like @scottyab the Xcode project it generated looks a bit different than yours. 

<img width="779" alt="Screen Shot 2020-11-11 at 9 19 28 AM" src="https://user-images.githubusercontent.com/2100009/98829776-394e5680-23ff-11eb-80de-28a4b25aaf4d.png">

This could perhaps be a Cocoapods issue, can you confirm what version you're using with `pod --version`.  I generated the project using version `1.10.0` which had some updates for `XCFramework` that you can see [here](https://github.com/CocoaPods/CocoaPods/releases/tag/1.10.0)?  If you're on a previous version of Cocoapods, would you mind updating and reintegrating the dependencies?

**Comment by BinhTNT** [comment]
Hi @scottyab @ScottPetit You are right, the problem is about Cocoapods version. After upgrading Cocoapods to 1.10.0 and reinstalling the dependencies, the issue was resolved. Thanks a lot for your help!

**Comment by scottyab** [comment]
Thanks for the assist @ScottPetit
