### ISSUE TITLE
On iPad, back arrow to exit "Chat with our team" works inconsistently

### ISSUE THREAD

**Issue by jasonfator** [helpscout/beacon-ios-sdk#133]
Testing Beacon in our app on iPad, I found that the back arrow to get out of the "Chat with our team" doesn't work consistently.

**Technical Details:**

- Beacon install method: 
     [X] CocoaPods, 
- SDK version: 2.1.1
- iOS OS version: 14.1
- Device make/model: Apple iPad mini (5th gen) 
- Impacted user count: Unknown, this is in our current beta app 

**Steps to reproduce**
    1. Open Beacon 
    2. Tap the Support tab 
    3. Tap Get Support 
    4. Try to exit by tapping the back button at the upper left 

**Expected outcome**
    The back button works consistently to exit "Chat with our team" 

**Actual outcome**
    Beacon's back button doesn't work consistently to exit that modal

I recorded the gif below to demonstrate, but it a bit difficult to see what is happening—it doesn't show taps. I was tapping the back button repeatedly, adjusting the exact location of my taps, with no response. Most of the time I could eventually exit the modal, but it took several taps. 

**Screen Recording**
![99133566-605b8280-25cf-11eb-8f7d-397205a9efcd](https://user-images.githubusercontent.com/51142089/99859441-e6824680-2b44-11eb-8037-5a5a13b0b78c.gif)

**Comment by codenameDuchess** [comment]
Hi @jasonfator 👋, sorry for the trouble. Thanks for reporting this issue, and giving us excellent reproduction steps. We appreciate the screen recording too. We'll address this issue and let you know once a fix has been released.

[Internal tracking ticket](https://helpscout.atlassian.net/browse/IOSSDK-436)

**Comment by codenameDuchess** [comment]
@jasonfator 👋 Thanks for reporting this issue. We wanted to let you know we fixed this in the latest version (2.2.0). You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
