### ISSUE TITLE
Embedded videos not loading when viewing an article

### ISSUE THREAD

**Issue by NappyPirate** [helpscout/beacon-ios-sdk#134]
When viewing an article that contains a video loaded via an iframe, such as vimeo, the video is not displayed.

**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [X] CocoaPods, 
    [ ] Manual
- SDK version: 2.1.2
- iOS OS version: 14.2
- Xcode version: 12.2
- Device make/model: iPhone 11
- Impacted user count: All

**Actual outcome**

    No video is visible when viewing an article that contains a video.

**Expected outcome**

    Video should be visible and responsively sized like the web experience.

**Steps to reproduce**

    1. Create an article that contains a vimeo video
    2. Open Beacon
    3. View the article that contains the video

**Comment by jotaemepereira** [comment]
Hey @NappyPirate! I did some local testing embedding the following Vimeo video on an article, and I was able to reproduce the video correctly:

```html
<iframe src="https://player.vimeo.com/video/398636593" width="640" height="360" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
```

![Screen Shot 2020-11-24 at 09 55 54](https://user-images.githubusercontent.com/7924732/100097379-41fd4e80-2e3b-11eb-96d3-2bc3b2bfc4da.png)

Is it possible for you to send me the `iframe` you are testing? Or could you send me your Beacon ID and article id to help@helpscout.com (directed to the mobile team)? Thanks!

**Comment by NappyPirate** [comment]
After further investigation, this seems to only be occuring on the iOS simulator for me.

**Comment by jotaemepereira** [comment]
I will close the issue, feel free to re-open it if you find it is happening on real devices.
