### ISSUE TITLE
Question: Is Beacon using Firebase? If so how?

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#136]
I am having trouble with displaying Firebase InAppMessaging and since I just discovered that the Beacon framework is using Firebase on Android (https://github.com/helpscout/beacon-android-sdk-sample/issues/146 and 
https://github.com/helpscout/beacon-android-sdk-sample/issues/62) I just wanted to ask. 

Is Beacon for iOS using Firebase and if so, what modules? 

I am seeing duplicated calls from the FirebaseInAppMessaging framework which is preventing in app messages to be displayed, so I suspect that there might be a possibility that this is caused by third party code. The most likely problem is that it is my fault, but I just want to rule out that this doesn't have anything to do with HelpScout ;)

**Comment by hs-gv** [comment]
Hello @sipersso , we can confirm that the iOS Beacon SDK does not use Firebase at all.  Given the issue you are seeing, one suggestion would be to integrate the SDK [manually](https://developer.helpscout.com/beacon-2/ios/#manually), since Firebase maybe swizzling behind the scenes.
