### ISSUE TITLE
Beacon article rating # is not changing

### ISSUE THREAD

**Issue by mehedihasan619** [helpscout/beacon-ios-sdk#137]
Actual Result: When a user rates an article with a happy or sad emoji the rating # is not getting updated in the help scout web report.

Expected Result: Help scout report must be updated so that we can monitor and improve our articles.

Steps to replicate:

1. Visit https://secure.helpscout.net/reports/docs/ and take a note of the rating count
2. Now visit the android or iOS app and open an article to rate it
3. Wait for a while and check back the rating count at https://secure.helpscout.net/reports/docs/

iOS SDK Version: 2.1.2

**Comment by hs-gv** [comment]
Hello @mehedihasan619 , we've looked at this with 2.1.2, and we've been unable to duplicate this issue.  Viewing at the Docs reports after rating articles, it is certainly not real-time.  I've experienced at the longest a 10 minute delay, but the rating will eventually be displayed.  

On step 3, how long are you waiting for your ratings to appear on the report page?

**Comment by mehedihasan619** [comment]
Thanks, @hs-gv I think I have waited for more than 10 mins.
I will check again.

**Comment by mehedihasan619** [comment]
Hi @hs-gv,
I think we can close this out. I found out that it takes some time to update the report.

**Comment by codenameDuchess** [comment]
Hi @mehedihasan619 👋 Thanks for verifying. We appreciate it and will close this one out. Hope you have a good day!
