### ISSUE TITLE
Installation of Example App from Beacon results in compile erros

### ISSUE THREAD

**Issue by gandhikunal** [helpscout/beacon-ios-sdk#14]
* Beacon install method: [ X] Carthage, [X ] CocoaPods, [ ] Manual

I would like to integrate the beacon 2.0 ios sdk into my mobile application. In order to get a better understanding of the sdk I am trying to install and run your example app on my local machine and I am getting a build error.

I am running Xcode version 10.1 and as per the instructions on your webpage doing a pod install in the example directory and running into this particular build error:

Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_QLPreviewController", referenced from:
objc-class-ref in Beacon(HSBeaconConversationDetailsController.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

I have tried some additional setup options at my end in order to make it work, however keep running into compile errors as frameworks are not getting linked properly. Please kindly find below the different scenarios tried and the resulting errors

1) Tried to use carthage on your example app by creating a Cartfile and adding github "helpscout/beacon-ios-sdk" to it and the running carthage update from the example directory which results in the following error from carthage

*** Fetching beacon-ios-sdk
*** Fetching HSAttachmentPicker
*** Checking out HSAttachmentPicker at "1.0.8"
*** Checking out beacon-ios-sdk at "0.67"
*** xcodebuild output can be found in /var/folders/tb/c5pd4p4s1rn9pyxd5s3369mh0000gn/T/carthage-xcodebuild.sLrevW.log
*** Downloading HSAttachmentPicker.framework binary at "1.0.8"
*** Skipped building beacon-ios-sdk due to the error:
Dependency "beacon-ios-sdk" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/helpscout/beacon-ios-sdk/issues/new

2) Created a new single app project for testing and created a Cartfile with following content github "helpscout/beacon-ios-sdk"
and again ran carthage update command which results in the same error message as above

3) Created a new single app project for testing and created a Podfile with following content pod 'Beacon'
and running pod install command from the project root directory which results in the following build error

ld: warning: directory not found for option '-F/Users/kunal/Library/Developer/Xcode/DerivedData/Beacon-Test-grjkgjkqijxpkihdcckwaqluslgq/Build/Products/Debug-iphonesimulator/HSAttachmentPicker'
ld: framework not found HSAttachmentPicker
clang: error: linker command failed with exit code 1 (use -v to see invocation) 

For some reason with either of the dependency managers all the dependencies are not getting ported properly.

**Comment by samsymons** [comment]
Thanks for reporting this, @gandhikunal!

* The example app has now been updated to link `QuickLook.framework`
* The build instructions have been updated to clarify how to install Beacon if you aren't using CocoaPods

Let me know if you run into any other trouble!
