### ISSUE TITLE
Navigation issue when tapping Ask in secure mode

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#140]
Hello,

I found an issue with navigation in secure mode. When user open Beacon on first time after launching the app, then tap on Ask tab, it will open directly contact form but the top left back arrow is not visible, so user cannot go back to Ask screen to see Previous conversations. If user open Beacon again and tap on Ask tab, at this time it doesn't open contact form, but with email menu and Previous conversion button. It would be better if it always open contact form directly with back arrow button every time tapping Ask.

- SDK version: 2.1.2

**Actual outcome**

    Beacon open contact form without top left back arrow on first time open and tap on Ask

**Expected outcome**

    Beacon should open contact form with top left back arrow so that user can go back to Previous conversation

**Steps to reproduce**
    1. Make sure secure mode work fine, launch app
    2. Open Beacon, tap on Ask
    3. Notice that it opens contact form without top left arrow button
    4. re-open Beacon, tap on Ask
    5. Notice that it opens with email and previous conversation

**Screenshot**
First open (not OK)
![image-20201208-092447](https://user-images.githubusercontent.com/45462932/101576579-e4a4f800-3a0b-11eb-9bb1-a38ef1bbd668.png)

Re-open (OK)
![image-20201208-092512](https://user-images.githubusercontent.com/45462932/101576713-eec6f680-3a0b-11eb-8ca7-1bcfe299ca24.png)

Could you please check it?

Thanks,
Binh

**Comment by shaunmcilroy** [comment]
Hey @BinhTNT -- when you are activating Beacon for the first time (and you have not previously submitted a question) you won't see Previous Messages displayed. That will only appear after you've successfully created a conversation via Beacon.

Is that the process you're following when testing a new user accessing Beacon for the first time via the app? If you could include a screen recording of the process rather than screenshots to illustrate the entire flow you're following here that would be helpful.

**Comment by BinhTNT** [comment]
Hi @shaunmcilroy Sorry for letting you confusion, I meant every time when user launch app and open Beacon for first time, not newly user. Also, the identified email had previous conversations already. I uploaded the video, hope it would help
Thanks
https://drive.google.com/file/d/15LINXN1VLyZnXifGH7IHHsByCUpDd_rN/view?usp=sharing

**Comment by ScottPetit** [comment]
Hey @BinhTNT thanks so much for the video.  I was able to reproduce the issue here and we're tracking it [internally here](https://helpscout.atlassian.net/browse/IOSSDK-443).  We'll let you know when it's resolved.  Thanks again.

**Comment by codenameDuchess** [comment]
@BinhTNT 👋 Thanks for reporting this issue. We wanted to let you know we fixed this in the latest version (2.2.0). You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
