### ISSUE TITLE
Buttons don't respect safe area

### ISSUE THREAD

**Issue by lewis-smith** [helpscout/beacon-ios-sdk#142]
**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [x] CocoaPods, 
    [ ] Manual
**NB Y'all need to SPM here** 

- SDK version:
  - Beacon (2.1.2)

- iOS OS version:
14.2

- Device make/model:
iPhone XS

- Impacted user count:
Not sure, but I have no reason to believe it's not in the thousands.

**Actual outcome**

    Beacon UI did not respect the safe area

**Expected outcome**

    Beacon should respect the safe area

**Steps to reproduce**

    1… Open Beacon with docs enabled:
```
        let settings = HSBeaconSettings(beaconId:)
        settings.delegate = self
        settings.docsEnabled = docsEnabled
        
        HSBeacon.open(settings)
```
    2…
    3…

**Screenshots/Screen Recording**

![IMG_0165](https://user-images.githubusercontent.com/1905433/101816936-97af4780-3b19-11eb-937c-4be217810160.PNG)
![IMG_DC0868FFF033-1](https://user-images.githubusercontent.com/1905433/101816943-99790b00-3b19-11eb-8adb-c9c2c40f628f.jpeg)

**Additional Information**

The beacon is configured to "ask first" mode.
I have recreated this with two apps.

It's only cosmetic, but it's a bad look.

**Comment by ScottPetit** [comment]
Hey @lewis-smith thanks for the writeup and 100% agree that it's a bad look.  We're tracking this one internally [here](https://helpscout.atlassian.net/browse/IOSSDK-446) and will let you know when we have a fix available.

**Comment by ScottPetit** [comment]
👋 @lewis-smith,

Thanks for reporting this. I just wanted to reach out and let you know that we now properly respect safe areas in our latest version (2.2.3). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
