### ISSUE TITLE
Chat navigation bar doesn't follow appearance

### ISSUE THREAD

**Issue by js** [helpscout/beacon-ios-sdk#143]
The chat navigation bar doesn't seem to follow the same appearance rules as the other navigation bars. The chat backbutton is also looking slightly squeezed?

Also, it animates in slightly weird, in that the main navigation bar pops out while the chat navbar and content is pushed in.

The following HSBeaconSettings are set: `tintColorOverride`, `color`, and `useNavigationBarAppearance`

![image](https://user-images.githubusercontent.com/23626/101881019-1e086f80-3b94-11eb-89b8-df9b70d7637c.png)
![image](https://user-images.githubusercontent.com/23626/101881142-45f7d300-3b94-11eb-97e0-9e67e0bfb47d.png)
_(Norwegian locale)_

**Comment by ScottPetit** [comment]
👋 @js,

Thanks for filing the issue.  We'll have some fixes for this in our next release and are tracking it internally [here](https://helpscout.atlassian.net/browse/IOSSDK-442).  We've also added some tests to validate Beacons configured with white look appropriate as that was something we hadn't really run into before.

**Comment by codenameDuchess** [comment]
@js 👋 Thanks for reporting this issue. We wanted to let you know we fixed this in the latest version (2.2.0). You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
