### ISSUE TITLE
Failed App Store Submit due to Beacon.framework

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#144]
**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [ ] CocoaPods, 
    [x] Swift Package Manager,
    [ ] Manual
- SDK version: 2.1.2 (checkout from `master` to avoid 'dSYM issue')
- iOS OS version: 14.3
- Device make/model: n/a
- Impacted user count: n/a

**Actual outcome**

    Beacon prevented submission to App Store.

**Expected outcome**

    Beacon shouldn't event make me think about it during submit.

**Steps to reproduce**

    1.. Include Beacon with SPM via master branch commit 5b19237)
    2…Build for Archive
    3…Upload to App Store and receive error and a warning caused by Beacon.

**Additional Information**

The project contains WidgetKit Extension.

App Store Connect output:
```
App Store Connect Operation Error
ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'net.helpscout.beacon' under the iOS application 'App.app'."

App Store Connect Operation Warning
WARNING ITMS-90806: "CFBundleIdentifier collision. Each bundle must have a unique bundle identifier. The bundle identifier 'net.helpscout.beacon' is used in the bundles '[Payload/App.app/Frameworks/Beacon.framework, Payload/App.app/PlugIns/Beacon.framework]'"
```

**Comment by andreyz** [comment]
Once I deleted a second Beacon.framework from PlugIns folder, the submit went through.

**Comment by ScottPetit** [comment]
Hey @andreyz,

Let me take a look at some SPM docs and see about a workaround for that, or if Apple even considered how to handle binary SPM frameworks included with multiple targets.  

I'm assuming though you don't actually want to include Beacon with your WidgetKit extension?  Could you check if `Beacon-iOS` is included in the "Link Binary with Libraries" Build Phase for the WidgetKit extension?  If so, and you really don't want to include it with your WidgetKit extension I'd say remove `Beacon-iOS` from that Build Phase.

**Comment by andreyz** [comment]
Yeah, I do not include, link or reference Beacon from the WidgetKit code. Double checked just now and even deleted and re-added Beacon SDK to make sure. No change.

Some research brought up similar issues in [other SDKs](https://github.com/DataDog/dd-sdk-ios/pull/182) and it seems either solved by adding platform specific suffixes to SDK targets (tvOS, iOS, etc) or some tweaking in the SDK project's build settings.

**Comment by ScottPetit** [comment]
Hey @andreyz,

I get how adding platform specific suffixes would fix this problem in those cases, but since Beacon is iOS only and we can't specify a suffix for use in App Extensions I don't think that would solve this problem.  The conclusion I've come to is the same from this [issue](https://github.com/usabilla/usabilla-u4a-ios-swift-sdk/issues/210) that it's an Xcode/SPM bug that can only be worked around manually or by running a script to remove the framework from the WidgetKit extension (since Xcode shouldn't be adding it there in the first place).

I'm going to look for a FB# to duplicate otherwise I'll create a new one and link it to this issue.

**Comment by andreyz** [comment]
@ScottPetit this might be helpful https://bugs.swift.org/browse/SR-13840 and https://forums.swift.org/t/swift-package-binary-framework-issue/41922

**Comment by andreyz** [comment]
This clearly [Xcode/SPM fault](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_4-rc-release-notes/).

**Comment by andreyz** [comment]
FYI Xcode 12.5 beta 1 already fixes that issue.
