### ISSUE TITLE
NSInvalidArgumentException crash on launch

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#146]
**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [ ] CocoaPods, 
    [x] Swift Package Manager,
    [ ] Manual
- SDK version: 2.1.2 (commit 5b19237 on main)
- iOS OS version: iOS 13.3
- Device make/model: iPhone 6s Plus
- Impacted user count: n/a

**Actual outcome**

    Beacon crashed on presentation.

**Expected outcome**

    Beacon shouldn't crash the app.

**Steps to reproduce**

    1. Launch app
    2. Present contact us or answers page
    3. Crash 💣 ☠️ 

**Additional Information**

Only happens in Release builds.

Console:
```
2020-12-21 19:15:57.464650+0100 App[5275:1508235] Beacon: Requesting Beacon Font Icon attributed string with nil color, using charcoal instead
2020-12-21 19:15:57.685001+0100 App[5275:1508235] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(0x1ab5daa48 0x1ab301fa4 0x1ab630360 0x1ab6396b4 0x1ab4c773c 0x1ab4b95d0 0x107007b58 0x106fde67c 0x1070270dc 0x1070268e0 0x1af02e920 0x1af033430 0x1aefa5510 0x1aefa582c 0x1aefa66f4 0x1aefa9660 0x1af04062c 0x1aefa8c70 0x107035844 0x106fd59d4 0x1087bd7fc 0x1087bebd8 0x1087ccc34 0x1ab5585e4 0x1ab5535d8 0x1ab552adc 0x1b54d8328 0x1af64dae0 0x1e03d1694 0x1051d3890 0x1051d3808 0x1051d38d4 0x1ab3dc360)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
terminating with uncaught exception of type NSException
```

Stack trace:
```
#0	0x00000001ab5daa48 in __exceptionPreprocess ()
#1	0x00000001ab301fa4 in objc_exception_throw ()
#2	0x00000001ab630360 in _CFThrowFormattedException ()
#3	0x00000001ab6396b4 in -[__NSPlaceholderDictionary initWithObjects:forKeys:count:].cold.4 ()
#4	0x00000001ab4c773c in -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] ()
#5	0x00000001ab4b95d0 in +[NSDictionary dictionaryWithObjects:forKeys:count:] ()
#6	0x0000000107007b58 in +[HSBeaconFontIcons attributedStringForIcon:color:size:] at /Users/travis/build/helpscout/beacon-ios-sdk-private/Beacon/Classes/Root/Utils/HSBeaconFontIcons.m:58
#7	0x0000000106fde67c in -[HSBeaconAnswersSearchBar setCenteredPlaceholder:] at /Users/travis/build/helpscout/beacon-ios-sdk-private/Beacon/Classes/Docs/UI/HSBeaconAnswersSearchBar.m:55
#8	0x00000001070270dc in -[HSBeaconSuggestionsContainerController setupSearchBar] at /Users/travis/build/helpscout/beacon-ios-sdk-private/Beacon/Classes/Docs/UI/HSBeaconSuggestionsContainerController.m:119
#9	0x00000001070268e0 in -[HSBeaconSuggestionsContainerController viewDidLoad] at /Users/travis/build/helpscout/beacon-ios-sdk-private/Beacon/Classes/Docs/UI/HSBeaconSuggestionsContainerController.m:67
#10	0x00000001af02e920 in -[UIViewController _sendViewDidLoadWithAppearanceProxyObjectTaggingEnabled] ()
#11	0x00000001af033430 in -[UIViewController loadViewIfRequired] ()
#12	0x00000001aefa5510 in -[UINavigationController _updateScrollViewFromViewController:toViewController:] ()
#13	0x00000001aefa582c in -[UINavigationController _startTransition:fromViewController:toViewController:] ()
#14	0x00000001aefa66f4 in -[UINavigationController _startDeferredTransitionIfNeeded:] ()
#15	0x00000001aefa9660 in -[UINavigationController pushViewController:transition:forceImmediate:] ()
#16	0x00000001af04062c in +[UIViewController _performWithoutDeferringTransitionsAllowingAnimation:actions:] ()
#17	0x00000001aefa8c70 in -[UINavigationController pushViewController:animated:] ()
#18	0x0000000107035844 in -[HSSuggestionsCoordinator start] at /Users/travis/build/helpscout/beacon-ios-sdk-private/Beacon/Classes/Coordinators/HSSuggestionsCoordinator.m:38
#19	0x0000000106fd59d4 in __68-[HSBeacon loadNewBeacon:postLoadCallback:signature:viewController:]_block_invoke_2 at /Users/travis/build/helpscout/beacon-ios-sdk-private/Beacon/Classes/HSBeacon.m:175
```

**Comment by ScottPetit** [comment]
Hey @andreyz,

I was just looking into this because we had a single user crash (on iOS 13.3 as well) in our iOS app this past week.  Are you consistently able to reproduce this or did this come from a crash report for your app out in the wild?

**Comment by andreyz** [comment]
@ScottPetit I can consistently reproduce this on my iPhone 6s Plus test device running iOS 13.3

**Comment by ScottPetit** [comment]
Hey @andreyz,

Unfortunately I don't have any better idea why this is happening on that device/OS combination.  We're tracking [internally](https://helpscout.atlassian.net/browse/IOSSDK-462) an issue to migrate from our use of a loaded Font Icon to just image assets which would solve this crash.  If you do run into this again, if you could check your logs for `Failed to load font:` which Beacon should be printing to the console in the case that it failed to load the icon font, that would be very handy.

**Comment by andreyz** [comment]
Thanks for looking into it @ScottPetit. The issue does appear obscure enough, that I've still submitted an update regardless.

I'll add the console logs here soon.

**Comment by ispiropoulos** [comment]
Hi! Just here to report that we faced the same issue on an iPhone 7 rocking iOS 13.3

**Comment by ScottPetit** [comment]
Hey @andreyz & @ispiropoulos 

Thanks for reporting this. I just wanted to reach out and let you know that we no longer use (as of the latest version 2.2.3) an icon font to render certain icons, and in doing so have removed the possibility of this crash occurring. If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
