### ISSUE TITLE
Problem report: Conversation history for a beacon contains messages from two different mailboxes

### ISSUE THREAD

**Issue by nikos-houssos-feel** [helpscout/beacon-ios-sdk#152]
**Technical Details:**

- SDK version: 2.1.2
- iOS OS version: 14.2
- Impacted user count: Everyone

**Actual outcome**

    Conversation history for beacon1 contains both the messages exchanged with mailbox1 (beacon1) and the messages exchanged with mailbox2 (beacon2).

**Expected outcome**

    Conversation history for beacon1 should contain the messages exchanged with mailbox1 (beacon1).

**Steps to reproduce**

    1…A mobile user has two beacons (beacon1, beacon2), each associated with a different mailbox (mailbox1, mailbox2). Mailbox1 and mailbox2 are each associated with a separate Helpscout account/mailbox.
    2…The user sends a message through beacon1 (mailbox1).
    3…The user sends a message through beacon2 (mailbox2).
    4…The user goes to conversation history for beacon1.

**Comment by codenameDuchess** [comment]
Hi @nikos-houssos-feel 👋 

Thank you for reporting this issue, and sorry for the trouble. I was able to reproduce this issue in both versions 2.1.2 and 2.2.0 and I've opened an [internal tracking ticket](https://helpscout.atlassian.net/browse/IOSSDK-474) for us to investigate.  We will let you know once we've had a chance to address it and get a fix into a release.

**Comment by nikos-houssos-feel** [comment]
Thank you @codenameDuchess 
Any estimate on when this fix is foreseen to make it into a release is very welcome. We need this for serving certain customer deployments.

**Comment by ScottPetit** [comment]
Hey 👋 @nikos-houssos-feel,

So we've been taking a look at this internally and believe this is working as expected from a users point of view.  Would you mind detailing for me how you're trying to use the multiple beacons and why you'd expect/want your users to not see conversations they were involved in based on the mailbox they're sent to?

**Comment by nikos-houssos-feel** [comment]
Hey @adrianne-helpscout, 

Many thanks for your reply. The use case that is not working for us due to this issue is a pretty common one: we have two different support mailboxes for the same group of users. Each mailbox covers a totally different area of support (i.e. one is technical support with the app and the other support for the provided content). These areas are operated by separate teams and have totally different scope and content. It does not make sense for a user to view a single conversation history for both support areas and it is very confusing since it will present unrelated content in the same view - this is why each support area should have its own conversation history.

I hope this makes our use case clear. I will be glad to provide more details, if needed.

**Comment by nikos-houssos-feel** [comment]
Hi @adrianne-helpscout 
Any update on this issue?

**Comment by shaunmcilroy** [comment]
Hi @nikos-houssos-feel - Shaun hopping in with @adrianne-helpscout. 

Beacon on the SDK follows the same principles in function as Beacon for the web, and as a result we don't have plans to change the existing, core behaviour of Beacon. Your feedback is helpful though, and I'll definitely filter it along to the teams for feedback should they look to make changes to the product down the road. 

In terms of a current fix, one suggestion would be to set the **enablePreviousMessages** boolean on the HSBeaconSettings object to False, overriding the Beacon Builder configuration and ensuring no access to previous conversations is available in Beacon for Mobile.

[Details here for iOS](https://developer.helpscout.com/beacon-2/ios/#settings-customization), and [for Android](https://developer.helpscout.com/beacon-2/android/#settings-customization).

While this will prevent users from viewing **any** previous conversations, regardless of mailbox, responses will continue to transmit between their email address and the mailbox in Help Scout without interruption. I'm sorry that we're unable to offer further workarounds but if this behaviour changes in the future we have your details on file and will keep you in the loop.

If you have any further questions or feature requests please let us know by opening a new issue. Thanks, Nikos.
