### ISSUE TITLE
HSBeaconDelegate sessionAttributes not called when user replies to previous conversation

### ISSUE THREAD

**Issue by artisanglobal** [helpscout/beacon-ios-sdk#159]
**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [X] CocoaPods, 
    [ ] Swift Package Manager,
    [ ] Manual
- SDK version: 2.2.0
- iOS OS version: All
- Device make/model: All
- Impacted user count: 1000s

**Actual outcome**

To help diagnose customer support issues, we include information about several user configurable app settings when a user submits a support request. This is done via the `HSBeaconDelegate` `sessionAttributes` delegate method, where we return a dictionary with the information. Often, we write back to the user with instructions to change one or more settings, and then they write back saying they did so - but we have no way to confirm the changes that they made because the `sessionAttributes` delegate method is not called when they reply to our message via the Previous Conversations button in the Beacon.

**Expected outcome**

Beacon should call the `sessionAttributes` delegate method every time the user sends a message, and include that information along with each message.

**Steps to reproduce**

    1. Add Beacon to a sample app and implement `HSBeaconDelegate` `sessionAttributes`
    2. Add some randomized data to the dictionary returned by `sessionAttributes`
    3. Send a support request from the app
    4. Reply to the support request from the dashboard
    5. Reply to the reply from the app via Previous Conversations
    6. Notice that the `sessionAttributes` delegate method is not called when replying. If it were, you would get different randomized data in the reply.

**Screenshots/Screen Recording**

    Please add any images or videos to support your report.

**Additional Information**

    Please attach any crash logs

**Comment by shaunmcilroy** [comment]
Hi @artisanglobal -- the Session Data is only written once to the Beacon note when a conversation is created, and not something that is designed or intended to create a new note for each subsequent follow up response within the same conversation. If a user were to create a new conversation that's when you'd see a fresh note with new session data included.

This is the default behaviour of Beacon, and is the same across all Beacon platforms including for web and Android. The alternative would be to write that data via [User Attributes in the customer profile](https://developer.helpscout.com/beacon-2/ios/#user-attributes) as and when each subsequent message comes in, though it will overwrite any previous values for those same fields in their customer profile. 

To build on that as a potential idea though, [you could have a Customer Updated webhook](https://c.hlp.sc/jkuLLzJg) send that information to you at an endpoint of your choosing, and you can either write it to the conversation as a note via the API, or store it in an offsite database of your choosing against that customers data.

Hope that helps you come up with a workaround to solve that problem @artisanglobal!
