### ISSUE TITLE
Carthage installation fails

### ISSUE THREAD

**Issue by alexmay23** [helpscout/beacon-ios-sdk#16]
* Beacon install method: [ ] Carthage

**Actual outcome**
Skipped building beacon-ios-sdk due to the error:
Dependency "beacon-ios-sdk" has no shared framework schemes for any of the platforms: iOS

**Expected outcome**
Beacon should be installed

**Comment by jgritman** [comment]
Hi Alex! The Carthage support is working again in build 0.72.

Let us know if you run into any problems!
