### ISSUE TITLE
In Dark mode, chat "Send" button background color changes to white when enabled and blends with the input field

### ISSUE THREAD

**Issue by yuliaveres** [helpscout/beacon-ios-sdk#160]
**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [ ] CocoaPods, 
    [x] Swift Package Manager,
    [ ] Manual
- SDK version: 2.2.1
- iOS OS version: 14.4.2
- Device make/model: iPhone 12 Pro Max
- Impacted user count: all users of our app who use dark mode

**Actual outcome**

     In Dark mode, chat "Send" button background color changes to white when enabled and blends with the input field

**Expected outcome**

    In Dark mode, chat "Send" button background color changes to a visible color when enabled and does not blend with the input field

**Steps to reproduce**

    1. Change device mode to Dark
    2. Open HSChatViewController
    3. Start typing in the message input field
    
**Screenshots/Screen Recording**

![RPReplay_Final1619514872](https://user-images.githubusercontent.com/27722554/116217841-414e4880-a74a-11eb-98b9-37bb13f21129.gif)

**Additional information**
Overriding `settings.color` to a custom color does not seem like a good solution in our case, since this causes issues to the navigation bar text contrast and it becomes  illegible. See screenshot attached.

<img src="https://user-images.githubusercontent.com/27722554/116218651-0862a380-a74b-11eb-973a-907d6fdce4e1.PNG" width="300">

**Comment by aliripe** [comment]
Hi @yuliaveres!

Thank you for reaching out and for the helpful images and gifs!

I've been able to reproduce the Send button "_dissappearing_" issue and I've created an internal ticket – [IOSSDK-483](https://helpscout.atlassian.net/browse/IOSSDK-483) – for us to look into it. Thank you for the report!

While we address this issue, my suggestion was going to be for you to use a different color if possible. However, it looks like you're having problems with that too. I've also tried to reproduce it but, unlike with the first one, I have been unable to do so.

I've tried setting the Beacon color through the Web and also by overriding the `HSBeaconSettings.color` field to a very similar color and both work as expected.

[<img src="https://user-images.githubusercontent.com/7792150/116230841-69dd3f00-a758-11eb-9036-52534492189b.jpeg" width="240">](https://user-images.githubusercontent.com/7792150/116230841-69dd3f00-a758-11eb-9036-52534492189b.jpeg)

Could you share the code where you set the Beacon's settings to see if we can help you debug this problem?

**Comment by yuliaveres** [comment]
Hi @aliripe , here is how I set the color:
```
let settings = HSBeaconSettings(beaconId: beaconID)
settings.color = TUIKitColor.BrandNew.eggYolk
```
We use `UINavigationBar.appearance().standardAppearance` with a light-ish background color, so I end up with the contrast issue. It would help if it was possible to change color of the navigation items on the chat view controller.

**Comment by aliripe** [comment]
Hi @yuliaveres,

Thank you for sending that information over!

The way you're setting the color on the Beacon is correct, however – and thank you so much for mentioning it – the call to `UINavigationBar.appearance().standardAppearance` is the one causing issues here because the changes that you make to `UINavigationBar.appearance()` apply to _every_ `UINavigation` created within the app, and that includes Beacon.

I'm going to add all these details to the original ticket and add your suggestion of being able to customize the navigation items' color. 

In the meantime, the workaround would be to not call `UINavigationBar.appearance().standardAppearance` until we release a new version with a fix.

We will make sure to keep you posted if there are any updates around this!

**Comment by nateirwin** [comment]
We're running into the same issue. We set `UINavigationBar.appearance().standardAppearance` in our AppDelegate, and it's not really an option for us to stop setting it there.

**Comment by ScottPetit** [comment]
Hey @nateirwin thanks for the additional report.  I recreated the issue you mentioned and totally get not being able to change the way you're configuring `UINavigationBar`s in your app.  We're tracking the [issue](https://helpscout.atlassian.net/browse/IOSSDK-494) and will let you know when we have a fix.

CC: @yuliaveres as this would apply to your setting of the `HSBeaconSettings.color` example as well.

**Comment by ScottPetit** [comment]
Hey @yuliaveres & @nateirwin,

I just wanted to reach out and let you know that we've resolved these issues (both the send button in dark mode, and the UINavigationBarApperance issue) in the latest release (2.2.3). If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
