### ISSUE TITLE
My Swift code doesn't find "BeaconRoute"/"HSBeaconRoute" 

### ISSUE THREAD

**Issue by ksilz** [helpscout/beacon-ios-sdk#161]
**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [X] CocoaPods, 
    [ ] Swift Package Manager,
    [ ] Manual
- SDK version: (latest CocoaPods)
- iOS OS version: 12.4
- Device make/model: Simulator
- Impacted user count: 5

**Actual outcome**

The sample code for navigating to a screen in the beacon doesn't compile because of "BeaconRoute"
https://developer.helpscout.com/beacon-2/ios/#navigate-to-a-specific-screen

**Expected outcome**

It should compile.

**Steps to reproduce**

Here's my code:

```
import Beacon

[...]

    if (questions) {
      HSBeacon.open(BeaconRoute.ask, settings)
    } else {
      HSBeacon.open(settings)
    }

```

**Screenshots/Screen Recording**

Here's the Xcode compiler output:

```
  /Users/karsten/workspaces/yhigh/apps/y_mobile/ios/Runner/AppDelegate.swift:38:21: error: cannot find 'BeaconRoute' in scope
          HSBeacon.open(BeaconRoute.ask, settings)
                        ^~~~~~~~~~~
```

I cloned your repo and found `HSBeaconRoute` as the enum. I then changed `BeaconRoute.ask` to `HSBeaconRoute.ask` in my code - but still got the same error. The second call `HSBeacon.open(settings)` compiles and works fine.

**Additional Information**

I'm compiling this as part of a Flutter project.

**Comment by codenameDuchess** [comment]
Hi @ksilz,
/
Thanks for reaching out and sorry for the trouble. We've run locally in Xcode and checked it out in a Flutter project as well. We think that dropping the "HSBeaconRoute/BeaconRoute" portion will get things moving again. Would you please give `HSBeacon.navigate(.ask, settings: settings)` a try and let us know how it goes?

**Comment by ksilz** [comment]
No such luck. Here's my updated code:
```
    let settings = HSBeaconSettings(beaconId: "XXX")

    if (questions) {
      HSBeacon.open(.ask, settings: settings)
    } else {
      HSBeacon.open(.answers, settings: settings)
    }
```

And here are the errors that Flutter spits out:

```
    /Users/karsten/workspaces/yhigh/apps/y_mobile/ios/Runner/AppDelegate.swift:38:37: error: extra argument 'settings' in call
          HSBeacon.open(.ask, settings: settings)
                                        ^~~~~~~~
    /Users/karsten/workspaces/yhigh/apps/y_mobile/ios/Runner/AppDelegate.swift:38:22: error: type 'HSBeaconSettings' has no member 'ask'
          HSBeacon.open(.ask, settings: settings)
                        ~^~~
    /Users/karsten/workspaces/yhigh/apps/y_mobile/ios/Runner/AppDelegate.swift:40:41: error: extra argument 'settings' in call
          HSBeacon.open(.answers, settings: settings)
                                            ^~~~~~~~
    /Users/karsten/workspaces/yhigh/apps/y_mobile/ios/Runner/AppDelegate.swift:40:22: error: type 'HSBeaconSettings' has no member 'answers'
          HSBeacon.open(.answers, settings: settings)
                        ~^~~~~~~
```

**Comment by ksilz** [comment]
Here's what does compile: `HSBeacon.open(settings)`

**Comment by codenameDuchess** [comment]
Hi @ksilz,

In your code sample you've got `HSBeacon.open` but I think you are intending to use `HSBeacon.navigate` instead. Would you please give `navigate` a try? Let us know if that has things working for you.

**Comment by ksilz** [comment]
You're absolutely right! That was stupid of me. Anyhow, here's my latest code and the compile error:

```
if (questions) {
  HSBeacon.navigate(.ask, beaconSettings: settings)
} else {
  HSBeacon.navigate(.answers, beaconSettings: settings)
}
```

Unfortunately, using the right API call doesn't change the fact that I still need to find these two enums somehow: 
```
/Users/karsten/workspaces/yhigh/apps/y_mobile/ios/Runner/AppDelegate.swift:42:26: error: type 'String' has no member 'ask'
      HSBeacon.navigate(.ask, beaconSettings: settings)
                            ~^~~
/Users/karsten/workspaces/yhigh/apps/y_mobile/ios/Runner/AppDelegate.swift:44:26: error: type 'String' has no member 'answers'
      HSBeacon.navigate(.answers, beaconSettings: settings)
                            ~^~~~~~~
```

**Comment by codenameDuchess** [comment]
Hi @ksilz,

Ok, so from the looks of this error it seems you might be pulling in an older version of Beacon before the Swift enum was added. Please take a look at your podfile.lock to confirm. The default version for Beacon with Flutter is version 1.0.5 and this is actually good news. For now we advise sticking with this older version. We believe that beyond version 2.0 you'd likely run into this [open issue we're investigating](https://github.com/helpscout/beacon-ios-sdk/issues/91#issuecomment-772590632) where Beacon assets don't always load. So

**Comment by codenameDuchess** [comment]
Hi @ksilz,

Ok, so from the looks of this error it seems you might be pulling in an older version of Beacon before this Swift enum was added. Please take a look at your podfile.lock to confirm. The default version for Beacon pulled in by Flutter projects is version 1.0.5, and this is actually somewhat good news. 

We believe that beyond version 2.0 you'd likely run into this [open issue we're currently investigating](https://github.com/helpscout/beacon-ios-sdk/issues/91#issuecomment-772590632) where Beacon assets don't always load for Flutter projects. 

For now, we advise sticking with this older version of Beacon and you can still call `navigate`. You'll just need to provide a String as you would if calling the Objective-C [example here](https://developer.helpscout.com/beacon-2/ios/#navigate-to-a-specific-screen). Navigation should be completed as expected with a few exceptions. 

The direct navigation for “ask” and “answers” was not yet available in this version so you’ll want to use "/ask/message/" and “/“ (home) respectively instead. We’re currently strategizing how to best resolve #91 and hope to have a solution there soon. But hopefully this work around will tide you over until then.

Again, sorry for the trouble, and we appreciate your patience.

**Comment by ksilz** [comment]
Confirmed: I've got `pod 'Beacon'` in my `Podfile` which resolved to `Beacon (1.0.5)` in my `Podfile.lock`. I should have mentioned this at the beginning!

And this code finally works:
```
    if (questions == true) {
      HSBeacon.navigate("/ask/message/", beaconSettings: settings)
    } else {
      HSBeacon.navigate("/", beaconSettings: settings)
    }
```

Thank you very much again for helping me!

**Comment by codenameDuchess** [comment]
You're welcome, happy to help. Thank you for opening this issue, @ksilz. It might be of help to other Flutter devs until we get #91 resolved.

**Comment by ScottPetit** [comment]
👋  @ksilz,

Just wanted to let you know that we just released Version [2.2.2](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md) of the SDK which resolved an issue loading assets in Flutter apps.

If you're targeting > iOS 11, then you can update the `platform` version in your Podfile and the Deployment target in the `Runner.xcodeproj` and upgrade to 2.2.2.  The 2.x releases include Chat, lots of bug fixes, and a much improved UI compared to 1.x.

**Comment by ksilz** [comment]
@ScottPetit My Flutter app targets iOS 10. So does that mean I should stay with version 1.0.5?

**Comment by ScottPetit** [comment]
@ksilz yes unfortunately so.  Beacon 2.x requires iOS 11+.  If your project eventually moves to iOS 11+ then feel free to upgrade.
