### ISSUE TITLE
Visibility of job title

### ISSUE THREAD

**Issue by outivartiainen** [helpscout/beacon-ios-sdk#163]
**Technical Details:**

- Beacon install method: 
    [ ] Carthage, 
    [ ] CocoaPods, 
    [x] Swift Package Manager,
    [ ] Manual
- SDK version: 2.2.1
- iOS OS version: 14.6
- Device make/model: iPhone X

**Actual outcome**

    The section informing person's name and his/her job title in chat is sometimes visible and sometimes not. The section has been managed to make visible only once by accident.

**Expected outcome**

    The section should be visible / invisible all the time or there should be on easy way to make it visible when using the chat.

![Bug1](https://user-images.githubusercontent.com/86602808/123633928-7b0efe80-d822-11eb-886a-fe09c2ecc466.PNG)
![Bug2](https://user-images.githubusercontent.com/86602808/123633946-7ea28580-d822-11eb-86ea-e73cb3f6b0d2.PNG)

**Comment by jotaemepereira** [comment]
Hey @outivartiainen, so what you are describing is a design decision not a bug.

When the header is collapsed we only show the avatar and the user name (2nd picture), when the header is expanded we show avatar, user name and role (1st picture).

Let us know if you have any other question.
