### ISSUE TITLE
iOS notifications

### ISSUE THREAD

**Issue by MaxMaxP** [helpscout/beacon-ios-sdk#166]
Thank you for taking the time to submit an issue with the details requested below. Our engineering team actively monitors issues submitted to this repo and will generally respond within 2 business days.

**Please note the following:**

- **Please ensure you are testing on the latest version of the SDK ahead of submitting a report.**
- **All reports are required to include steps to reproduce any issues reported.** 
- **Issues logged without this information may be closed until more information is made available.**

**Technical Details:**

- Beacon install method: 
    [ ] CocoaPods, 
- SDK version: the latest, just downloaded from Cocoapods
- iOS OS version: 14.7.1
- Device make/model: iPhone 12
- Impacted user count: for the moment nobody, still developing

**Actual outcome**

    Beacon is not sending notifications to the device when receiving new reply from me.

I added the following code in the willAppear of the main view:
DispatchQueue.main.async {
            UIApplication.shared.registerForRemoteNotifications()
            HSBeacon.initializeBeaconPushNotificationSupport()
        }

then, in AppDelegate didFinishLaunching:
HSBeacon.initializeBeaconPushNotificationSupport()

and in didRegisterForRemoteNotificationsWithDeviceToken:
HSBeacon.setDeviceToken(deviceToken)

**Comment by codenameDuchess** [comment]
Hi @MaxMaxP,

Thanks for reaching out. We've done a quick search and it doesn't look like we're received any new requests for setting up your APNS certificates. You'll need to email customer support according to [these instructions](https://developer.helpscout.com/beacon-2/ios/#push-notifications-1) in order to test push notifications. 

Also, just wanted to mention that if you aren't using secure mode for your Beacon you might consider switching to our [automatic push notification handling](https://developer.helpscout.com/beacon-2/ios/#automatic-handling). 

Hope this helps. If you've already sent your request with your certificates please send another note to help@helpscout.com with the details of your original request so that we can verify.

**Comment by MaxMaxP** [comment]
Thank you. I will send the certificate soon

I need another help. I’m not always in front of the desk, and I would like to give Chet to my users. Can I manage it by mobile?
I cannot use by web

Thanks 


Massimiliano Picchi

**Comment by shaunmcilroy** [comment]
Thanks @MaxMaxP - I'll keep an eye out for the certificate in our inbox. We don't support Chat on our mobile apps at this time for agent replies, though we are tracking requests. Please note that in your email regarding certificates also and we'll add you to the tracking list to update in the future.

**Comment by MaxMaxP** [comment]
It’s so bad, without chat it missing a big piece of the solution

 

 

Massimiliano

Waterspeed Team

 

Chat with us for support: https://www.facebook.com/messages/t/waterspeedapp

 

 

Thanks @MaxMaxP - I'll keep an eye out for the certificate in our inbox. We don't support Chat on our mobile apps at this time for agent replies, though we are tracking requests. Please note that in your email regarding certificates also and we'll add you to the tracking list to update in the future.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MaxMaxP** [comment]
Hi

I have deleted my account by mistake, but now I have deployed in my app.

Are you able to reactivate it quickly, please?

 

thanks

 

 

Massimiliano

Waterspeed Team

 

Chat with us for support: https://www.facebook.com/messages/t/waterspeedapp

 

 

From: Massimiliano Picchi ***@***.***>
Date: Wednesday, 18 August 2021 at 2:05 PM
To: helpscout/beacon-ios-sdk ***@***.***>, helpscout/beacon-ios-sdk ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [helpscout/beacon-ios-sdk] iOS notifications (#166)

 

It’s so bad, without chat it missing a big piece of the solution

 

 

Massimiliano

Waterspeed Team

 

Chat with us for support: https://www.facebook.com/messages/t/waterspeedapp

 

 

Thanks @MaxMaxP - I'll keep an eye out for the certificate in our inbox. We don't support Chat on our mobile apps at this time for agent replies, though we are tracking requests. Please note that in your email regarding certificates also and we'll add you to the tracking list to update in the future.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaunmcilroy** [comment]
Hi @MaxMaxP - your account has been restored and you're all set. Drop us an email if there's anything you need.

**Comment by MaxMaxP** [comment]
Thank you

 

 

Massimiliano

Waterspeed Team

 

Chat with us for support: https://www.facebook.com/messages/t/waterspeedapp

 

 

Hi @MaxMaxP - your account has been restored and you're all set. Drop us an email if there's anything you need.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MaxMaxP** [comment]
But not the portal is not sending the SMS to login

 

 

Massimiliano

Waterspeed Team

 

Chat with us for support: https://www.facebook.com/messages/t/waterspeedapp

 

 

From: Massimiliano Picchi ***@***.***>
Date: Monday, 6 September 2021 at 12:12 PM
To: helpscout/beacon-ios-sdk ***@***.***>, helpscout/beacon-ios-sdk ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [helpscout/beacon-ios-sdk] iOS notifications (#166)

 

Thank you

 

 

Massimiliano

Waterspeed Team

 

Chat with us for support: https://www.facebook.com/messages/t/waterspeedapp

 

 

Hi @MaxMaxP - your account has been restored and you're all set. Drop us an email if there's anything you need.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaunmcilroy** [comment]
Hi Max, I'll respond to you regarding this issue via the Help Scout support ticket you have open. We only provide support for the SDK via this platform. Talk soon.
