### ISSUE TITLE
Close button becomes invisible when replying to previous conversation

### ISSUE THREAD

**Issue by tiwoc** [helpscout/beacon-ios-sdk#168]
This is a followup to #160. The original issue is fixed for us in the main screen, but not in the screen that is shown when users reply to a previous conversation. This is because the navigation controller containing `HSBeaconPreviousMessagesReplyController` has a navigation bar that doesn't override the colors that we set globally in `UINavigationBar.appearance` (see screenshots below). Since we use a white background in light mode, the close button isn't visible there. In dark mode, everything's fine because we use a dark background.

**Technical Details:**

- Beacon install method: 
    [x] CocoaPods, 
- SDK version: 2.2.3
- iOS OS version: 14.7.1
- Device make/model: iPhone X
- Impacted user count: everyone who's using light mode

**Actual outcome**

In the navigation controller containing `HSBeaconPreviousMessagesReplyController`, the navigation bar title and background colors adjust to whatever we set globally in `UINavigationBar.appearance`.

**Expected outcome**

The navigation bar title and background colors should not adhere to the colors set in `UINavigationBar.appearance`, similar to how the rest of Beacon ignores these colors. Alternatively, the close button could adhere to the tint color of the navigation bar to keep it visible.

**Steps to reproduce**

1. Open Beacon
2. Tap on _Previous Conversations_
3. Tap on one of the conversations
4. Tap on _Reply_

**Screenshots/Screen Recording**

Simulator screenshots in dark mode and light mode:

<img width="403" alt="dark mode" src="https://user-images.githubusercontent.com/1260821/131626173-e1f1334f-aa0f-48f8-abc8-5aaa9becc513.png"> <img width="403" alt="light mode" src="https://user-images.githubusercontent.com/1260821/131626182-358234ac-0e43-4d34-8571-613bf2674c95.png">

Note how the close button is invisible in light mode because it has the same color as the background.

**Comment by aliripe** [comment]
Hi @tiwoc! 

Thank you so much for this report with clear repro steps and screenshots!

I've created a ticket for the team to investigate, and we will get back to you once we have a fix.

**Ticket:** [IOSSDK-496](https://helpscout.atlassian.net/browse/IOSSDK-496)

**Comment by ScottPetit** [comment]
Hey @tiwoc, I just wanted to reach and let you know that we've released a new version (2.2.4) that fixes this issue.  Thanks for the detailed writeup, and let us know if you run into any other issues.  If you want to see what else in this release feel free to check out our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).

**Comment by tiwoc** [comment]
Looks great. Thanks!
