### ISSUE TITLE
Question for SwiftUI usage

### ISSUE THREAD

**Issue by kennedycraig** [helpscout/beacon-ios-sdk#173]
Hi Folks,
I've scoured documentation and comments that I can find however I am unable to find any concrete suggestions on how to implement prefilled forms, using SWIFTUI as the platform. Can someone point me to where I can learn about this?

**Comment by ScottPetit** [comment]
Hey @kennedycraig,

You're right that our docs and examples don't have suggestions around implementing prefilled forms with SwiftUI.  We're tracking updating our docs or providing examples [internally here](https://helpscout.atlassian.net/browse/IOSSDK-509).  In the meantime I've put together a quick example of how you could do that:

```swift
import Beacon
import Foundation

class BeaconDelegate: NSObject, HSBeaconDelegate {

    static let shared = BeaconDelegate()
    var prefill: ((HSBeaconContactForm) -> Void)?
    var email: String?
    var name: String?
    var subject: String?
    var text: String?


    func prefill(_ form: HSBeaconContactForm) {
        if let prefill = prefill {
            prefill(form)
        } else {
            if let email = email {
                form.email = email
            }
            if let name = name {
                form.name = name
            }
            if let subject = subject {
                form.subject = subject
            }
            if let text = text {
                form.text = text
            }
        }
    }

}
```

This implementation has a couple of ways you could use and a few ways of extending it.  If you have all the data to profile the form when Beacon is being opened then you could just:

```swift
BeaconDelegate.shared.prefill = { form in
    form.name = "Name"
//  And so on for whatever properties you'd like to be prefilled
}
```

In a somewhat different case where the values you want to prefill are accumulated as your user goes through the app then you could use the individual vars for `email`, `name`, `subject` like `BeaconDelegate.shared.email = user.email`.

To use the delegate you just need to be sure to set it on the settings object that you're already creating:

`settings.delegate = BeaconDelegate.shared`

Just to call out that this is just a quick example, you want to include the ability to `reset` the delegate or may need to include other fields as needed.

Let us know if this helps you get it working, and we'll let you know when our examples/docs are more complete.

**Comment by kennedycraig** [comment]
Hey, Scott. Thanks so much. I was just about to go down this route and you jump started it for me. I really appreciated it. Already implemented the quick example and its heading exactly where I needed.

Craig
