### ISSUE TITLE
Status Bar Color Incorrect

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#19]
* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

**Actual outcome**
Beacon view controllers always present status bar content as dark/black.

**Expected outcome**
Beacon view controllers should adapt the status bar color based on the given color in settings, same as the title labels. For example, given a UIColor.black color setting, the status bar content should be white.

**Screenshots or GIFs**
![simulator screen shot - iphone xs - 2018-12-07 at 16 18 49](https://user-images.githubusercontent.com/171163/49673246-d8ac8700-fa3b-11e8-8783-ef8be8580261.png)
![simulator screen shot - iphone xs - 2018-12-07 at 16 20 05](https://user-images.githubusercontent.com/171163/49673293-fb3ea000-fa3b-11e8-9629-fed8fd57552e.png)

**Comment by jgritman** [comment]
Hey Curtis! How is the status bar color getting set in your app? I see it changes between the "Record" and "History"/"More" tabs. Are you implementing `preferredStatusBarStyle`?

We set and reset `UIApplication.sharedApplication.statusBarStyle` when opening/closing Beacon, but looks like that doesn't work for your case. I'll keep testing this out on my end and see if I can figure out where the problem is.

**Comment by parrots** [comment]
Yep, that's exactly how I'm doing it.

**Comment by parrots** [comment]
Wait, why did this get closed? `preferredStatusBarStyle` was presented as the way forward with regards to managing the status bar color in iOS 7, not manually changing it via `UIApplication.sharedApplication.statusBarStyle`.

You may want to look into setting `modalPresentationCapturesStatusBarAppearance` (defaults to NO) on the view controller that HSBeacon presents. Assuming those controllers properly comply to `preferredStatusBarStyle` everything should work OK, without having to manually capture the style on UIApplication.

**Comment by jgritman** [comment]
Oh, I don't know how that happened! Sorry about that! Thanks for the heads up on that setting!

**Comment by jgritman** [comment]
@parrots I've uploaded a new release (0.71) with `preferredStatusBarStyle` set on our modal controller, but it's still missing `modalPresentationCapturesStatusBarAppearance`. You can give that a try if you want, and I'll try to get another build with the modal setting out sometime over the weekend (I have to run out now).

**Comment by parrots** [comment]
0.71 seems to fix the status bar issue. Thanks for the quick turnaround!
