### ISSUE TITLE
Doesn't quite handle tables smoothly

### ISSUE THREAD

**Issue by ay8s** [helpscout/beacon-ios-sdk#2]
* Beacon install method: CocoaPods

**Actual outcome**
Beacon doesn't handle displaying tables smoothly. Users can't scroll horizontally to see hidden content.

**Expected outcome**
Beacon should allow for displaying tables that span further than the screen width. 

**Screenshots or GIFs**
![simulator screen shot - iphone x - 2018-08-14 at 14 29 45](https://user-images.githubusercontent.com/1058408/44119774-03f5afc6-9fcf-11e8-9071-a5471689ae8a.png)
![simulator screen shot - iphone x - 2018-08-14 at 14 29 21](https://user-images.githubusercontent.com/1058408/44119788-0cd68b74-9fcf-11e8-8520-da212d8aa7b3.png)

**Comment by jgritman** [comment]
It turns out this is an issue on all of our platforms (web & SDKs). We're hoping to push a new release out next week with a fix.

**Comment by jgritman** [comment]
Hi Andrew! We've pushed the new version of the SDK today (0.49) with updated CSS for scrolling/styling for tables longer than the screen width. Let us know if you're still seeing any issues.
