### ISSUE TITLE
[Enhancement] Use Tint Color

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#20]
* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

**Actual outcome**
Beacon did not respect the tint color of the containing app's UIWindow, instead using its own blue for links.

**Expected outcome**
Beacon should use the same tint color as the parent app, allowing for more seamless integration.

**Comment by jgritman** [comment]
We were hoping to get this updated today, but it's not as straightforward a change as we hoped. We'll let you know once it is ready to go!

**Comment by jgritman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tint color support for article links](https://trello.com/c/Wy7Z8U2T/305-tint-color-support-for-article-links)

**Comment by samsymons** [comment]
Hey @parrots! We've released Beacon SDK 1.0.1 which has a new flag, `tintColorOverride`, where you can set the color used for links throughout the SDK: https://github.com/helpscout/beacon-ios-sdk/blob/master/Beacon.framework/Headers/HSBeaconSettings.h#L103-L108

Let me know if this is what you're looking for. Thanks for the suggestion!
