### ISSUE TITLE
Related articles html entities not parsed

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#23]
In the Related Articles section, HTML entities seem not to be parsed properly. See screenshot below:

![e7e97299-e0df-4b85-8f43-f3b4bd084bb0](https://user-images.githubusercontent.com/792706/50722570-5f9f5e80-10d1-11e9-88d2-1710b853fe9a.png)

**Comment by jgritman** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Un-escape HTML in related articles preview](https://trello.com/c/8kRd0HD4/325-un-escape-html-in-related-articles-preview)

**Comment by jgritman** [comment]
Hi Bruno! Our API team made a change so this data is sent to the Beacon clients cleanly now, so you should no longer see this issue. 

Let us know if you run into any other bugs! Thanks!
