### ISSUE TITLE
Presenting beacon from a modal view

### ISSUE THREAD

**Issue by kcfancher** [helpscout/beacon-ios-sdk#24]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [X] Manual

**Actual outcome**
Our settings page is already a modally presented view controller, when we try to open beacon from that page it fails silently (presumably because it's trying to present on a presented view controller). 

**Expected outcome**
Beacon should present the ViewController, or allow us to initialize the view controller and use it as we see fit (in this instance push it onto our navigation controller).

**Comment by jgritman** [comment]
Hello! Sorry for the delayed response!

All of the various methods to launch the Beacon modal have overloaded implementations with a `from: UIViewController,` argument (example [here](https://developer.helpscout.com/beacon-2/ios-api/Classes/HSBeacon.html#/c:objc(cs)HSBeacon(cm)openBeacon:fromViewController:)) to help out with this specific case. Apple allows you to launch modal controllers from other modal controllers, so you'll be set if you pass in your presented modal as the `from:` argument.

We've looked into the navigation controller approach in the past but there are some aspects of our design that require the modal right now. It's a big effort on our end change that, but we'll keep it in mind for the future.

I hope that helps! Let us know if you're still running into issues!

**Comment by rromanchuk** [comment]
@jgritman doh, didn't even think to look if there were any other initialization signatures, this works great. Great product to add to helpscout, thanks for shipping this. 

Since a lot of times settings pages (common paradigm for getting help) is many times modally displayed might be worth it to throw a quick note in https://developer.helpscout.com/beacon-2/ios/

```swift
class MyModalViewController: UIViewController
  func open() {
    let settings = HSBeaconSettings(beaconId: "my-id")
    HSBeacon.open(settings, from: self)
  }
}
```

**Comment by ScottPetit** [comment]
https://helpscout.atlassian.net/browse/IOSSDK-29

**Comment by ScottPetit** [comment]
Closing this as the documentation has now been updated [here](https://developer.helpscout.com/beacon-2/ios/#usage)
