### ISSUE TITLE
Add delegate method when Beacon is hidden

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#25]
In our use case, it would be nice to have a Beacon delegate method to be notified of when the support screen is dismissed.

Suggested signature: `func beaconDidDismiss(_ beacon: HSBeacon)`

**Comment by adrianne-helpscout** [comment]
https://trello.com/c/4bgIcddy/350-notify-application-when-beacon-is-hidden

**Comment by jgritman** [comment]
In the next release, we'll have a few new delegate methods to support this (`onBeaconInitialOpen`, `onBeaconOpen`, `onBeaconInitialClose`, and `onBeaconClose`). I'll ping you here once that's out.

**Comment by jgritman** [comment]
Hi Bruno! These methods are live now with our 1.0 release. 

You'll find the documentation [here](https://developer.helpscout.com/beacon-2/ios/#open-and-close-events). Let us know if you have any questions!
