### ISSUE TITLE
Improve signature of delegate method

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#26]
The `prefill(_ form: HSBeaconContactForm)` delegate method doesn't have a standardize signature.
The signature should be:
`func beacon(_ beacon: HSBeacon, prefillForm form: HSBeaconContactForm)`. While it's not a big deal, this would be cleaner. 

See: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-1001803-BCIDAIJE

**Comment by jgritman** [comment]
Thanks for the feedback! We don't expose the state of the Beacon through `HSBeacon`, so adding it to the signature wouldn't do much. 

However, the `HSBeaconSettings` object passed on open has some relevant information that could be useful to the delegate calls. We're making a few changes in the next release to help there:

* `HSBeaconContactForm` will now have a read-only property with the settings object. This will keep the signature the same, so we don't need to deprecate the existing one.
* We're adding some more delegate methods for open/close events, and these will have the `HSBeaconSettings` as an argument.
