### ISSUE TITLE
Get in touch customization 

### ISSUE THREAD

**Issue by ay8s** [helpscout/beacon-ios-sdk#3]
Right now we ship the app with our own FAQ which pulls in HelpScout Docs. We then show different contact options based on the users plan. It would be great if we could remove our implementation of docs in favor of Beacons but that would require an odd feature request.

We'd love the ability to disable the default contact option within Beacon but have a way for us to define our own that gets called when a user taps "Get in touch". For us this would open a Twitter client to allow them to tweet to us rather than email.

**Comment by jgritman** [comment]
We're not sure if we want to expose this functionality right now. I'll leave this open until we have a definite answer for you. Even if we proceed with adding this, there's a lot of complexity in implementing this feature, so it might be a while before we can ship it. 

Would it help out if the SDK provided methods to make the docs calls for you? Our [Android SDK has a way to do this](https://github.com/helpscout/beacon-android-sdk-sample#exposed-methods)(built with Buffer's requirements in mind) and it wouldn't take much to expose those in the iOS SDK.

**Comment by ay8s** [comment]
I guess the simplest solution right now would be the option to disable the get in touch within Beacon instead of customization. That way we can show the docs side and have a separate get in touch flow for users where we prefer other channels.

**Comment by jgritman** [comment]
You can toggle that in the Beacon builder UI on the web on a per Beacon basis:
<img src="http://c.hlp.sc/3a3x431B2v3t/%255B6b4fdeed38f8c623a25d5de0018c75b6%255D_Screen%252520Shot%2525202018-08-15%252520at%2525201.04.33%252520PM.png"/>

It sounds like you want to change that on a per-user basis though. Our JS library has that option exposed:
```
Beacon('config', {
  messagingEnabled: false
})
```

We can make a release next week where you would set that on the `HSBeaconSettings` object before launching. Alternately, you could create two different Beacons and choose which one to display based on the user's plan. Exposing the setting is a small project, so I'll probably push that out anyway.

**Comment by jgritman** [comment]
The new version of the SDK (0.49) now has a `messagingEnabled` flag you can set on `HSBeaconSettings`. The [updated documentation](https://developer.helpscout.com/beacon-2/ios/) should be available shortly.
