### ISSUE TITLE
Ability to add additional actions within Beacon.

### ISSUE THREAD

**Issue by ay8s** [helpscout/beacon-ios-sdk#31]
We'd love the ability to add additional contact options alongside the Beacon Contact Option. For Free users we don't enable email support but give them to reach out over Twitter & Facebook. 

Right now we show an action sheet giving them the option for FAQ, Twitter and Facebook but we'd love to show them the FAQ initially so they're able to search for an answer before then reaching out.

Same with paid users, we'd love to have the Beacon contact option but give them the flexibility to reach out over Twitter and Facebook if they wish.

Maybe they just get listed within the "Get in touch" section? Would be awesome if this was also possible on the Android side. Couldn't see an obvious way of doing this right now. :)

**Comment by samsymons** [comment]
Hey @ay8s! I'm very sorry for the late reply here, it's been a super busy time at Help Scout. 😄 

I've tracked this suggestion internally; we're heads down on the iOS app at the moment, but I'll sync up with the mobile team and see what we can do. If or when this makes it into a release, I'll let you know! Thanks for the suggestion!
