### ISSUE TITLE
Crash when calling HSBeacon reset

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#35]
When calling reset on a form with attachments, Beacon will crash instead of resetting the form. This leaves us with no way to clear pre-populated fields (via the `prefill` method) when they might want to restart the feedback process.

* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
Crash

**Expected outcome**
Beacon should not crash

**Screenshots or GIFs**

<img width="371" alt="Screen Shot 2019-08-23 at 15 47 43" src="https://user-images.githubusercontent.com/171163/63619695-5cec6d80-c5bd-11e9-844a-dced0741ccd0.png">

**Comment by adrianne-helpscout** [comment]
https://helpscout.atlassian.net/browse/IOSSDK-9

**Comment by parrots** [comment]
This appears fixed in 1.0.2.

**Comment by ScottPetit** [comment]
Well @parrots I was just writing to let you know that it was indeed fixed in 1.0.2 but you seem to have beaten me to the punch.  Thanks for the detailed issue and screenshot, it made fixing it that much easier.
