### ISSUE TITLE
Offline Support for message sending

### ISSUE THREAD

**Issue by florianbuerger** [helpscout/beacon-ios-sdk#36]
Hi, 

We are evaluating the iOS beacon for our app [Flighty](https://www.flightyapp.com). Since our app is often used while in airplane mode, writing feedback & preparing bug reports while offline is something we would want to support.

Are there any plans to offer an offline mode via your SDK in the near future? Or is that something you don't want to support. 

Thanks.

**Comment by florianbuerger** [comment]
Ah, sorry for not making our use case clear, I forgot about the docs feature. 

For us, it would be great if a user could write a message draft that will be sent once the device comes back online, similar to a draft in Mail.app. No access to previous conversations needed. 

I fully understand that this would be a pretty big thing to support so I can understand if you don't want to maintain it.

**Comment by scottyab** [comment]
I think offline support for message sending would be a great feature we have it logged internally, however, we're not looking to add this in the near term. I'm closing this issue to as part of our housekeeping to keep the open issues list the concise. Thanks for the suggestion.
