### ISSUE TITLE
Incorrect "There was a problem sending your message pleased try again in a moment" message

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#38]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon install method: [x] CocoaPods

**Repro step**
- Switch to Airplane mode (or use the network conditioner with a bad connection)
- Open Beacon in our app.

**Actual outcome**

We often get reports of our users saying that they get the following message when trying to access Beacon: "There was a problem sending your message pleased try again in a moment".
I can reproduce the issue by switching to Airplane mode and opening Beacon. I was not yet trying to send a message through Beacon.

They end up having to reach out to us through a different way. 

**Expected outcome**

- The error message should not be "There was a problem sending your message. Please try again in a moment" but "No network connection available. Please check your network connection or try again in a moment" and there should be a "Retry" button below the text. 
- Beacon should minimize times where it requires network access and delay showing this message when the users starts typing a search or attempts to send their message. Eg. I should be able to open Beacon, go to the Ask tab, type a message and hit "Send". There would be the time to show the error message if there is no network connection.

This is loosely related to #36

**Comment by adrianne-helpscout** [comment]
https://helpscout.atlassian.net/browse/IOSSDK-17

**Comment by ScottPetit** [comment]
Hey @bvirlet thanks for filing an issue.  Just wanted to let you know that this has been improved in 1.0.4.  The error message is much improved and there is now a retry button.  

Although it's definitely not offline support hopefully it's a better experience for your users.
