### ISSUE TITLE
sdk freezing when Pick Image from photo library 

### ISSUE THREAD

**Issue by MoElnaggar14** [helpscout/beacon-ios-sdk#39]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
sdk freezing in iOS 13 when try to pick image form photo library

**Expected outcome**
sdk should works fine in pick image 

**Screenshots or GIFs**
Any examples of the issue

**Comment by bvirlet** [comment]
I confirm this issue on iOS 13. When an image is picked, you end up with the image on a white screen and you cannot do anything anymore.

**Comment by bvirlet** [comment]
Note also the the SDK crashes if the user chooses "Take photo" and the app has not given the camera permissions yet.

**Comment by samsymons** [comment]
@MoElnaggar14 @bvirlet Thanks for the report – we're seeing this in our own app as well, and have gotten a fix in place for it. We'll aim to get a Beacon SDK release ASAP including this fix. I'll close out this ticket once we've published the new version. Thanks again!

**Comment by adrianne-helpscout** [comment]
https://helpscout.atlassian.net/browse/IOSSDK-15

**Comment by MoElnaggar14** [comment]
@adrianne-helpscout we doesn't have access

**Comment by adrianne-helpscout** [comment]
👋 @MoElnaggar14. The rest of the mobile team and I are aware that you do not have access to our internal tracking system. Still, we decided that there was value in adding our references to our Jira tickets to these GitHub issues. It makes it easier for us internally to keep things in sync and make sure that we do not drop any inflight items. We also believed that it could provide some value to you as it makes it apparent that we are working on it, and if you so needed, you had a specific issue number that you can reference.

We will, of course, update here as we resolve the items.

**Comment by ScottPetit** [comment]
Hey @MoElnaggar14  & @bvirlet,

I just wanted to let y'all know that the issue y'all mentioned about not being able to select an image on iOS 13 is fixed with version 1.0.2 of the SDK.
