### ISSUE TITLE
View Hierarchy Error then Presenting Beacon

### ISSUE THREAD

**Issue by jimjeffers** [helpscout/beacon-ios-sdk#4]
* Beacon install method: CocoaPods

**Actual outcome**
We have a view hierarchy as follows: 
TabBar VC -> Navigation VC -> TableVC

and received a view hierarchy error when attempting to execute HSBeacon.open from the didSelectRow delegate method:

```swift
override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
  //...
  let settings = HSBeaconSettings(beaconId: "intentionally-omitted")
  HSBeacon.open(settings)
  //...
}
```

The view does not change upon row selection but a window error appears in the console:
```
Warning: Attempt to present <HSBeaconNavigationController: 0x7fd92f8e7e00> on <NavigationViewController: 0x7fd930075000> whose view is not in the window hierarchy!
```

**Expected outcome**
Beacon should have presented it's modal view. For example presenting our own support website in a safari view from the same point in our code works as expected: 

```swift
let supportURL = "https://support.ourwebsite.com/"
guard let url = URL(string: supportURL) else { return }
self.present(SFSafariViewController(url: url), animated: true)
```

**Comment by jgritman** [comment]
Hi Jim! By default, `Beacon.open` will attempt to present the Beacon modal using `UIApplication.sharedApplication.delegate.window.rootViewController`. This works well for many apps, but for cases like yours where that fails, we've included an overloaded `open` call where you can specify the presenting view controller:

```HSBeacon.open(settings, from: self)```

Let us know if you're still seeing any problems after switching to that call. Thanks for helping us out with beta testing!

**Comment by jimjeffers** [comment]
Thanks @jgritman that solved the problem!
