### ISSUE TITLE
Tapping add reply does nothing

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#40]
When trying to add a reply to an existing conversation, nothing happens.

![RPReplay_Final1573524470 2019-11-11 21_12_19](https://user-images.githubusercontent.com/171163/68635927-001b9780-04c8-11ea-9720-c0b6b8b226c6.gif)

* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

**Actual outcome**
Tapping the add reply button does nothing. Both on iPad and iPhone.
  
**Expected outcome**
Tapping add reply should bring up the form to add a reply.

**Screenshots or GIFs**
Any examples of the issue

**Comment by codenameDuchess** [comment]
Thanks so much for reporting this issue and sorry for the trouble. We were unfortunately unable to re-create this behavior with the last public release of the SDK. Would you please provide us with some additional details? Which version of the SDK are you seeing this issue in and while running which operating systems? Is the issue limited a particular version of iOS?

An updated version of the SDK (1.0.2) is due out this week. Would you please verify whether or not you are still seeing this issue in the latest release? 

Thanks in advance for any additional details you can provide to help us track this down.

**Comment by parrots** [comment]
I'm using version 1.0.2 of the beacon SDK, and this is running on iOS 13.2.2. I originally found out of this issue via a customer, running I think 13.1. It is happening to me both on an iPhone test device and an iPad test (from the above GIF).

Not sure if this is a common thread, but a user is configured via the beacon SDK.

**Comment by adrianne-helpscout** [comment]
👋 Hiya @parrots. We haven't released v1.0.2 yet, so, if you are on our latest, that would be v1.0.1. We'll post once the update is available and would ask that you reverify then.

**Comment by parrots** [comment]
Oops sorry yeah. I meant to type 1.0.1, that is what is in my pod lock file.

**Comment by parrots** [comment]
This is not fixed by 1.0.2, just tried and both of my devices still do nothing when hitting reply on an existing chat. No debug messaging on the console.

**Comment by codenameDuchess** [comment]
Thank you for confirming this is still an issue in the version 1.0.2 and for the additional details so that we can recreate the problem and address it. We'll report back when we have a fix in.

**Comment by samsymons** [comment]
Internal Jira reference: https://helpscout.atlassian.net/browse/IOSSDK-31

**Comment by codenameDuchess** [comment]
Hi @parrots we have unfortunately had a tough time trying to reproduce this error with the latest version of the SDK. You mentioned that you've installed the SDK with cocoa pods. Is it possible while viewing your  pod project's BeaconPreviousMessages.storyboard the action was accidentally disconnected? It's a st

**Comment by parrots** [comment]
@codenameDuchess to your message asking about the storyboard (which seems to have disappeared from this thread), I can't open the BeaconPreviousMessages.storyboard because it is compiled. Xcode won't open storyboards one they've been compiled.

**Comment by codenameDuchess** [comment]
Sorry for the errant message @parrots (hoped I'd deleted it before the notification went out). 

Though I was not able to recreate the issue I did find some good info in Apple's forums from others who encountered similar behavior in iOS 13 and employed the fix they suggested. Will circle back with you once we release the update so you can verify it resolved this issue. 👍

**Comment by subhash825** [comment]
Hi codenameDuchess,
When tap on Attachment Icon next to "SEND A MESSAGE" button in reply message close the attachment screen without showing the ActionSheet.

**Comment by codenameDuchess** [comment]
Thanks for these reproduction steps @subhash825 👍 Will add them to our ticket to be sure we run this scenario on the fix.

**Comment by parrots** [comment]
I have the latest version of the SDK installed and I can confirm that this did not fix the issue for me :(

![RPReplay_Final1583872896 2020-03-10 13_43_28](https://user-images.githubusercontent.com/171163/76357544-249c4a80-62d5-11ea-9d8e-64973c7d78d0.gif)

**Comment by samsymons** [comment]
Hey @parrots – sorry you're still running into this issue. 😞 We originally struggled to reproduce it ourselves, so our original fix was speculative. The good news is that I've been able to reproduce this locally tonight, and I'm working on a fix for it right now. We'll get a new release out ASAP with this bug squashed.

Thanks so much for the patience here!

**Comment by parrots** [comment]
Happy you all tracked it down. I'm totally familiar with the feeling of a speculative fix not actually working, so I'm glad you got a victory shortly after!

**Comment by samsymons** [comment]
@parrots This fix is now available in Beacon 1.0.5! 💃 Give that a go and definitely let us know if anything pops up. Thanks again for the patience! 😄
