### ISSUE TITLE
Adding a photo gets stuck

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#41]
When adding an attachment and picking the "choose from library" option, when tapping on a photo it appears full-screen but then there is no way to confirm the selection or cancel out.

iPhone X

* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
Picture is displayed, but user is unable to do anything with it. App basically is locked at that point and unresponsive.

**Expected outcome**
Should be able to pick or dismiss the photo.

**Screenshots or GIFs**
![RPReplay_Final1573572216 2019-11-12 10_25_58](https://user-images.githubusercontent.com/171163/68684643-d483c600-0536-11ea-82b2-ee39bdda4202.gif)

**Comment by codenameDuchess** [comment]
Thanks so much for reporting this issue and sorry for the trouble. The next release of the SDK (Version 1.0.2) will contain a fix for this. Please be on the lookout for the update and we will circle back to close out this issue once the fix release is live. Thanks again.

**Comment by parrots** [comment]
Confirmed fixed with 1.0.2.
