### ISSUE TITLE
Prefill called multiple times

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#42]
`Prefill` can be called multiple times in iOS 13. With the new modal appearance, swipe down to dismiss is an option. However a user can cancel this gesture, causing the view to snap back into place. In this case, prefill is called again, which can wipe out any of the existing information the user provided and possibly duplicate some default file attachments.

Even if you add your own custom checks in the `prefill` method to prevent multiple calls, the subject and body of the existing method are still reset to blanks.

Fix needs to be two-fold: `prefill` should only be called once, and body/subject should not be reset as part of the canceled gesture.

v1.0.2

* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

**Actual outcome**
`Prefill` is called a second time when a user starts to swipe to dismiss, but cancels the gesture by starting to swipe up after swiping down initially.

**Expected outcome**
Prefill should not be called as the form has already been filled once.

**Screenshots or GIFs**
![Screen Recording 2019-11-14 at 11 56 50 PM 2019-11-14 23_58_07](https://user-images.githubusercontent.com/171163/68918024-9e169880-073a-11ea-8bbb-40bb71d1d697.gif)

**Comment by codenameDuchess** [comment]
Thanks for this detailed bug report and sorry for the trouble. We're looking into it and will report back.

**Comment by samsymons** [comment]
Internal Jira reference: https://helpscout.atlassian.net/browse/IOSSDK-30

**Comment by samsymons** [comment]
This issue should now be fixed in Beacon 1.0.3. Thanks so much for the patience!
