### ISSUE TITLE
Modal dismiss prevention

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#43]
With the new modal presentation in iOS 13, view controllers can set a state such that the drag down to dismiss presentation can be prevented, or at least have a prompt to confirm (the recommended approach). This will prevent an accidental drag too far on a scrollview triggering a dismiss and loss of information.

* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

**Actual outcome**
Dragging down on the feedback modal immediately dismisses.

**Expected outcome**
The modal should ask and confirm if the user meant to dismiss.

**Screenshots or GIFs**
Current Beacon behavior:
![Screen Recording 2019-11-15 at 12 01 00 AM 2019-11-15 00_01_44](https://user-images.githubusercontent.com/171163/68918216-49bfe880-073b-11ea-9ac2-a5c16af21a9f.gif)

Recommended behavior by Apple in iOS 13:
![Screen Recording 2019-11-15 at 12 02 01 AM 2019-11-15 00_03_09](https://user-images.githubusercontent.com/171163/68918229-547a7d80-073b-11ea-986b-26297ebdb235.gif)

**Comment by parrots** [comment]
To make things easier: there is a new property on view controllers that can be set to allow a modal to prevent the automatic drag to dismiss behavior. Google around `isModalInPresentation = true` which is new for iOS 13, and `func presentationControllerShouldDismiss(_ presentationController: UIPresentationController) -> Bool` to bring up the action sheet confirmation.

**Comment by samsymons** [comment]
@parrots Thanks so much for the report! We'll get this into the next Beacon release.

Internal Jira reference: https://helpscout.atlassian.net/browse/IOSAPP-373

**Comment by samsymons** [comment]
This is now fixed in Beacon 1.0.3! Closing this ticket.
