### ISSUE TITLE
Error building Beacon with Carthage (1.0.2)

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#44]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon install method: [x] Carthage, [ ] CocoaPods, [ ] Manual

**Actual outcome**
```
$ xcodebuild -version
Xcode 11.0
Build version 11A420a
```

When running carthage build:
```
carthage build --no-use-binaries --cache-builds --platform ios "beacon-ios-sdk"
```

I get the following error:

```
/usr/bin/xcrun xcodebuild -workspace /Users/bruno/Documents/_TheGrizzlyLabs/src/core-ios/Vendor/Carthage/Checkouts/HSAttachmentPicker/Example/HSAttachmentPicker.xcworkspace -scheme HSAttachmentPicker -configuration Release -derivedDataPath /Users/bruno/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/HSAttachmentPicker/1.0.8 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/ds/94mr7zn90mq0zb39s7cf6d5c0000gn/T/HSAttachmentPicker SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/bruno/Documents/_TheGrizzlyLabs/src/core-ios/Vendor/Carthage/Checkouts/HSAttachmentPicker)User defaults from command line:
    IDEArchivePathOverride = /var/folders/ds/94mr7zn90mq0zb39s7cf6d5c0000gn/T/HSAttachmentPicker
    IDEDerivedDataPathOverride = /Users/bruno/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/HSAttachmentPicker/1.0.8

Build settings from command line:
    CARTHAGE = YES
    CLANG_ENABLE_CODE_COVERAGE = NO
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    GCC_INSTRUMENT_PROGRAM_FLOW_ARCS = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos13.0
    SKIP_INSTALL = YES
    STRIP_INSTALLED_PRODUCT = NO

2019-11-15 09:45:14.258 xcodebuild[95298:27104839]  DTDeviceKit: deviceType from 2cf2c38a9ead253b80ee6c5dca3376002f748059 was NULL
2019-11-15 09:45:14.369 xcodebuild[95298:27104845]  DTDeviceKit: deviceType from 2cf2c38a9ead253b80ee6c5dca3376002f748059 was NULL
Build Preparation
Build task concurrency set to 4 via user default IDEBuildOperationMaxNumberOfConcurrentCompileTasks

note: Using new build system
note: Planning build
note: Constructing build description
Build system information
error: Unexpected duplicate tasks:
1) Target 'HSAttachmentPicker' (project 'Pods') has copy command from '/Users/bruno/Documents/_TheGrizzlyLabs/src/core-ios/Vendor/Carthage/Checkouts/HSAttachmentPicker/HSAttachmentPicker/Info.plist' to '/Users/bruno/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/HSAttachmentPicker/1.0.8/Build/Intermediates.noindex/ArchiveIntermediates/HSAttachmentPicker/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/HSAttachmentPicker.framework/Info.plist'
2) Target 'HSAttachmentPicker' (project 'Pods') has copy command from '/Users/bruno/Documents/_TheGrizzlyLabs/src/core-ios/Vendor/Carthage/Checkouts/HSAttachmentPicker/HSAttachmentPicker/Info.plist' to '/Users/bruno/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/HSAttachmentPicker/1.0.8/Build/Intermediates.noindex/ArchiveIntermediates/HSAttachmentPicker/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/HSAttachmentPicker.framework/Info.plist'

warning: duplicate output file '/Users/bruno/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/HSAttachmentPicker/1.0.8/Build/Intermediates.noindex/ArchiveIntermediates/HSAttachmentPicker/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/HSAttachmentPicker.framework/Info.plist' on task: ProcessInfoPlistFile /Users/bruno/Library/Caches/org.carthage.CarthageKit/DerivedData/11.0_11A420a/HSAttachmentPicker/1.0.8/Build/Intermediates.noindex/ArchiveIntermediates/HSAttachmentPicker/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/HSAttachmentPicker.framework/Info.plist /Users/bruno/Documents/_TheGrizzlyLabs/src/core-ios/Vendor/Carthage/Checkouts/HSAttachmentPicker/Example/Pods/Target Support Files/HSAttachmentPicker/Info.plist (in target 'HSAttachmentPicker' from project 'Pods')
** ARCHIVE FAILED **
```

**Comment by codenameDuchess** [comment]
Thank you for reporting this issue and sorry for the trouble. We're looking into it and will report back.

**Comment by adrianne-helpscout** [comment]
https://helpscout.atlassian.net/browse/IOSSDK-32

**Comment by ScottPetit** [comment]
Hey @bvirlet I just wanted to reach out to provide a workaround and get some more context on how you're using Carthage.

So the workaround would be to point to master

```
github "helpscout/beacon-ios-sdk" "master"
```
which should resolve the issue.  

Also I was just wondering why you're passing the `--no-use-binaries` for the Beacon SDK and if not passing that flag affects the build in anyway.

**Comment by samsymons** [comment]
Hey @bvirlet! Were you able to get things working with the workaround provided above?

**Comment by bvirlet** [comment]
Hi @ScottPetit. Haven't tried it yet. Are we getting any other changes in master?
For the no-use-binaries, we use the same command for all our Carthage integrations (so it's not specific to HelpScout Beacon SDK), and I think it was related to previous issues with Swift ABI stability. We might not need that anymore.

**Comment by ScottPetit** [comment]
@bvirlet there's no source code changes on `master` just some updates to the Cartfile that should resolve the issue you're seeing.

**Comment by bvirlet** [comment]
@ScottPetit I'm now getting the following error:

```
carthage build --cache-builds --platform ios --verbose beacon-ios-sdk
```

```
➜  core-ios git:(master) ✗ sh Scripts/carthage-build.sh
*** No cache found for beacon-ios-sdk, building with all downstream dependencies
*** Skipped building beacon-ios-sdk due to the error:
Dependency "beacon-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/helpscout/beacon-ios-sdk/issues/new
```

**Comment by codenameDuchess** [comment]
@bvirlet Thanks for trying the possible workaround and for providing the additional info. 

We've confirmed we're able to duplicate this error. And we've double-checked that our schemes are indeed shared so we'll need more time to dig into this issue. 

Will add the details you provided to our ticket and circle back once we have a solution.

**Comment by ScottPetit** [comment]
Hey @bvirlet, sorry it took so long for me to circle back with you but just wanted to update you after digging into Carthage a bit more.  The quick update is Beacon doesn't support being built by Carthage with the `--no-use-binaries`.  The main reason for that is the only way that distributed is via a binary ( we don't provide an Xcode project of the Beacon SDK for you to build) and as such just isn't compatible with that Carthage flag. 

Like you mentioned hopefully the need for this flag becomes less-so with the Swift ABI compatibility updates, but until then Beacon should continue to be able to be built without that flag.

**Comment by bvirlet** [comment]
Hi @ScottPetit, please see [my comment](https://github.com/helpscout/beacon-ios-sdk/issues/44#issuecomment-563982056) from December 10: I was building with `--no-use-binaries`.

**Comment by ScottPetit** [comment]
Yea sorry I didn't address the December 10th comment where you weren't using the `--no-use-binaries` flag.

That error could be caused by my previous suggestion about specifying a branch to Carthage, which seems to actually be causing problems.  Instead of specifying a branch, Carthage seems to work just fine by leaving off a version number entirely:

`github "helpscout/beacon-ios-sdk"`

or specifying a version like 

`github "helpscout/beacon-ios-sdk" "~> 1.0"`

Both of those entries seem to work just fine in a Sample project.  Also just incase you do run into any issues, clearing the Carthage cache using:

`'rm -rf ~/Library/Caches/org.carthage.CarthageKit'`

has always helped me in the past.
