### ISSUE TITLE
[Still investigating] error: unable to index file  Possible git-lfs/git issue when committing pod update 

### ISSUE THREAD

**Issue by rromanchuk** [helpscout/beacon-ios-sdk#45]
Because of CI constraints, i commit my `Pods/` directory and when i try to commit the latest update i'm getting the following 

```
error: unable to index file 'Pods/Beacon/Beacon.framework/Beacon.bundle/BeaconAttachmentCell.nib'
fatal: updating files failed
```

This is probably something out of your control and a `git-lfs` configuration issue on my end. You can close this, but posting for visibility.

**Comment by codenameDuchess** [comment]
Hi @rromanchuk 

Clearing your local git cache or removing and then re-adding your Pods directory will hopefully resolve this issue for you. 

Clearing Cache:

cd Pods/
git rm -r --cached .
git add .
git commit -am 'git cache cleared'

Remove and Re-add:

cd Pods/Beacon
git rm -r Beacon.framework/
git add .
git commit * -m "Maintenance: Fixed git error unable to index file"

**Comment by rromanchuk** [comment]
@codenameDuchess thanks for saving me a bunch of googling 🍺
