### ISSUE TITLE
Suggested for you doesn't respect collection limits

### ISSUE THREAD

**Issue by ay8s** [helpscout/beacon-ios-sdk#5]
* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
When viewing Beacon with a Collection limit I am seeing articles for other collections display in "Suggested for you".

When searching for articles the limit is respected and only articles from the selected collection are shown.

**Expected outcome**
Beacon should not show articles from unselected collections within "Suggested for you".

**Comment by ay8s** [comment]
Looks like this may effect web also. I have gone ahead and manually selected iOS only articles for our beacons.

**Comment by jgritman** [comment]
Hi Andrew! Thanks for pointing this out. We had a server side bug with the suggestions but it's all fixed up now.

We're running a build through QA with fixes for your other issues now, and that should be up in the next few days.
