### ISSUE TITLE
Undefined symbol on arm64: ___isPlatformVersionAtLeast

### ISSUE THREAD

**Issue by graver** [helpscout/beacon-ios-sdk#50]
Thank you for taking the time to submit an issue with all the details shown below.  Our engineering team monitors issues submitted and strives to respond with 1-2 business days.

* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
Unable to compile Beacon v1.0.3 due to undefined symbol.

```
Undefined symbols for architecture arm64:
  "___isPlatformVersionAtLeast", referenced from:
      -[HSNavigationController viewDidLoad] in Beacon(HSNavigationController.o)
      -[HSTableViewController viewDidLoad] in Beacon(HSTableViewController.o)
      -[HSTableView initWithFrame:] in Beacon(HSTableView.o)
      -[HSTableView initWithCoder:] in Beacon(HSTableView.o)
      -[HSTableViewCell initWithStyle:reuseIdentifier:] in Beacon(HSTableViewCell.o)
      -[HSBeaconKeyboardHeightObserver handleKeyboardShown:] in Beacon(HSBeaconKeyboardHeightObserver.o)
      -[HSBeaconContactFormViewController viewDidLoad] in Beacon(HSBeaconContactFormViewController.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Expected outcome**
Compile and link Beacon properly.

More than willing to provide additional details!

**Comment by samsymons** [comment]
@graver Yikes – thanks for the report here! We made some tweaks around the way Beacon is built for the last release, so this might be related. Let me take a dive into this and get back to you here with any questions/updates. Thanks again!

Internal Jira ticket: https://helpscout.atlassian.net/browse/IOSSDK-109

**Comment by samsymons** [comment]
@graverJust following up with a quick question: by chance, are you building with Xcode 10?

**Comment by samsymons** [comment]
Unfortunately, since we're using availability checks for iOS 13, it looks like this isn't backwards compatible with Xcode 10. 😞 For now, Beacon SDK can only be used with Xcode 11+; I tested some other SDKs which use iOS 13 checks and ran into the same exact problem with Xcode 10.3, so I'm not sure there's a suitable workaround.

I'll update the documentation to reflect this, very sorry for the trouble @graver.
