### ISSUE TITLE
Tapping attachment button next to "SEND A MESSAGE" close the Add Reply Screen - iPad

### ISSUE THREAD

**Issue by subhash825** [helpscout/beacon-ios-sdk#52]
Hi codenameDuchess, @adrianne-helpscout ,

When tap on Attachment Icon next to "SEND A MESSAGE" button in reply message close the attachment screen without showing the ActionSheet.
Issue tested in iOS 13 iPad

**Comment by hs-gv** [comment]
Thanks for contacting us with this.  I'll attempt to reproduce the issue and Iet you know the results.  One question, which version of the SDK were you running when you experienced this? Thanks.

**Comment by hs-gv** [comment]
Hello @subhash825, 
Following up from yesterday.  I've tried to reproduce the issue that you reported yesterday using the latest version of our SDK, 1.0.3, but I'm unable to.  If there's any other information that you could provide to us in order to reproduce this, we would appreciate it.  Thanks.

**Comment by subhash825** [comment]
@hs-gv thanks for the reply.
I am trying with latest SDK 1.0.3 and iOS 13 iPad.

Steps I followed

open beacon
Get in Touch and add conversation
select conversation
add a reply
add attachment
close the beacon

**Comment by hs-gv** [comment]
Hello @subhash825, thanks for the extra information.  I will try those steps next, and update you with what we find.

**Comment by hs-gv** [comment]
@subhash825, I was able to reproduce with the extra information you provided.  Thank you again for sending those steps.  I have created a bug in our internal system (https://helpscout.atlassian.net/browse/IOSSDK-110) to investigate.  We will update you with any changes on this issue.

**Comment by ScottPetit** [comment]
Hey @subhash825, thanks again for filing the issue.  This is now fixed in Version 1.0.4 of the SDK.
