### ISSUE TITLE
Example app is broken

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#56]
The Example app is broken, because it doesn't have a Podfile anymore. It seems to be missing the HSAttachmentPicker framework.

README instructions incorrectly say:

> To run the example project in this repo, clone and run pod install from the Example directory. Once the installation is complete, open Beacon Example.xcworkspace and run the Beacon Example scheme.

**Comment by shaunmcilroy** [comment]
Thanks for reporting this @bvirlet, will touch base with the team and report back with details soon.

**Comment by ScottPetit** [comment]
Hey @bvirlet sorry about the trouble running the example app.  It seems our documentation was a bit out of date.  I've updated it [here](https://github.com/helpscout/beacon-ios-sdk/blob/master/README.md#sample-application) but to summarize you should be able to resolve it by running `carthage bootstrap` from the root directory.

**Comment by bvirlet** [comment]
Thank you @ScottPetit.
