### ISSUE TITLE
Add Catalyst support?

### ISSUE THREAD

**Issue by lewis-smith** [helpscout/beacon-ios-sdk#57]
* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
`'fetchAssetsWithALAssetURLs:options:' is unavailable: not available on macCatalyst`

**Expected outcome**
It would be great if Beacon could work on macOS.

**Screenshot**
<img width="1227" alt="CleanShot 2020-04-01 at 08 48 37@2x" src="https://user-images.githubusercontent.com/1905433/78112100-9e67b580-73f5-11ea-9a5d-07d0736a138c.png">

**Comment by parrots** [comment]
For anyone else running into this that needs a workaround until they fix this, here's how to exclude Beacon from your Mac builds using CocoaPods (1.9.1):

```
post_install do |installer|
  #catalyst workaround, these pods can't be linked against catalyst ATM
  #beacon / HSAttachment reference iOS-only methods
  installer.generated_projects.each do |project|
    if project.project_name == "Pods"
      project.targets.each do |target|
       if target.name == "Pods-App"
         #we need to make sure some dependencies never even compile due to mac build errors
         target.dependencies.each do |dependency|
          if dependency.name == "HSAttachmentPicker" || dependency.name == "Beacon"
           dependency.platform_filter = 'ios'
          end
         end
         puts "Updating #{target.name} to exclude pods on mac"
         target.build_configurations.each do |config|
           xcconfig_path = config.base_configuration_reference.real_path
           xcconfig = File.read(xcconfig_path)
           xcconfig.sub!('-l"HSAttachmentPicker"', '')
           xcconfig.sub!('-framework "Beacon"', '')
           xcconfig.sub!('-iframework "${PODS_ROOT}/Beacon"', '')
           xcconfig.sub!('-Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/HSAttachmentPicker/HSAttachmentPicker.modulemap"', '')
           xcconfig.sub!('-fmodule-map-file="${PODS_ROOT}/Headers/Public/HSAttachmentPicker/HSAttachmentPicker.modulemap"', '')
           xcconfig = xcconfig + "\n" + 'OTHER_LDFLAGS[sdk=iphone*] = $(inherited) -ObjC -framework "Beacon" -l"HSAttachmentPicker"'
           xcconfig = xcconfig + "\n" + 'OTHER_CFLAGS[sdk=iphone*] = $(inherited) -iframework "${PODS_ROOT}/Beacon"  -fmodule-map-file="${PODS_ROOT}/Headers/Public/HSAttachmentPicker/HSAttachmentPicker.modulemap"'
           xcconfig = xcconfig + "\n" + 'OTHER_SWIFT_FLAGS[sdk=iphone*] = $(inherited) -Xcc -fmodule-map-file="${PODS_ROOT}/Headers/Public/HSAttachmentPicker/HSAttachmentPicker.modulemap" -Xcc
           
           File.open(xcconfig_path, "w") { |file| file << xcconfig }
         end
       end
      end
    end
  end
end
```

Replace Pods-App with your Pods-YourTargetName.

**Comment by lewis-smith** [comment]
Thanks @parrots, this is great :)

**Comment by shaunmcilroy** [comment]
Hey @parrots thanks for updating with your workaround. I'll pass that over to the team for documenting should anyone else ask in the future.

In regards to long term support, @lewis-smith, adding support for MacOS via Catalyst is not something on our radar at the moment. I can't promise we'll add support in the future as we are focused on bringing new features to the SDK at the moment (such as Beacon chat for customers). We've had no other requests for this in our internal tracking tool but I've added a card for our team to track any requests moving forward. If we have any updates to share about adding support, we'll be sure to loop you in via this issue.

**Comment by parrots** [comment]
Add me as a +1 to that tracker. I expect you'll have more requests this fall when Apple adds iPhone app support to Catalyst. Right now it is iPad only, and that limits the potential apps using it.

**Comment by shaunmcilroy** [comment]
Sure thing @parrots - I've added your vote to the list. Thanks again for being proactive in supporting our development community!

**Comment by lewis-smith** [comment]
I couldn't get the solution that parrots mentions to work. I'm sure this is my fault.

That said, the API call that HSAttachmentPicker is making that isn't allowed in Catalyst has been deprecated since iOS 11, so there should be motivation to fix this regardless of Catalyst.

**Comment by samsymons** [comment]
@lewis-smith Hey Lewis! Good call on the deprecated APIs – we're moving to iOS 11 as a minimum deployment target across the board, so we'll be doing that with `HSAttachmentPicker` shortly and tidying up the deprecated API usage.

@parrots Great point about the widening of Catalyst support when iPhone support arrives. We're on the home stretch for the 2.0 release of Beacon which has definitely taken up a lot of resources – there's a bit of a Swift overhaul internally – and after that I'm hoping to dig deeper into Catalyst support for the 2.1 release.

Thank you both for the patience! ❤️

**Comment by adrianne-helpscout** [comment]
Internal tracking ticket: https://helpscout.atlassian.net/browse/IOSSDK-195

**Comment by scottyab** [comment]
We're not looking to add this in the near term. I'm closing this issue to as part of our housekeeping to keep the open issues list the concise. Thanks for the suggestion.

**Comment by rafaelks** [comment]
Would be super important for us to have the Catalyst support to have a seamless experience between our iOS and macOS apps as well. Please add me as +1 to that tracker as well.

> I'm hoping to dig deeper into Catalyst support for the 2.1 release.

It's in version 2.2 already, and we are waiting for a really long time now -- any updates here?

**Comment by sipersso** [comment]
I'd love to see catalyst support as well. Right now it breaks builds for OSX/Apple Silicon which is unfortunate. Any pointers on how to avoid compilation errors when using SwiftPM?

**Comment by codenameDuchess** [comment]
I've updated our internal tracking ticket to document your +1s to this request. We'll circle back with updates if we bring in this Beacon enhancement in the future. Thanks again.

**Comment by sipersso** [comment]
@codenameDuchess Maybe I should add a separate ticket for the fact that it currently isn't possible to even compile apps with HelpScout if you are including it via SPM? And that there are no instructions on how to exclude it when using Cocoapods (except for the instructions by @parrots  here).

If anyone else is using SPM and HelpScout, one workaround is to include the HelpScout framework manually. Then you can exclude it from being included in your OSX builds and only include it for iOS. Maybe there is a way to do this with SPM, but I couldn't get it working.  

You will also have to wrap all your code that is touching the beacon
#if canImport(Beacon)
#endif

If not, your project won't compile.

I think one thing is adding support for Catalyst, it is another thing to not prevent apps using HelpScout for iOS to compile their projects for OSX. I can live with HelpScout not being available, but I must be able to compile the project if I am adding support for OSX.

**Comment by codenameDuchess** [comment]
@sipersso I agree that warrants a separate ticket and we appreciate you opening a separate issue with reproduction steps so we can (hopefully) get in a fix that doesn't require the workaround you mentioned. It will also make the workaround easier for folks in need of it to find via search in the meantime until we can get the work prioritized and address it.
