### ISSUE TITLE
iOS App crash

### ISSUE THREAD

**Issue by staffy123** [helpscout/beacon-ios-sdk#6]
I've got a crash when I open the Previous Messages page. 
issue:- Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSConcreteAttributedString initWithString:: nil value'

**Comment by jgritman** [comment]
Sorry to hear you ran into this! It looks like this might be due to an empty subject line. Does that sound like a possible cause?

We've got a fix we're testing out right now.

**Comment by jgritman** [comment]
We've fixed the empty subject issues in release 0.52. Let us know if you're still having any issues!

**Comment by staffy123** [comment]
Thank you,  Now it's working fine.
