### ISSUE TITLE
iOS Beacon form prefilled custom fields don't work at all

### ISSUE THREAD

**Issue by kjpolaszek** [helpscout/beacon-ios-sdk#62]
Hello,

We are using Beacon Library 2.0.0-beta.1, but this issue are in 1.0.5 as well. We are currently having a problem with prefilled custom fields.
Beacon install method: CocoaPods,
FInd the code below.

```
static func showHelpScout(from vc: UIViewController) {
    let settings = HSBeaconSettings(beaconId: getBeaconId())
    settings.delegate = playbookAutoFill
    ... (fill user information)
    HSBeacon.open(settings, from: vc)
}
class PlaybookAutoFillDelegate: NSObject, HSBeaconDelegate {

    func prefill(_ form: HSBeaconContactForm) {
        form.addCustomFieldValue("112529", forId: 22657)
        form.beaconSettings.messagingSettings.contactFormCustomFieldsEnabled = true
        form.beaconSettings.messagingSettings.showPrefilledCustomFields = true
    }

}
```

**Actual outcome**
Beacon did not prefill custom fields and don't show custom field on contact form. Function ` func prefill(_ form: HSBeaconContactForm)` is called properly before contact form will appear.

**Expected outcome**
Beacon should prefill that customField and show it.

**Screenshots or GIFs**
![Simulator Screen Shot - iPhone X - 2020-05-27 at 14 46 03](https://user-images.githubusercontent.com/2893345/83020662-1551b100-a029-11ea-852b-32aaf30a1953.png)

**Comment by shaunmcilroy** [comment]
Hi @kjpolaszek - first of all so sorry for missing this earlier. We aim to get a response for new issues within 1-2 business days and we've fallen short here. We'll do better.

For this bug you'll be happy to know that we've got a fix due for a release in our next SDK update. I don't have an ETA on when that will be yet but we'll follow up here when it's published.

Internal tracking card: https://helpscout.atlassian.net/browse/IOSSDK-152

**Comment by adrianne-helpscout** [comment]
👋 @kjpolaszek, 
The fix for this bug went out in 2.0.0-beta.2; so, if you updated to the latest version you should be good to go. Please let us know if you run into any other issues.

**Comment by kjpolaszek** [comment]
I have version 2.0.0-beta.2 already over a month and that issue is still exist.

**Comment by jotaemepereira** [comment]
> I have version 2.0.0-beta.2 already over a month and that issue is still exist.

Hey @kjpolaszek sorry for the back and forth. We confirmed we have an issue when showing custom fields. We will let you know when this is fixed.

**Comment by jotaemepereira** [comment]
👋  @kjpolaszek! I did some testing and I got the prefill working on my side. Something important is that the `contactFormCustomFieldsEnabled` can only be enabled via the iOS API if it is already enabled in the Beacon settings.

On your Beacon settings on the web, you should have an option to show/hide custom fields, this flag needs to be on to be able to see custom fields on the contact form on iOS.

<img width="699" alt="custom" src="https://user-images.githubusercontent.com/7924732/87490474-2330b500-c61c-11ea-92e6-4467bdcd57c7.png">

Let me know if you have this on and we can take it from there. Thanks!

**Comment by kjpolaszek** [comment]
@jotaemepereira Thank you for that. It can be helpful but, my minor goal is to prefill custom field, so user don't need do that. I have custom field with dropdown type. I trying this:
```
func prefill(_ form: HSBeaconContactForm) {
    form.addCustomFieldValue("112529", forId: 22657)
}
```
Issue is that, this function didn't work.
Thanks!

**Comment by jotaemepereira** [comment]
Hey @kjpolaszek, the `Show Custom Fields` flag **is necessary** to be able to show and pre-fill custom fields on the SDK. If that flag is off on the Beacon settings, you are not going to be able to see the pre-filled custom fields on iOS even with the flags `contactFormCustomFieldsEnabled ` and `showPrefilledCustomFields` flags turned on.

Here is a step-by-step guide to prefill custom fields:

1. Go to your Beacon settings and turn on the flag `Show Custom Fields`. **This is important, without this step you are not going to be able to prefill custom fields**
2. On your iOS SDK set the `showPrefilledCustomFields` to `true` if want to display the custom fields to the user, by default is `false`.
3. On your iOS SDK prefill custom fields using the `prefill(_ form: HSBeaconContactForm)` delegate method.

Let me know if you have any issues after following the steps. I'm going to close this issue for now.
