### ISSUE TITLE
[minor] When space input in subject, error message

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#64]
_We are running some crowd testing on Genius Scan and some users report bugs related to HelpScout, we are forwarding them here even if it's minor for us._

* Beacon install method: [x] Carthage, [ ] CocoaPods, [ ] Manual
* Beacon 1.0.5

# Expected result

I expected that the user should be able to send a message in this case. If no, there should be a clear message to point out the user that he has to input the text into Subject filed in order to send a message successfully

# Actual result

The user is not able to send a message with enough information using only space for subject field since the unclear error message There was a problem sending your message. Please try again in a moment is always shown

[e6bf0c1f-0210-43c2-84f4-7e510a4e0908.MP4.zip](https://github.com/helpscout/beacon-ios-sdk/files/4729595/e6bf0c1f-0210-43c2-84f4-7e510a4e0908.MP4.zip)

**Comment by shaunmcilroy** [comment]
Thanks for the note, @bvirlet - we'll get that messaging updated so that it's as clear as the messaging in the web-app: https://c.hlp.sc/mXuARNdx

**Comment by ScottPetit** [comment]
Hey @bvirlet just wanted to reach out and let you know this behavior has been improved with the latest release (`v.2.0.0`).  Thanks for bringing it to our attention.
