### ISSUE TITLE
[minor] Cannot add more than 3 attachments

### ISSUE THREAD

**Issue by bvirlet** [helpscout/beacon-ios-sdk#65]
_We are running some crowd testing on Genius Scan and some users report bugs related to HelpScout, we are forwarding them here even if it's minor for us._

* Beacon install method: [x] Carthage, [ ] CocoaPods, [ ] Manual
* Beacon 1.0.5

# Expected result

The App should allow a third picture to be added or App responds with error message indicating number of allowed Attachments has been reached.

# Actual result

Three attachments are displayed - Log Txt and two pictures added are displayed. Tapping on Attachment Icon doesn’t respond. No error message or notifications displayed

[1325152f-d8f3-44f8-b322-4e3f35038dd9.MP4.zip](https://github.com/helpscout/beacon-ios-sdk/files/4729622/1325152f-d8f3-44f8-b322-4e3f35038dd9.MP4.zip)

**Comment by shaunmcilroy** [comment]
Hi @bvirlet the behaviour you're seeing here is the same as Beacon for web in that we only allow a maximum of three attachments per Beacon message. 

We don't have plans to allow more than this as we inherit the max number from the web version. I'll add an internal card to request that we make that clearer when the limit has been reached and we'll let you know if that's changed down the line. As this isn't a bug I'll close this one out for now.
