### ISSUE TITLE
User attributes are not saving

### ISSUE THREAD

**Issue by mehroozkhan** [helpscout/beacon-ios-sdk#66]
Hello,
 
I can't see user attributes on the Beacon dashboard. My code: 

        let user = HSBeaconUser()
        user.addAttribute(withKey: "appname", value: name)
        user.addAttribute(withKey: "appversion", value: appVersion)
        user.addAttribute(withKey: "osversion", value: osVersion)
        user.addAttribute(withKey: "device", value: device)
        
        HSBeacon.login(user)
        
        let settings = HSBeaconSettings(beaconId: "xxxx")
        HSBeacon.open(settings, from: self)

SDK version: 1.0.5

can you please help me if I am doing something wrong.

**Comment by shaunmcilroy** [comment]
Hey @mehroozkhan - when your user attributes are passed to Beacon you'll see them inside your Help Scout account for conversations that customer has submitted. The app on the sidebar [seen here](https://c.hlp.sc/xQuDpdJ8) should return that data for you. I'm not seeing an active company listed under your name, can you share with us the company you're developing/testing for and we can check your account to see if that data is being passed over?

**Comment by mehroozkhan** [comment]
Hi @shaunmcilroy!
 it's under arfan@blackacemedia.com

**Comment by shaunmcilroy** [comment]
Hey @mehroozkhan I'm seeing the Beacon sidebar displaying data where that information has been passed through. If you look at Convo #6 in your account with the subject Testing you'll see that data in the sidebar: https://c.hlp.sc/wbuWy0Lj

Is there something different that you were expecting to see here?

**Comment by mehroozkhan** [comment]
Hi @shaunmcilroy  
Thank you I can see the expected data.

**Comment by shaunmcilroy** [comment]
No problem, glad to hear it's working good. Open a new issue if you run into any blockers @mehroozkhan :-)
