### ISSUE TITLE
HSBeacon.reset() does not remove attachments

### ISSUE THREAD

**Issue by shubrich** [helpscout/beacon-ios-sdk#68]
* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual

**Actual outcome**
Beacon did not remove the attachment when calling `HSBeacon.reset()`. 

**Expected outcome**
Beacon should remove all attachments when calling `HSBeacon.reset()`. 

We are prefilling the attachment using the `HSBeaconDelegate's` `prefill` method. I verified that the delegate is only called once, so it seems to be a leftover from the last time the beacon was presented.

**Screenshots or GIFs**

<img src="https://user-images.githubusercontent.com/1526320/84412478-986d2c80-ac0f-11ea-90a0-5505aa72f6f2.png" width="256"  title="Github Logo">

**Comment by ScottPetit** [comment]
Hey 👋  @shubrich thanks for the report.  Just to confirm y'all are using the latest chat beta right?  

This seems to be an issue we've struggled with, where if the contact form is the visible screen, when it's dismissed, that then the form doesn't get properly reset.  

We're [tracking it internally](https://helpscout.atlassian.net/browse/IOSSDK-194) and will let you know when it's resolved.

**Comment by shubrich** [comment]
@ScottPetit I should have mentioned that, sorry :) Yes, we are using the latest chat beta.
Thanks for following up!

**Comment by ScottPetit** [comment]
Hey @shubrich I just wanted to reach out to let you know that as of version 2.0.0 this should be resolved.  Thanks for the easy to follow repro steps.
