### ISSUE TITLE
The session attributes is not supported on iOS

### ISSUE THREAD

**Issue by BinhTNT** [helpscout/beacon-ios-sdk#70]
Hello HelpScout support,

According to SDK document, It seems the session attributes supports only for Android. What is the reason that it's not available on iOS? How can I have the same thing like session attributes on Android for iOS?

Thanks,
Binh

**Comment by shaunmcilroy** [comment]
Hi @BinhTNT - you're right, this isn't available in the iOS SDK yet but it's something we've got planned for a future release. We'll keep you in the loop when that rolls out.

Internal tracking card: https://helpscout.atlassian.net/browse/IOSSDK-178

**Comment by xiaohule** [comment]
Hi @shaunmcilroy ,

I am the colleague of @BinhTNT  and this was just to tell you that is issue is not a priority for us anymore as we have found a satisfying workaround.

Thx

**Comment by shaunmcilroy** [comment]
Hey @xiaohule thanks for the note. We'll keep this issue open for any other folks who may need this support, but would love to hear what your eventual solution was. Perhaps it could help other users!

Look forward to hearing from you.

**Comment by xiaohule** [comment]
OK @shaunmcilroy actually we just decided to use user attributes :-)

**Comment by ScottPetit** [comment]
Hey @BinhTNT & @xiaohule I just wanted to reach out to let y'all know that as of version 2.0.0 we now support session attributes on the iOS SDK.

Thanks for the note.
