### ISSUE TITLE
Cannot set HSBeaconSettings.messagingSettings

### ISSUE THREAD

**Issue by jasongaare** [helpscout/beacon-ios-sdk#71]
* Beacon install method: [x] Carthage, [ ] CocoaPods, [ ] Manual

Hi, I'm attempting to vet out Helpscout as a solution for my company, and I'm running the example app from this repo. 

I've scoured the docs, and I feel like I'm attempting to do this correctly, but there's probably something I'm missing -- I'm trying to simply allow for attachments to be added to messages by setting that boolean to true. **But Xcode is telling me that `messagingSettings` is a readonly property** whenever I try to compile 

Any hints as to how to resolve this? Or am I just being near-sighted somehow?

**Screenshots or GIFs**
![Screen Shot 2020-06-18 at 4 08 51 PM](https://user-images.githubusercontent.com/15896334/85072275-6fecb180-b17e-11ea-88d4-48c872406c8f.png)

**Comment by ScottPetit** [comment]
Hey 👋  @jasongaare.  Xcode is indeed correct about `messagingSettings` being readonly.  The way to work around the error is set the properties that you want on the `messagingSettings` object that already exists on `HSBeaconSettings`.  To implement what you're attempting in your screenshot would then look like:

```objc
settings.messagingSettings.contactFormAllowAttachments = YES;
```

Let us know if you run into any other issues with the SDK.
