### ISSUE TITLE
Contact only beacon shows email option even though chat is disabled.

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#74]
Beacon version: 2.0.0-beta2

Steps to reproduce:
1: Open a beacon with docs disabled and chat disabled.

Expected:
I should be taken straight to the contact form.

Actual:
The user gets a screen with an option that says "Email" and no question.

![image](https://user-images.githubusercontent.com/6479433/85320608-a0588680-b4c3-11ea-87f2-473e0ea60eb4.png)
The SDK:s are inconsistent here. The web beacon takes you straight to the contact form. However, both the Android SDK and the iOS SDK presents you with the contact method screen even if there is only one method available, which doesn't make sense for the user.

**Comment by sipersso** [comment]
I originally mistakenly posted this in the wrong repository here: https://github.com/helpscout/beacon-android-sdk-sample/issues/105

I am closing that one. But it does seem to be an issue with both mobile SDK:s, but not the web.

**Comment by codenameDuchess** [comment]
Hi @sipersso, thanks for reporting this issue and sorry for the trouble. Good news is the team is already addressing this issue and we'll have this fixed in an upcoming release. We'll reach back out once these fixes are out.

**Comment by codenameDuchess** [comment]
Internal tracking tickets for [iOS](https://helpscout.atlassian.net/browse/IOSSDK-176) and [Android](https://helpscout.atlassian.net/browse/ANDSDK-426).

**Comment by ScottPetit** [comment]
Hey 👋 @sipersso I just wanted to reach out to let y'all know that as of version 2.0.0 of the iOS SDK, you shouldn't be presented with this screen in an email only Beacon.
  
Thanks for bringing it to our attention.

**Comment by sipersso** [comment]
Awesome! That's great news :)
