### ISSUE TITLE
Carthage install fails for 2.0 Beta 2

### ISSUE THREAD

**Issue by jasongaare** [helpscout/beacon-ios-sdk#75]
* Beacon install method: [x] Carthage, [ ] CocoaPods, [ ] Manual

**Expected outcome**
Beacon should install 

**Actual outcome**
I'm attempting to install the latest 2.0 beta via Carthage, but I am receiving this error:

```
*** Downloading beacon-ios-sdk.framework binary at "2.0 Beta 2"
***  Skipped installing beacon-ios-sdk.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)."
```

Here's my version of Carthage:
```
> carthage version
0.35.0
```

Here's my Cartfile
```
github "helpscout/beacon-ios-sdk" "2.0.0-beta.2"
```

It could possibly be due to the version of Carthage I'm using? I'm on the latest version, [see the release notes here](https://github.com/Carthage/Carthage/releases/tag/0.35.0)

**Comment by ScottPetit** [comment]
Hey @jasongaare this seems less to do with Carthage and more to do with changing Xcode versions.  It seems like you're now running Xcode 11.5 while the beta was built with Xcode 11.4.1.  We'll have another beta out shortly that will be built with the latest Xcode.  In the meantime you could also try rolling back to the latest 1.x version 1.0.5.

**Comment by jasongaare** [comment]
@ScottPetit thanks for the info -- unfortunately I need the chat feature from the beta so rolling back is not an option! I've commented on #77 as well, but a static framework solution would help me too, as I would rather install with Cocoapods but hit a roadblock due to the current distribution as a dynamic framework

**Comment by codenameDuchess** [comment]
Hi @jasongaare, when you get a moment would you please try updating with the no-use-binaries flag and let us know if that workaround gets you past this issue?

`carthage update --no-use-binaries --platform iOS`

Thanks in advance. As my colleague mentioned we expect to have a new beta out soon and will circle back to let you know once it is available.

**Comment by jasongaare** [comment]
Hello! Thanks for the tip. 

Here's my Cartfile (I've added the other deps as well)

```
github "helpscout/beacon-ios-sdk" "2.0.0-beta.2"
github "ashleymills/Reachability.swift" "v4.3.0"
github "daltoniam/Starscream" "3.0.6"
github "helpscout/HSAttachmentPicker" "1.0.11"
github "krzyzanowskim/CryptoSwift" "0.15.0"
github "pusher/pusher-websocket-swift" "7.2.0"
```

Here's what I get when I attempt that command:

```
> carthage update --no-use-binaries --platform iOS

*** Cloning beacon-ios-sdk
*** Fetching Reachability.swift
*** Fetching CryptoSwift
*** Fetching Starscream
*** Fetching HSAttachmentPicker
*** Fetching pusher-websocket-swift
*** Checking out HSAttachmentPicker at "1.0.11"
*** Checking out Reachability.swift at "v4.3.0"
*** Checking out pusher-websocket-swift at "7.2.0"
*** Checking out beacon-ios-sdk at "2.0.0-beta.2"
*** Checking out Starscream at "3.0.6"
*** Checking out CryptoSwift at "0.15.0"
*** xcodebuild output can be found in /var/folders/xr/l9qrll5x1lv6jmd6z36_bvsr0000gn/T/carthage-xcodebuild.IhKMzW.log
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
*** Building scheme "HSAttachmentPicker" in HSAttachmentPicker.xcworkspace
*** Building scheme "Reachability" in Reachability.xcodeproj
*** Building scheme "Starscream" in Starscream.xcodeproj
*** Building scheme "PusherSwift" in PusherSwift.xcworkspace
*** Skipped building beacon-ios-sdk due to the error:
Dependency "beacon-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/helpscout/beacon-ios-sdk/issues/new
```

**Comment by codenameDuchess** [comment]
My apologies @jasongaare, would you please give it a try without the platform flag and let us know if that gets you around this issue?

`carthage update --no-use-binaries`

**Comment by codenameDuchess** [comment]
Internal ticket for [supporting the platform flag iOS](https://helpscout.atlassian.net/browse/IOSSDK-229).

**Comment by jasongaare** [comment]
I ran without the platform flag, but had the same outcome (with slightly different error message):

<details>
  <summary>Carthage Update Results</summary>
  
  ```
> carthage update --no-use-binaries

*** Fetching HSAttachmentPicker
*** Fetching pusher-websocket-swift
*** Fetching Reachability.swift
*** Fetching CryptoSwift
*** Fetching Starscream
*** Checking out Reachability.swift at "v4.3.0"
*** Checking out Starscream at "3.0.6"
*** Checking out beacon-ios-sdk at "2.0.0-beta.2"
*** Checking out HSAttachmentPicker at "1.0.11"
*** Checking out CryptoSwift at "0.15.0"
*** Checking out pusher-websocket-swift at "7.2.0"
*** xcodebuild output can be found in /var/folders/xr/l9qrll5x1lv6jmd6z36_bvsr0000gn/T/carthage-xcodebuild.NWoDQZ.log
*** Building scheme "CryptoSwift" in CryptoSwift.xcworkspace
*** Building scheme "HSAttachmentPicker" in HSAttachmentPicker.xcworkspace
*** Building scheme "Reachability" in Reachability.xcodeproj
*** Building scheme "Starscream" in Starscream.xcodeproj
*** Building scheme "PusherSwift" in PusherSwift.xcworkspace
*** Skipped building beacon-ios-sdk due to the error:
Dependency "beacon-ios-sdk" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/helpscout/beacon-ios-sdk/issues/new
  ```
</details>

**Comment by codenameDuchess** [comment]
Thanks for giving this a try. So sorry for the error on my part. We no longer make the project file available in the repo, so this is why the local build workaround is not an option in this case. Will let you know once our update for the beta is available and we get a chance to address #78 for cocoapods.

**Comment by jasongaare** [comment]
Sounds great, thanks for the update. Right now I’ve been installing all the dependencies with Carthage, while downloading the zip from the GitHub Releases page for the actual Beacon.framework file (which is not ideal ha!)

**Comment by adrianne-helpscout** [comment]
Internal tracking ticket:

- https://helpscout.atlassian.net/browse/IOSSDK-228

**Comment by ScottPetit** [comment]
Hey @jasongaare, I'm not sure if this one is still relevant to you, but the latest version 2.0.0 is now built as a library for distribution.  Thanks for filing the issue.
