### ISSUE TITLE
HSAttachmentPickerPhotoPreviewController' is missing a [super viewWillAppear:] call

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#76]
Beacon version: 1.0.5

When analyzying my build in XCode I found that there is a bug in HSAttachementPickerPhotoViewController.m

```
- (void)viewWillAppear:(BOOL)animated {
    [super viewDidAppear:animated];

    if (self.navigationController.navigationBarHidden) {
        [self.navigationController setNavigationBarHidden:NO];
        self.wasNavigationBarHidden = YES;
    }
}

```

The function calls the wrong method in the super class, which may lead to unexpected behavior. It should call super.viewWillAppear and not super.viewDidAppear.

**Comment by shaunmcilroy** [comment]
Hi @sipersso - can you confirm if you've tested to see if the same issue exists in the 2.0.0 Beta 2 Release?

**Comment by sipersso** [comment]
@shaunmcilroy I am not using pre-release software in production. When you release the 2.x release I can confirm if it is there or not.

**Comment by ScottPetit** [comment]
Hey @sipersso, thanks for catching this.  It'll be fixed in our next release.  Also just a fun little fact, you do have access to `HSAttachmentPicker` since it's open source [here](https://github.com/helpscout/HSAttachmentPicker) 😄.

**Comment by sipersso** [comment]
@ScottPetit Thanks Scott! I didn't know ;) Thank you for the quick response!
