### ISSUE TITLE
Update Beacon to be distributed as a Static framework

### ISSUE THREAD

**Issue by shaunmcilroy** [helpscout/beacon-ios-sdk#77]
Original report:
@ScottPetit I was under the impression, per cocoapods release notes [here](http://blog.cocoapods.org/CocoaPods-1.5.0), that since cocoapods 1.5.0 and xcode 9, you no longer need to `use_frameworks!` with swift libraries.  While removing Flipper (a debugging utility) in a simple sample project like this is trivial, enabling `use_frameworks!` in our production app breaks some of our other critical dependencies.  Could this be an issue with how the Beacon pod is distributed? or how the `vendored_frameworks` is compiled?

_Originally posted by @NappyPirate in https://github.com/helpscout/beacon-ios-sdk/issues/67#issuecomment-647655437_

**Comment by shaunmcilroy** [comment]
This request has been filed and we are tracking it on our internal card here: https://helpscout.atlassian.net/browse/IOSSDK-210

**Comment by jasongaare** [comment]
This is very exciting to me, I've been wrestling the last two weeks trying to get this installed in our React Native application and was hitting the exact same hurdles outlined in #67 

I've currently had to install the framework manually, then am using Carthage to install the dependencies, as I cannot install the current beta using Carthage (see #75)

I know this is a relatively new issue, but any chance there is any kind of ETA on when this might be shipped as a static framework? I'm trying to help my support team why we are held up releasing this in our application.

**Comment by ScottPetit** [comment]
Hey @jasongaare I totally get the desire for an ETA and I'm sorry getting the beta integrated has been such a hassle.  That said we don't have a date we're able to speak to as it's a policy for us not to give out dates (as timelines can slip, etc.).  We're actively working on the next release though and will be sure to let you know here as soon as it's available.

**Comment by ScottPetit** [comment]
@NappyPirate since I believe you've integrated 2.0.0 since you filed [Issue 87](https://github.com/helpscout/beacon-ios-sdk/issues/87), could you double check me in your RN project if you can remove `use_frameworks!` with that release?

**Comment by NappyPirate** [comment]
@ScottPetit That is correct, I was able to integrate version 2.0.0 of the Beacon pod into our production react-native code base without using `use_frameworks!` and without any issue.  Thanks so much for the work on this!  I think this will make things a lot easier for react-native users.

**Comment by ScottPetit** [comment]
@NappyPirate That's great, glad to hear it.  

I'm going to close this out, but any future people running into issues with Static frameworks please feel free to open an issue.
