### ISSUE TITLE
Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by tiwoc** [helpscout/beacon-ios-sdk#78]
* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual
* Xcode version: 12.0 beta (12A6159)
* Beacon 2.0.0-beta.2

**Actual outcome**
Error when compiling a Swift project at `import Beacon`:
> Module compiled with Swift 5.2.2 cannot be imported by the Swift 5.3 compiler: /Users/[...]/Pods/Beacon/Beacon.framework/Modules/Beacon.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Expected outcome**
It should be possible to import the SDK no matter what version of the Swift compiler we're running (as long as it is reasonably recent).

**Suggested fix**
Swift has module stability since 5.1, but it has to be explicitly enabled via the `BUILD_LIBRARY_FOR_DISTRIBUTION` / `Build Options > Build Libraries for Distribution` setting.

See also [this question on StackOverflow](https://stackoverflow.com/questions/58654714/module-compiled-with-swift-5-1-cannot-be-imported-by-the-swift-5-1-2-compiler).

**Comment by jasongaare** [comment]
related to: #75 -- same issue with the Swift compiler version

**Comment by codenameDuchess** [comment]
Hi @jasongaare, thanks for letting us know about this issue and sorry for the trouble. Really appreciate the background and the suggested fix. 

We expect to have a new beta out very soon that was built with the latest version of Xcode but we'll look into this long term fix and let you know once we've addressed this. 

In the meantime, hopefully the carthage workaround mentioned in #75 will help avoid the wait.

**Comment by codenameDuchess** [comment]
[Internal tracking ticket](https://helpscout.atlassian.net/browse/IOSSDK-228).

**Comment by tiwoc** [comment]
> We expect to have a new beta out very soon that was built with the latest version of Xcode but we'll look into this long term fix and let you know once we've addressed this.

As far as I understand Swift module compatibility, if you don't set `BUILD_LIBRARY_FOR_DISTRIBUTION` to `YES`, you'll have to decide between supporting Xcode 11.5 or Xcode 12 beta. A library built with one of those can't be linked with code compiled with the other version. I suppose you'll want to support the latest released Xcode and therefore build with Xcode 11.5.

We'll have to remove the HelpScout SDK from our iOS 14 builds until there's either a dedicated Xcode 12 build of the SDK, or until `BUILD_LIBRARY_FOR_DISTRIBUTION` is set. Just to be clear, this isn't a huge problem for now since it isn't possible yet to submit apps to the App Store that are built with Xcode 12; everything built with Xcode 12 is still an experiment. It will only become a problem once this changes, probably in September.

**Comment by codenameDuchess** [comment]
Hi @tiwoc, thanks for providing the additional context. We do anticipate getting this into a release well before September so you should be good to go by then. Will let you know once we've gotten it in. 👍

**Comment by gtchance** [comment]
@codenameDuchess Any update on when the next beta will be released?

**Comment by andreyz** [comment]
@codenameDuchess I'm also blocked waiting for: 

1. SDK binary compatible with latest dev tools.
2. Push notification support.

Any dates, however vague, could you provide for future releases?

**Comment by shaunmcilroy** [comment]
@gtchance @andreyz We don't give out any ETAs, even vague ones I'm afraid. This is to ensure that we're not offering an artificial timeline that may slip due to unforeseen challenges leading to disappointment. When we have news to share regarding an updated version of the SDK, or any updates regarding Push Notification support you'll be among the first to hear about it.

**Comment by andreyz** [comment]
@shaunmcilroy is there at least a way to use Beacon iOS SDK that's not beta and is fully functional? I'm frankly disappointed with the quality of SDK given I'm a paying subscriber and my main product is a mobile app.

**Comment by shaunmcilroy** [comment]
@andreyz We're happy to keep you updated when those items become available but we do make it clear that the v2.0+ versions are pre-release beta editions of the SDK ([reference](https://c.hlp.sc/Jru6zBoj)). With each successive release we plan to continue resolving bugs and add new features - and we're thankful for the help of the development community for reporting those.

The latest non-beta release of the SDK is v1.0.5 ([link](https://github.com/helpscout/beacon-ios-sdk/releases/tag/1.0.5)) however this contains none of the live chat updates so you can opt to introduce that into your app, then update when we come out of Beta later in the year. I hope that helps for now, but if you have any other questions drop us an email and we'll be happy to continue the conversation in a more focused place.

**Comment by ScottPetit** [comment]
Hey @andreyz, @gtchance, @tiwoc just wanted to let y'all know that the latest version (2.0.0) of the SDK is now built for distribution.  Let us know if you run into any issues with, and thanks for all the context.
