### ISSUE TITLE
Translations from Beacon Web UI not displaying [2.0 Beta 2]

### ISSUE THREAD

**Issue by jasongaare** [helpscout/beacon-ios-sdk#79]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [x] Manual

When running Beacon on iOS, the translations from the Beacon Web UI are not displaying as anticipated. The expected outcome is on the right, but as you can see the default text is displaying on the left.

![Screen Shot 2020-07-07 at 9 50 29 AM](https://user-images.githubusercontent.com/15896334/86799435-8c6e6200-c037-11ea-814b-b21efea30f6f.png)

Here's my settings when opening the Beacon:

```
beaconSettings = [[HSBeaconSettings alloc] initWithBeaconId:helpscoutBeaconID];
beaconSettings.chatEnabled = YES;
beaconSettings.messagingSettings.contactFormAllowAttachments = YES;
beaconSettings.useLocalTranslationOverrides = NO;
```

I'm pretty sure that `useLocalTranlationOverrides` defaults to false, but I wanted to explicitly set it to try to make it work. I've also: (1) removed all my derived data, (2) cleaned my Xcode project, (3) restarted my simulator and erased all contents and settings, all which proved fruitless.

**Comment by jasongaare** [comment]
Is it possible there is some sort of latency with the downloading of the translations? I just noticed they now came through, after using the simulator for roughly 20 minutes.

**Comment by shaunmcilroy** [comment]
Hey @jasongaare - looks like we're not respecting the web keys for that screen so we'll need to get that investigated by the team. I'll log a card for this and keep you in the loop when we have an update.

**Comment by ScottPetit** [comment]
Hey @jasongaare, again not sure how relevant this is anymore, but the iOS SDK now respects those translations and presents them appropriately.  Thanks for raising this.
