### ISSUE TITLE
useLocalTranslationOverrides don't overrides all contact Beacon

### ISSUE THREAD

**Issue by amolieres** [helpscout/beacon-ios-sdk#8]
* Beacon install method:  
CocoaPods -> using updated Beacon pod 0.57

**Actual outcome**
There is some string not overrided when useLocalTranslationOverrides is activated

**Expected outcome**
Beacon should translate all string with BeaconLocalizable (look on subHead on the sreen above) 

**Screenshots or GIFs**
![translatesubhead](https://user-images.githubusercontent.com/44435734/47436243-6abb4180-d7a6-11e8-99e4-38f4457d459e.png)

PS: Sorry for my english... I'm french ;)

**Comment by jgritman** [comment]
This bug is fixed in 0.58. Let us know if you're still seeing any missing translations. Merci!

**Comment by amolieres** [comment]
Thanx, work perfectly with 0.58 version 👍 

Maybe you can olso translate the attachement Action Sheet components 
![img_0107](https://user-images.githubusercontent.com/44435734/47709429-81dbb280-dc30-11e8-9554-02fa85ebbd4c.PNG)

The header in messaging history (there is no translation for "History" in translate local file, in french it's "Historique"):
![img_0108](https://user-images.githubusercontent.com/44435734/47710787-f2380300-dc33-11e8-9719-8720b24ca89d.PNG)

And at last in a message history there is "you" ( in french "vous") and "Just now" (in french "A l'instant") not translated

![img_0109](https://user-images.githubusercontent.com/44435734/47710931-4c38c880-dc34-11e8-967d-9aaffc5022d1.PNG)

It's nothing dramatic so we'll start using Beacon 2.0 for our ios app in beta for some selected user. Should I open a new issue for this 3 little missings translations ?

have a good day ;)

**Comment by jgritman** [comment]
@amolieres Sure we'll get these translations in the next version, hopefully out later this week. No need to open another issue!

**Comment by jgritman** [comment]
@amolieres Sorry for the delay, but the new build 0.67 is out with those translation fixes (plus a few others we found testing). Let us know if you run into any other issues!

**Comment by amolieres** [comment]
No problem ;) Thanx for the translation fixes it work like a charm !
I send you a pull request with more accurate french translation and with some missing keys on french localized BeaconLocalizable file 
We can now start to test Beacon with some users with beta testing state
