### ISSUE TITLE
Beacon remembers navigation state even after being closed

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#80]
This issue can easily be seen in the HelpScout mobile app v.1.20.3 and is also present in the SDK version 1.0.5

Steps to reproduce
1: Open the HelpScout app
2: Press get help
3: Press get in touch. You are now in the contact screen.
4: Close the beacon
5: Open the beacon again.

Expected:
Opening the beacon should always result in the same screen being opened.

Actual:
In step 2 I am taken to the support screen, but in step 5 I am taken directly to the contact screen.

**Comment by shaunmcilroy** [comment]
Hi @sipersso - when "closing" the Beacon we're not passing a reset command that puts Beacon back at Step 1 each time so that you're back to the original "Support" screen. When you click the Beacon X you're minimizing Beacon, allowing you to return to the app and then resume your place in Beacon when you're ready to continue composing your message. 

This is how it works on all versions of the embed ([web example](https://c.hlp.sc/6quemDGR) | [iOS example](https://c.hlp.sc/o0u8bxJN)) and we don't have plans to change how this works moving forward, and when the newer 2.1 version of Beacon launches on iOS later this year it'll follow the same flow. 

Hope that clarifies the behaviour!

**Comment by sipersso** [comment]
Thanks for clarifying this. I definitely don't agree with the behavior though. If the beacon is minimized, shouldn't the icon reflect that? On the web it makes sense as the beacon button is persistent. Thus it doesn't appear to be fully closed from the user perspective. But in the mobile app, the beacon is completely gone when you close it. From a user perspective it is closed, not minimized. Thus it doesn't make sense that it remembers state.

**Comment by shaunmcilroy** [comment]
@sipersso On the web the Beacon button can be persistent, or you can use the Manual option to tie it to a link or other internal option of your choosing so there's never a persistent visual reminder. For both screens it's important to give the customer an opportunity to return to the same open screen on Beacon if they need to temporarily minimize it (either to search for additional information requested inside the app (via SDK) or via their web browser. 

In the flow you're describing, we'd see a less helpful customer flow if that user were to start entering text, click close, grab the additional information and then reinitialize Beacon to find their message has been wiped, or they need to navigate back to the screen again. 

We'll keep this issue here for visibility should other customers implementing their Beacons feel strongly about this in the future but we have no plans to change this.

**Comment by sipersso** [comment]
If there is a way to minimze, I think there should be a clear way to maximize as well. This isn't the case in the mobile apps. Let's just agree that we disagree here ;)

I tried to open the beacon using  HSBeacon.navigate("/", beaconSettings: settings) instead. This is close to the behaivor I want. However, it seems like it first opens the beacon in it's previous state before animating back to the start destination. Is there any way to disable the animation? Calling reset is not an option as it will clear emails, which I don't want. 

I just want the help and support button to always start at the welcome screen.

**Comment by shaunmcilroy** [comment]
We don't have a method to disable animations in the SDK, or in the web app (we only have one to disable the pulse animation). The navigation methods are used to allow you to route folks to specific screens which means we'll not reset the default position of the Beacon back to Support **if you're on another screen** before heading to "Previous Messages" for example. 

**I just want the help and support button to always start at the welcome screen.**
As we've covered there isn't a way for you to do that outside of resetting the Beacon each time, but as you note - that'll clear out any pre-filled information like emails. 

We'll let you know if that changes in the future, but for now you can expect Beacon to continue working along the current established pattern.

**Comment by sipersso** [comment]
I am sorry to hear that. This means that there is no way in my app to make sure that the same navigation button always goes to the same destination without unwanted visual side effects.

**Comment by sipersso** [comment]
Ok, this will be my last message on why I think the current behavior is problematic. 

Background:
I use the beacon to provide context sensitive help to my users. In different areas of the app, I am there fore opening the beacon using different settings with different articles preloaded. 

Consider the following senario. 

1: The user opens the beacon from screen 1 where relevant articles to screen 1 is shown. 
2: The user contacts support and the user is navigated to the "We're on it" screen
3: The user opens the beacon from screen 2 where I have configured relevant articles to screen 2. 

In this case, the user will not be taken the relevant articles to screen 2, instead the user will be taken to the "We're on it"-screen and will never see the help articles related to the screen the user is on, unless he presses "back". Don't you think this behavior is confusing?

**Comment by sipersso** [comment]
> Hi @sipersso - when "closing" the Beacon we're not passing a reset command that puts Beacon back at Step 1 each time so that you're back to the original "Support" screen. When you click the Beacon X you're minimizing Beacon, allowing you to return to the app and then resume your place in Beacon when you're ready to continue composing your message.
> 
> This is how it works on all versions of the embed ([web example](https://c.hlp.sc/6quemDGR) | [iOS example](https://c.hlp.sc/o0u8bxJN)) and we don't have plans to change how this works moving forward, and when the newer 2.1 version of Beacon launches on iOS later this year it'll follow the same flow.
> 
> Hope that clarifies the behaviour!

Hi Shaun! I just tried this on the Android SDK and it doesn't behave the same as the iOS app and the web. 

On Android repeating the following steps will lead to the same screen being shown in step 2 and step 5 on Android, but not on iOS:
1: Open the HelpScout app
2: Press get help
3: Press get in touch. You are now in the contact screen.
4: Close the beacon
5: Open the beacon again.

Any reason the behavior is different between iOS and Android? Is this a bug in the Android SDK?

**Comment by shaunmcilroy** [comment]
Hi @sipersso the Help Scout app does not use the latest version of the SDK, which you note above is using v1.0.5. This version of the SDK is no longer under active development, with all future fixes and improvements moving forward being delivered for v2.0.0+ of the SDK. 

I'll raise a question with the Android team to determine if their current flow is correct for that platform, but as for the [iOS](https://c.hlp.sc/o0u8bxJN) and [Web](https://c.hlp.sc/Qwu0DdgG) both of these flows follow the currently established pattern of being able to resume the Beacon from the previous screen when reactivated.

**Comment by sipersso** [comment]
For Android, I am using 2.1.2 and it has the same behavior as the HelpScout Android app, so it is still inconsistent between the iOS and Web behavior. Personally I think Android and Web is doing the right thing and being consistent with how platform navigation works.

**Comment by sipersso** [comment]
I just found this in the Android SDK. There is a BeaconScreens setting that allows developers to choose which screen to open. This API doesn't exist on iOS right? It would be exactly what I am after. 

```/**
 * BeaconScreens allows developers to choose which screen to open when the Beacon is launched
 */
enum class BeaconScreens {

    /**
     * Opens to the Home (Ask/Answers) screen
     */
    DEFAULT,

    /**
     * Search results screen (requires a search parameter and docs enabled)
     */
    SEARCH_SCREEN,

    /**
     * Contact form (requires messaging enabled)
     */
    CONTACT_FORM_SCREEN,

    /**
     * Article screen (requires an Article ID and docs enabled)
     */
    ARTICLE_SCREEN,

    /**
     * Previous Messages if any exist.
     */
    PREVIOUS_MESSAGES,

    /**
     * Chat Screen
     */
    CHAT
}
```

**Comment by shaunmcilroy** [comment]
After talking with the Android team we're going to make a corrective change to bring the current behaviour in-line with the existing web and iOS behaviours. Thanks for highlighting that as I can see how it would be confusing for one screen to be out of sync.

For iOS, the HSBeacon we've some navigation methods which opens the Beacon and shows a specific screen. Available routes are listed here:
https://developer.helpscout.com/beacon-2/ios/#navigate-to-a-specific-screen

For any changes on either platform we are unable to notify on specific changes which may (or may not) happen in future releases. The best way to remain informed is to watch the repo for any releases that come in the future and we'll have everything that changes documented in line.

**Comment by sipersso** [comment]
@shaunmcilroy I tried that method and it is almost what I want. Unfortunately, it doesn't look good. The SDK to flash the previous screen before navigating to the one I am after using animations. I am not sure you would ever want an animation in this case, but there is no way to disable it as you pointed out.

**Comment by shaunmcilroy** [comment]
Yeah, that's the downside for you. Sorry we don't have a workaround in the meantime. We'll look to track interest in disabling those deep link animations as we continue to progress with the items currently on our radar for the SDK. If we make any changes we'll update you here directly @sipersso
