### ISSUE TITLE
Incomplete Manual SDK integration instructions [2.0 Beta 2]

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#81]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [x] Manual

Beacon.framework is added to the project according to README and https://developer.helpscout.com/beacon-2/ios/

**Actual outcome**
My app target fails to build with `Module 'PusherSwift' not found` error.

**Expected outcome**
Beacon should not prevent the app target from compiling.

**Screenshots or GIFs**
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/205317/89156981-fa8d4280-d56b-11ea-9ffc-e48d957e03b5.png">

**Comment by shaunmcilroy** [comment]
Hey @andreyz, can I redirect you to take a look at the conversation here where another user has reported the same issue. Our engineer @ScottPetit has outlined a number of potential routes you can investigate: https://github.com/helpscout/beacon-ios-sdk/issues/67#issuecomment-644165921

Let us know if any of those help solve this issue

**Comment by andreyz** [comment]
Hi @shaunmcilroy and thanks for replying. Yes, the linked issue is related to mine, although I wasn't following CocoaPods or Carthage installation steps. 

I've managed to resolve my problem by building SDK's dependencies with Carthage and then adding those to my project alongside Beacon.framework. 

Hence my original issue — your installation instructions are incomplete, they don't mention the dependencies.

**Comment by shaunmcilroy** [comment]
Hi @andreyz - we plan to fully update the documentation for the SDK upon general release. This is something the team are aware of and will update this request to confirm this has been actioned when it's rolled out.

**Comment by ScottPetit** [comment]
We're tracking this internally [here](https://helpscout.atlassian.net/browse/IOSSDK-302).

**Comment by ScottPetit** [comment]
Hey 👋 @andreyz just wanted to let you know that the documentation has been updated to reflect the steps needed for manual integration with the latest version (2.0.0).
