### ISSUE TITLE
When clicking push notification, user is not taken to the conversation.

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#82]
When clicking a push notification for an email reply, it doesn't seem like the view is updated and the user is presented with the "We're on it" screen instead of the updated conversation. In the 2.0.0-beta, when docs and chat is disabled it doesn't seem possible to get to the conversation at all!  

Beacon version: 1.0.5 and 2.0.0-beta.2.

Steps to reproduce:
1: Make sure push notifications is enabled for the project and that chat and docs is disabled for the beacon. 
2: Open the beacon and send a message.
3: Minimize the app
4: Reply to the message in helpscout (which will trigger a push notification)
5: Click the push notification on the mobile device. 

Expected result:
The customer should be taken straight to the conversation. 

Actual result:
The customer is taken back to the "We're on it!"- screen and is being told that he/she will receive an email reply within a few hours. In 2.0.0 beta If I press the "Previous conversations" button or the back button nothing happens and I can't get to the conversation no matter what I do. This seems to be a change from 1.0.5 where I could get to the conversation by pressing previous conversations. 

See attached video. 
[Push_notification_bug.zip](https://github.com/helpscout/beacon-ios-sdk/files/5027024/Push_notification_bug.zip)

**Comment by sipersso** [comment]
Will retry this issue with the latest beta sdk before reopening..

**Comment by sipersso** [comment]
Tested on 2.0.2-beta2 and the issue is even worse there. There is no way to get to the conversation after opening a push notification.

**Comment by hs-gv** [comment]
Hello @sipersso, thanks for reporting this.  I'm happy to report that the team has fixed this bug on the upcoming release.  We'll let you know when the new SDK version is made public.

**Comment by sipersso** [comment]
Awesome! Thanks!

**Comment by adrianne-helpscout** [comment]
@sipersso Just wanted to let you know that we pushed out a new release today and this issue should be fixed.

**Comment by sipersso** [comment]
Awesome! I'll try it out straight away.
