### ISSUE TITLE
iOS long English text & long link cannot wrap

### ISSUE THREAD

**Issue by cbhhhhh** [helpscout/beacon-ios-sdk#83]
* Beacon version: 2.0.0 Beta 2 Release

**Actual outcome**
As the title shows, iOS long English text & long link cannot wrap, when you receive or send these two types of information in the app, you need to keep swiping right to see the complete content. I hope it can be resolved as soon as possible! 
thank you :)

**Expected outcome**
Beacon should wrap automatically and display in full

**Screenshots or GIFs**
![test text IOS](https://user-images.githubusercontent.com/49544557/90103511-35198b00-dd75-11ea-8af9-c90c17521646.PNG)

**Comment by scottyab** [comment]
Thanks for raising this @cbhhhhh I've recreated the issue and logged an internal issue for this https://helpscout.atlassian.net/browse/IOSSDK-313

**Comment by codenameDuchess** [comment]
@cbhhhhh 👋 Thanks for reporting this issue. We wanted to let you know we fixed this in the latest version (2.2.0). You can read more about what's in this release in our [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
