### ISSUE TITLE
Users replys in the mail, but we can‘t receive the message in the help scout background

### ISSUE THREAD

**Issue by cbhhhhh** [helpscout/beacon-ios-sdk#84]
* Beacon install method: 2.0.0 Beta 2 Release

Note：This is not only a problem for the iOS SDK, Android also has this problem

**Actual outcome**
1. The user submits a question in the app
2. We responded to user questions in the help scout background
3. The user received a reply in the mailbox（such as Gmail） and replied to us via the mailbox
4. At this time, our support team cannot receive the reply sent by the users' mailbox in the help scout background

**Expected outcome**
Regardless of whether the user replied to the message via app beacon or email, the help scout backend should be able to receive the reply, otherwise the information will be missed, which is very important to us

**Screenshots or GIFs**
This problem is not easy to show with pictures, you can try it (recommend using multiple emails to try)

**Comment by scottyab** [comment]
Hey @cbhhhhh This doesn't sound like an issue relating to the mobile SDKs and maybe something to do with incoming email for the mailbox? 

To clarify If a customer replies to a conversation they started in the SDK via gmail that message should be shown when they load/refresh the previous conversation in Beacon. Please note a reply by email doesn't appear immediately like with a reply via SDK as its travelling via email servers and has to be parsed (the delay can be a minute or two.) 

I've just tested this in the Android SDK and it works as described.  Here's the steps:

1. In your App/SDK: With a valid email, create a new message
2. In your App/SDK: Open previous conversations to the message has sent.   
3. In Web browser on Help Scout.net - find the new incoming message, reply with text "ABC". 
4. In gmail, see the new email with "ABC" and reply with message "XYZ"
5. In Web browser on Help Scout.net verify the message with "XYZ" has been received
6. In your App/SDK: Open previous conversations or pull down to refresh to verify message with "XYZ" is visible.   

See the example screen shot below.  

![Image 2020-08-13 at 12 18 19 pm](https://user-images.githubusercontent.com/404105/90128742-4788ca00-dd5f-11ea-89ba-8795becff2d1.png)

**Comment by cbhhhhh** [comment]
thanks, we found no problems after testing :)
