### ISSUE TITLE
Regression: Navigation Color Lost

### ISSUE THREAD

**Issue by parrots** [helpscout/beacon-ios-sdk#85]
Beacon 2.0

* Beacon install method: [ ] Carthage, [ X] CocoaPods, [ ] Manual

**Actual outcome**
When viewing the beacon a second time, the navigation bar reverts back to a white color. This is problematic if you're using a white tint color (white text, blue custom BG), as then the white close button is not visible. 

Removing any color customization in-app (tintColor and color in the settings) yields the same issue, a white nav bar.

**Expected outcome**
Should remain the same color.

**Screenshots or GIFs**
First time, default settings:
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-18 at 10 32 05](https://user-images.githubusercontent.com/171163/90526167-1123c400-e13e-11ea-9aac-b6ca7f82983b.png)

Second time, default settings:
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-18 at 10 30 24](https://user-images.githubusercontent.com/171163/90525983-d588fa00-e13d-11ea-9be2-ada43838b935.png)

Second time, color customization issue:
![Simulator Screen Shot - iPhone 11 Pro - 2020-08-18 at 10 26 44](https://user-images.githubusercontent.com/171163/90525868-bb4f1c00-e13d-11ea-8e3c-3e86e04bd52f.png)

**Comment by sipersso** [comment]
This is related to: https://github.com/helpscout/beacon-ios-sdk/issues/73. The beacon doesn't seem to be consistent in the way it sets the navigationbar appearance.

**Comment by jotaemepereira** [comment]
@parrots Thanks for reporting the issue. Like @sipersso mentioned, this is related to #73, where he provided a workaround using the [close](https://developer.helpscout.com/beacon-2/ios/#open-and-close-events) Beacon event.

We are going to work on this issue in this [internal card](https://helpscout.atlassian.net/browse/IOSSDK-203), and we will let you know when it gets fixed. Thanks!

**Comment by sipersso** [comment]
@parrots Don't use the workaround I presented. It isn't reliable. I decided to revert back to 1.0.5 until #73 is fixed.

**Comment by ScottPetit** [comment]
👋 Hey @parrots,

Thanks for letting us know about this so quickly.  It should be resolved with version 2.0.1 which should now be available on the Cocoapods CDN.  You can check out what else was fixed in the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
