### ISSUE TITLE
HSBeacon.handlePushNotification crashes the app

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#86]
Beacon: 2.0.0

Whenever I try to open a push notification from HelpScout the app crashes with the following stacktrace

```
2020-08-18 16:41:05.808577+0200 MyApp[13449:2964567] Email (null) sent to BeaconUser is invalid. Ignoring.
2020-08-18 16:41:05.888304+0200 MyApp[13449:2964567] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL URLByAppendingPathComponent:]: component, components, or pathExtension cannot be nil.'
*** First throw call stack:
(0x1bc3f9654 0x1bc11bbcc 0x1bc6e6dc4 0x10169b7cc 0x1016c1934 0x1016c0658 0x1016c01d4 0x1016c33c8 0x1016c31dc 0x1014af1ec 0x1014d15a8 0x1014d1b80 0x1c04c0ff8 0x1bfac2ab4 0x1bfac3b68 0x1c0049a08 0x1c15810a8 0x1c15a5684 0x1c158abfc 0x1c15a55b8 0x10778f730 0x107792bb0 0x1c15c9850 0x1c15c951c 0x1c15c9a44 0x1bc377ad8 0x1bc377a30 0x1bc3771b8 0x1bc3721e8 0x1bc371ba8 0x1c64e1344 0x1c04ad3e4 0x100f4b14c 0x1bc1f98f0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

This happens when the application is open. If it is closed and I press the push notification, then nothing happens. 

Any ideas? I am not using secure mode if that makes a difference

**Comment by jotaemepereira** [comment]
Hey @sipersso, I tried to reproduce the crash but I wasn't able to. Some questions:

- Is this happening with all push notifications from conversations?
- Can you provide me with your Beacon configuration?

About the steps to reproduce it, what I tried was:
- From a new user (not using secure mode) I sent a new message through the contact form
- I close the app and Beacon, and I responded to the customer from Help Scout
- The push notification is shown
- I open the app again and I press the push notification
- It takes me to the previous conversation screen

Are those the same steps where you are experiencing the crash?

**Comment by sipersso** [comment]
Hi!

It was an error on my part. For push notifications I had missed to set the beacon id in the constructor of the Beacon Configuration. When changing this, push notifications work as expected and take you to the conversation and it doesn't crash.

However, I think there is a few points of improvement here:

1: The error message in the crash could be made clearer. It wasn't until you told me to check the beacon settings that I found out that this was the cause of the error. Or at least the error message could be changed. When you get: "'NSInvalidArgumentException', reason: '*** -[NSURL URLByAppendingPathComponent:]: component, components, or pathExtension cannot be nil.'" it isn't clear what is going on. 

2: Documentation needs an update: The handleWillPresentNotification method doesn't exist [https://developer.helpscout.com/beacon-2/ios/#push-notifications-1](https://developer.helpscout.com/beacon-2/ios/#push-notifications-1)

3: If a beacon id is required for HSBeaconSettings, then maybe there shouldn't be an empty constructor?

I will close this issue, since it was a configuration error on my part. Thanks for the feedback!

**Comment by jotaemepereira** [comment]
Thanks for your feedback! 

About the points you made:
1 - You are right, we could improve the exception message when the Beacon ID is not set.
2 - The method exists, but on Swift is `handleWillPresent(notification ...)`. I'm going to update the documentation to reflect both Objective-C and Swift scenarios.
3 - As point number one, we could better handle the no Beacon ID scenario.

**Comment by sipersso** [comment]
Thanks for the comments. I found the handelWillPresent method now. However, this method does not have a viewController argument, and in my case it means that I risk it not being displayed if a modal view is being displayed, so I am not able to use it. 

I assume that the handleWillPresent is just a shortcut for passing notification.request.content.userInfo into the handleNotification method anyway? Right now I am extracting the userInfo from notification.request.content.userInfo and this seems to work well. Any downsides of this?

**Comment by ScottPetit** [comment]
@sipersso `handleWillPresent` is really only used for chat notifications currently.  And is meant to be called from [this UNUserNotificationCenterDelegate](https://developer.apple.com/documentation/usernotifications/unusernotificationcenterdelegate/1649518-usernotificationcenter).  This is because we don't show chat notifications if the user is currently viewing the chat screen but do show them if they're elsewhere in the app.

Since this method isn't responsible for presenting the notification, only for determining if a notification should be shown or not, it does not include a `UIViewController` as a parameter.  What use case would you have for passing a `UIViewController` as an argument?

**Comment by sipersso** [comment]
@ScottPetit I am not using chat, just email. But I still want the notification to appear if the app is in foreground, not just in the backround. Isn't this supposed to work when chat is disabled as well?

According to the documentation:
"To handle whether notifications are displayed to the user you should forward any relevant notifications from your UNUserNotificationCenterDelegate userNotificationCenter:willPresentNotification:withCompletionHandler: method to Beacon through the [HSBeacon handleWillPresentNotification:withCompletionHandler:] method. Beacon will only call the completionHandler if it is a Beacon notification."

However, the completion handler isn't called and the notification isn't presented to the user. I guess this is a bug?

**Comment by ScottPetit** [comment]
@sipersso Yea it seems like when we introduced this functionality we tied it to chat and had an oversight on having non chat notifications show.  We'll track that bug [internally here](https://helpscout.atlassian.net/browse/IOSSDK-317).

Do you have a crash log for when you interact with the notification while the message screen is displayed.  Also just to verify by message screen do you mean viewing the conversation that you just started?

Also just to circle back you should be passing in `notification.request.content.userInfo` so that's definitely correct.  Also do you still see a need for `handleWillPresent` to take a view controller or is the current interface ok?

**Comment by sipersso** [comment]
I guess it depends on what handleWillPresent does? If it only calls the completion handler, then there is no need. But if it will be able to display a viewcontroller, then it won't work if the app is already presenting a modal controller. 

Yes, If I get a push notification of a response while viewing the conversation and click the push. I implemented a workaround for the crash, by adding state for when the beacon is opened or not. If the beacon is already opened and I get a notification, I just ignore it. The error message is that you can't present a viewcontroller that is already active. I can't get you a stacktrace today, but I may be able to get you one tomorrow if needed.
