### ISSUE TITLE
Chat transcript message shown regardless of transcript setting

### ISSUE THREAD

**Issue by NappyPirate** [helpscout/beacon-ios-sdk#87]
* Beacon version 2.0.0
* Beacon install method: [ ] Carthage, [X] CocoaPods, [ ] Manual

**Actual outcome**
After a chat has ended the following messaged is always displayed "All done! A copy of this conversation will land in your inbox shortly."

**Expected outcome**
The message about the conversation landing in the user's inbox should only display if the beacon is configured to send an email transcript after the chat has ended.

**Screenshots or GIFs**
![Image 2020-08-18 at 11 57 43 AM](https://user-images.githubusercontent.com/6239901/90544500-d2493a80-e14c-11ea-8374-2ae2bb62916a.png)

**Comment by jotaemepereira** [comment]
👋  Hey @NappyPirate thanks for raising this. I just confirmed this bug is happening, I've added this [card](https://helpscout.atlassian.net/browse/IOSSDK-316) for internal tracking and we will let you know as soon as we address it. Thanks!

**Comment by ScottPetit** [comment]
👋 Hey @NappyPirate,

Just wanted to let you know that we resolved this issue in the latest version 2.0.1.  More info is available in the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).  Thanks for reporting it.
