### ISSUE TITLE
HSBeaconDelegate methods not called when swiping down to dismiss on iOS 13+

### ISSUE THREAD

**Issue by sipersso** [helpscout/beacon-ios-sdk#88]
When using HSBeacon.openArticle() the delegate methods onBeaconOpen and onBeacon close does not get called. 

This means that the workaround listed in https://github.com/helpscout/beacon-ios-sdk/issues/73 doesn't work if HSBeacon.openArticle is being used.

Steps to reproduce:
1: Call HSBeacon.openArticle, and make sure the delegate is set on the HSBeaconSettings you pass in. 
2: Close the article and close the beacon. 

Expected result:
The HSBeaconDelegate method onOpen should be called when the beacon is opened and onClose should be called when the beacon is closed. 

Actual result:
None of the HSBeaconDelegate methods are called. 

In my app I am linking to help articles from the "What's new" screen right on app launch. If the user opens an article, which opens the beacon, and presses "get in touch", the navigationbar color will be wrong during due to https://github.com/helpscout/beacon-ios-sdk/issues/73 and the workaround listed cannot be applied.

**Comment by jotaemepereira** [comment]
👋 Hey @sipersso, thanks for reporting this, I did some testing on our side and both `onBeaconOpen` and `onBeaconOpen` delegates were called after using `HSBeacon.openArticle`. 

I will ask you some questions so you can help me with reproducing it:
- Can you provide which parameters are you passing to the `HSBeacon.openArticle`? 
- Can you send me your Beacon configuration? 

I will continue doing some digging on my side too. Thanks.

**Comment by sipersso** [comment]
@jotaemepereira I have opted to revert to 1.0.5 due to #73. I'd be happy to test this once #73 is fixed so I can upgrade to the latest version of the SDK. I guess it is no use to verify it on 1.0.5.

**Comment by sipersso** [comment]
@jotaemepereira I think I figured it out. If you press the X button, the delegate gets called. However, if you swipe down to close the modal, it doesn't. This behavior is new in iOS 13... and very easy to miss. I guess you will have to implement   [UIAdaptivePresentationControllerDelegate](https://developer.apple.com/documentation/uikit/uiadaptivepresentationcontrollerdelegate) to fix it?

**Comment by ScottPetit** [comment]
👋 Hey @sipersso,

Just wanted to let you know that we resolved this issue in the latest version 2.0.1.  More info is available in the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).  Thanks for reporting it.
