### ISSUE TITLE
Is there an example using initializeAutomaticPushNotificationHandlingWithMethodSwizzling

### ISSUE THREAD

**Issue by SMJ93** [helpscout/beacon-ios-sdk#90]
Is there a working example with `[HSBeacon initializeAutomaticPushNotificationHandlingWithMethodSwizzling]`?

* Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual:

`pod 'Beacon', '2.0.0'`

I get the following when trying to use it:

`No known class method for selector 'initializeAutomaticPushNotificationHandlingWithMethodSwizzling:'`

**Comment by ScottPetit** [comment]
Hey @SMJ93, you wouldn't happen to be using Swift would you?  The signature in Swift is,

```swift
HSBeacon.initializeAutomaticPushNotificationHandling(withMethodSwizzling: true, overrideUserNotificationCenterDelegate: true)
```

**Comment by SMJ93** [comment]
Hi @ScottPetit , nope i'm using Objective C.

In my AppDelegate:

```
#import "Beacon/Beacon.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [[HSBeacon initializeAutomaticPushNotificationHandlingWithMethodSwizzling]
                                                   methodSwizzling:true
                                                   overrideDelegate:true];
  ...
}

**Comment by ScottPetit** [comment]
@SMJ93 Gotcha.  In Objective-C it should look like

```objc
[HSBeacon initializeAutomaticPushNotificationHandlingWithMethodSwizzling:YES overrideUserNotificationCenterDelegate:YES];
```

I'll get the docs updated to make this more clear.  Let me know if you run into any issues.

**Comment by jotaemepereira** [comment]
[Card](https://helpscout.atlassian.net/browse/IOSSDK-321) for internal tracking

**Comment by SMJ93** [comment]
Great that works! Thanks @ScottPetit
