### ISSUE TITLE
Transparent background view when opening Beacon controller

### ISSUE THREAD

**Issue by rafaelks** [helpscout/beacon-ios-sdk#92]
**Installation:** CocoaPods, version 2.0.0

```swift
let settings = HSBeaconSettings(beaconId: "#hidden#")
settings.tintColorOverride = .blue
settings.useNavigationBarAppearance = false
settings.color = .blue

HSBeacon.open(settings)
```

**Actual outcome**

Beacon controller is opening with a transparent background, instead of the default white one.

**Expected outcome**

Background should be white (or black when in dark mode)

**Screenshots or GIFs**

<img width="862" alt="Screen Shot 2020-08-25 at 09 22 28" src="https://user-images.githubusercontent.com/551004/91173640-851d1980-e6b4-11ea-903c-b954ff50b998.png">

<img width="862" alt="Screen Shot 2020-08-25 at 09 22 23" src="https://user-images.githubusercontent.com/551004/91173655-8b12fa80-e6b4-11ea-9186-cd5b74527bb3.png">

**Comment by ScottPetit** [comment]
@rafaelks This is actually the same underlying issue as https://github.com/helpscout/beacon-ios-sdk/issues/91, so I'm going to close this here in favor of keeping the conversation in one place.

**Comment by rafaelks** [comment]
@ScottPetit The background color is an asset?

**Comment by ScottPetit** [comment]
@rafaelks the background color isn't but that view controller is loaded from a XIB.
