### ISSUE TITLE
Prevent chat push notifications from deeplinking to chat screen when app is closed

### ISSUE THREAD

**Issue by SMJ93** [helpscout/beacon-ios-sdk#93]
Is there a way to prevent the deeplinking to the chat screen when the app has been closed?

In our app the chat functionality is only available if you are logged in so we just want to deeplink to the app on push notification press if the app is closed. Is there a way to set this with the SDK?

Beacon install method: [ ] Carthage, [x] CocoaPods, [ ] Manual:
pod 'Beacon', '2.0.0'

**Screenshots or GIFs**

![RPReplay_Final1598361657](https://user-images.githubusercontent.com/2145641/91179859-f5409500-e6de-11ea-959a-23e9eeec88be.gif)

**Comment by ScottPetit** [comment]
Hey @SMJ93,

You can definitely do that, but you'll have to follow the manual integration path for push notifications instead of the swizzled.  The manual steps are documented [here](https://developer.helpscout.com/beacon-2/ios/#manual-setup).

You'd then be able to implement any logic you'd like before forwarding or not forwarding the push notification to Beacon.  Which would probably look something like

```objc
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
    // whatever check you need to verify the user is logged in
    if (isUserLoggedIn) {
        NSDictionary *userInfo = response.notification.request.content.userInfo;
        if ([HSBeacon isBeaconPushNotification:userInfo]) {
            [HSBeacon handlePushNotification:userInfo beaconSettings:beaconSettings];
        }
    }
    completionHandler();
}
```

**Comment by SMJ93** [comment]
Great, thanks @ScottPetit!

I'll give this a go

**Comment by SMJ93** [comment]
Hi @ScottPetit, i've given what you said a go and now it doesn't deeplink to the chat when you press the push notifications 🙈 

Here is my `AppDelegate.m`:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

  ...
  [HSBeacon initializeBeaconPushNotificationSupport];
}

// Push notification received in foreground
 - (void)userNotificationCenter:(UNUserNotificationCenter *)center
willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler{
   [HSBeacon handleWillPresentNotification:notification withCompletionHandler: completionHandler];
}

// Push notification received in background
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {
  
    NSDictionary *userInfo = response.notification.request.content.userInfo;
  
    if ([HSBeacon isBeaconPushNotification:userInfo]) {
         NSString *helpScoutBeaconID = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"HelpScoutBeaconID"];
         HSBeaconSettings *settings = [[HSBeaconSettings alloc] initWithBeaconId:helpScoutBeaconID];
         [HSBeacon handlePushNotification:userInfo beaconSettings:settings];
    }
  
    completionHandler();
}

// Push notification registration success
- (void)application:(UIApplication *)application
didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [HSBeacon setDeviceToken: deviceToken];
}

// Push notification registration error
- (void)application:(UIApplication *)application
didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
  [HSBeacon failedToRegisterForRemoteNotificationsWithError: error];
}
```

Here's a GIF:

![ezgif com-gif-maker](https://user-images.githubusercontent.com/2145641/91299161-1a91d980-e799-11ea-870f-513aba39d2fe.gif)

For v1 I need these 2 flows working:

- If a user presses a push notification when the app is closed - **open the app**
- If a user presses a push notification when the app is in the background or foreground - **deeplink to the relevant chat**

Cheers

**Comment by ScottPetit** [comment]
Hey @SMJ93 your implementation looks correct to me.  Just want to confirm you're setting your AppDelegate as the `UNUserNotificationCenterDelegate` like `[UNUserNotificationCenter currentNotificationCenter].delegate = self;`.

If you can confirm you're doing that, can you verify that your implementation of `- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler` is getting called?  And whether or not HSBeacon is identifying that notification as a Beacon push notification?

**Comment by SMJ93** [comment]
Ahhh that was it!!!!! Thanks @ScottPetit! I forgot to add ` [UNUserNotificationCenter currentNotificationCenter].delegate = self;`

Now I just need to check if app the was opened from background before calling `handlePushNotification`:

```
// Push notification received in background
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))completionHandler {

    NSDictionary *userInfo = response.notification.request.content.userInfo;

    [[SEGAnalytics sharedAnalytics] receivedRemoteNotification:userInfo];

    // @todo check if app was opened from background
    if ([HSBeacon isBeaconPushNotification:userInfo]) {
         NSString *helpScoutBeaconID = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"HelpScoutBeaconID"];
         HSBeaconSettings *settings = [[HSBeaconSettings alloc] initWithBeaconId:helpScoutBeaconID];
         [HSBeacon handlePushNotification:userInfo beaconSettings:settings];
    }

    completionHandler();
}
```

Nearly there!

**Comment by SMJ93** [comment]
@ScottPetit you don't happen to know how to check if the app was killed, inactive or in the background in `didReceiveNotificationResponse` do you?

I've tried lots of different solutions on StackOverflow, but can't get it working 😕 

Here's my SO question:
https://stackoverflow.com/questions/63599820/ios-unusernotificationcenter-didreceivenotificationresponse-only-run-code-if-app

Thanks

**Comment by ScottPetit** [comment]
Hey @SMJ93, I just responded on StackOverflow with a potential solution.  I didn't run the code but believe that should work with what you're trying to do.  Also surely there's a more elegant solution that Apple provides that I'm just not thinking of at the moment.  Best of luck and let us know how it goes.

**Comment by SMJ93** [comment]
Hi @ScottPetit, thank you! I managed to get it working with a few changes 🎉 

Thanks again for all your help!
