### ISSUE TITLE
First attempt to send a message says "Invalid email" error

### ISSUE THREAD

**Issue by rafaelks** [helpscout/beacon-ios-sdk#94]
**CocoaPods, version 2.0.0**

**Actual outcome**

When the user tries to send a message, the first attempt will show an error message saying that the email is not valid. By simply tapping again on the button, it works.

**Expected outcome**

It should work from the first try.

**Screenshots or GIFs**

![2020-08-26 08 19 36](https://user-images.githubusercontent.com/551004/91297669-1784f200-e775-11ea-942e-905f821a1824.gif)

**Comment by hs-gv** [comment]
Hello @rafaelks 

Thanks for reporting this.  We are able to reproduce the error and have created an [internal ticket](https://helpscout.atlassian.net/browse/IOSSDK-325) to track this bug.  We'll update you with any news on this issue.

**Comment by ScottPetit** [comment]
Hey 👋 @rafaelks,

Thanks for reporting this, just wanted to write and let you know that this is resolved with the latest version (2.0.2) of the SDK.  If you'd like to see what else is in this release take a look at the [Changelog](https://github.com/helpscout/beacon-ios-sdk/blob/master/CHANGELOG.md).
