### ISSUE TITLE
Presenting Beacon from SwiftUI

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#97]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [x] Manual

**Actual outcome**
How should `UIViewRepresentable` be adopted to be able to present Beacon from SwiftUI?

**Expected outcome**
I would strongly prefer the Beacon API that allows to integrate it without "special case" development. Current singleton presentation pattern (`HSBeacon.open(:)`) is counterproductive for adopting iOS platform technologies such as SwiftUI. Is there a reason you're not implementing a separate UIViewController for UI and singleton for configuration/background logic like most other chat platforms?

**Comment by codenameDuchess** [comment]
Hi @andreyz, thanks for reporting this issue and sharing your request that we offer an alternative to the current singleton presentation pattern. I've created a ticket for us to dig into presenting Beacon from SwiftUI and determine our recommendations for adopting UIViewRepresentable. We'll get back to you once we've had the time to dive into this one. 

[Internal tracking ticket](https://helpscout.atlassian.net/browse/IOSSDK-335).

**Comment by lewis-smith** [comment]
I'm not sure if this is going to be a valid solution or not, but here is my current work around/hack:

```
// In view body
Button(action: {
                            let settings = HSBeaconSettings(beaconId: "ce4affd4-60c0-4ff8-95b9-d100e2e7367b")
                            settings.docsEnabled = false
                            HSBeacon.open(settings, from: topViewController!)
                        }, label: {
                            Text("Contact us")
                        })


// Variables at view level

    var topViewController: UIViewController? {
        return topViewController(withRootViewController: UIApplication.shared.keyWindow?.rootViewController)
    }

    func topViewController(withRootViewController rootViewController: UIViewController?) -> UIViewController? {
        if rootViewController is UITabBarController {
            let tabBarController = rootViewController as? UITabBarController
            return topViewController(withRootViewController: tabBarController?.selectedViewController)
        } else if rootViewController is UINavigationController {
            let navigationController = rootViewController as? UINavigationController
            return topViewController(withRootViewController: navigationController?.visibleViewController)
        } else if rootViewController?.presentedViewController != nil {
            let presentedViewController: UIViewController? = rootViewController?.presentedViewController
            return topViewController(withRootViewController: presentedViewController)
        } else {
            return rootViewController
        }
    }
```

**Comment by sipersso** [comment]
UIApplication.shared.keyWindow is deprecated, so this is definitely a hack. 

Any updates on support for UIViewControllerRepresentable @codenameDuchess?

**Comment by aliripe** [comment]
Hi @sipersso,

I'm Alicia, joining @codenameDuchess. 

Unfortunately, we don't have any updates on this. It's still on our radar and the team is aware of it but I cannot offer an estimate as to when this is going to be addressed.

We will make sure you update this ticket once we have any news related to this.

**Comment by codenameDuchess** [comment]
Hi @andreyz,

I just wanted to reach out and let you know that we've made some adjustments to better support presenting from SwiftUI in our [latest release](https://github.com/helpscout/beacon-ios-sdk/releases/tag/2.2.3). We've also added a basic Swift UI example app and updated our documentation in the[ ReadMe](https://github.com/helpscout/beacon-ios-sdk#sample-applications). Thanks for reporting this issue.

**Comment by andreyz** [comment]
@codenameDuchess thank you for making it happen.
