### ISSUE TITLE
Make SDK open-source 

### ISSUE THREAD

**Issue by andreyz** [helpscout/beacon-ios-sdk#98]
* Beacon install method: [ ] Carthage, [ ] CocoaPods, [ ] Manual

**Actual outcome**
SDK is distributed as closed binary which makes troubleshooting trivial issues (see #88, #97, and #73) an impossible guess work.

**Expected outcome**
Beacon should open-source the SDK code. Your business model is selling SaaS platform that in no way dependent on keeping mostly UI code of the SDK secret.

HelpScout would offload majority of the trivial bug fixes to the community of active developers (such as myself) that use your SDK for their business critical apps. 

**Screenshots or GIFs**
Example of a trivial issue that could be fixed by community
<img width="366" alt="Screenshot 2020-09-02 at 13 15 09" src="https://user-images.githubusercontent.com/205317/91977685-4d9d1580-ed23-11ea-8ef2-25be4abd9dc4.png">

**Comment by NappyPirate** [comment]
+1

**Comment by galo2002** [comment]
+1

**Comment by davidyoakum** [comment]
+1

**Comment by shaunmcilroy** [comment]
Hi folks,

Thanks for your interest in our Beacon SDK, and for any contributions you've made in reporting issues or highlighting previous issues raised by the development community. 

We have no plans to provide an open sourced version of our SDK, and our Mobile engineering team continue to work to resolve reported issues raised by the community in future SDK releases. In many of the cases on this board, including those referenced, subsequent SDK releases include fixes for new issues reported since the previous version was released. We'll continue to work on that cadence, and continue to set expectations accordingly in the comments of each issue.

If we have anything to announce in the future about such a change we'll keep this issue updated. I'll close this out for now, but we'll track interest over time -- and thanks again for raising asking the question @andreyz

**Comment by andreyz** [comment]
@shaunmcilroy is there a reason why you'd sacrifice mobile experience quality to keeping SDK closed source? Given recent high profile apps crashing to a random Facebook SDK bug, I don't trust HelpScout to deliver an SDK that wouldn't harm my app's performance. Not to mention privacy concerns over closed code framework.

**Comment by shaunmcilroy** [comment]
Thanks for your note, @andreyz  

We don't see our chosen path forward as one that sacrifices quality and/or velocity as our development team has many years of combined experience with developing on Android and iOS, but also in QA work to ensure each release is something you can be confident integrating with your own apps. 

The third party SDK bug you reference was unfortunate (I remember being unable to access Spotify), however there have been no issues of a similar scope across our platform in the past as reported by our [Status Page](http://status.helpscout.net/). On the topic of privacy, our Privacy Policy [outlined here](https://www.helpscout.com/company/legal/privacy/) should answer any questions you have internally on how we handle and process data.

It's also important to note that as our team also wrote the SDK that means they have the most familiarity with its codebase which greatly helps when triaging and correcting issues. We'd ask that you do trust in the ability of our engineers to support you and the Help Scout community in correcting any issues raised when integrating our SDK, while also adding new features over time. I can promise they are 100% dedicated to that mission.

While we have nothing to announce regarding your request to make our SDK code open source I can promise that the support we provide for our iOS and Android SDKs will continue to be delivered by the team to the best extent possible. Should we change our policy towards open sourcing our code in the future we'll be sure to update this card.

Thanks again for the request. Hope you have a great week!

**Comment by andreyz** [comment]
> We'd ask that you do trust in the ability of our engineers to support you

Trust is built on actions. Here's just a start of the list and the first and second ones are bug that crash the host app with normal use of the SDK. Need I say more?

* https://github.com/helpscout/beacon-ios-sdk/issues/102
* https://github.com/helpscout/beacon-ios-sdk/issues/100
* https://github.com/helpscout/beacon-ios-sdk/issues/103
* https://github.com/helpscout/beacon-ios-sdk/issues/94
* https://github.com/helpscout/beacon-ios-sdk/issues/101

These prove that development isn't fast enough (lagging behind already mainstream iOS technologies):
* https://github.com/helpscout/beacon-ios-sdk/issues/99
* https://github.com/helpscout/beacon-ios-sdk/issues/97

This is just not good enough for a paid product.
